### ISSUE TITLE
[REQUEST] favorite tab

### ISSUE THREAD

**Issue by Snypaz26** [Paperback-iOS/app#100]
**Description**
A clear description of the feature
 When a new chapter for your manga that u have in your library updates it give u a notification at the top I can click and to which manga has a new chapter like manga rock

**How would it improve the App?**
How would the feature improve the app?

**Additional context**
![FBBB92EC-7567-4F32-8496-3587C63BF94D](https://user-images.githubusercontent.com/64497251/80528637-407ead00-8964-11ea-822b-41ad6cc0113f.png)

**Comment by ConradWeiser** [comment]
In current versions of the application, the library view supports marking manga under categories. (Reading, Planned, etc.) - If these aren't enough for organization, you can create a custom category called 'Favorites' and view all of the manga in that list all in one place!
