### ISSUE TITLE
[REQUEST] Additional sync settings for sorting discrepancies

### ISSUE THREAD

**Issue by an0thercat** [Paperback-iOS/app#109]
For users who are sure they want to follow a certain action whenever there’s a discrepancy between MD and app (like _Follow locally_, _Use MD_, _Remove local manga_), automate these actions by having them as toggle options in the _Sync settings_.

**Comment by ConradWeiser** [comment]
Eventually, the Mangadex implementation as a tracker will likely be converted into the more generic tracker system which is planned in a later version of the application. This enhancement will likely be integrated/handled in the new system. Closing this for now, it's certainly on our roadmap, although in a little different of a form than what's described!
