### ISSUE TITLE
[REQUEST] Mangas list concerned by discrepancies

### ISSUE THREAD

**Issue by an0thercat** [Paperback-iOS/app#110]
When there are discrepancies, show a list of the mangas that are concerned.

**Comment by ConradWeiser** [comment]
Can you elaborate a little more on what you mean by a discrepancy between manga? Are you suggesting conflicts of a single manga between multiple sources?

**Comment by ConradWeiser** [comment]
Closing due to a lack of dialog - Manga Merging has been added in the alpha builds, which in my interpretation to this problem, will solve what you're suggesting!
