### ISSUE TITLE
Syncing manga list with kitsu

### ISSUE THREAD

**Issue by Ghajik** [Paperback-iOS/app#112]
**Description**
Simple syncing all the mangas we're reading with the kitsu servers since the mangadex doesn't contain all manga and sometime we read through other official sources like tapas.

**How would it improve the App?**
Would simply make things for us, no need to manually add them

**Comment by ConradWeiser** [comment]
Kitsu has a much nicer API than Anilists GraphQL!
[A proper RESTful system](https://kitsu.docs.apiary.io/#)

**Comment by buitim** [comment]
AniList would also be much appreciated as possible!

**Comment by ConradWeiser** [comment]
Consolidating tracker posts into one issue. Merging with the issue below and marking this as a dupe. It's on our roadmap!
https://github.com/Paperback-iOS/app/issues/187
