### ISSUE TITLE
[BUG] Line seperators on longview

### ISSUE THREAD

**Issue by Artesians** [Paperback-iOS/app#113]
**Describe the bug**
Line separators randomly on longview, seemingly no pattern to their appearance.

**To Reproduce**
View something in long view, every couple of pages, there should be a line separator that cuts across the manga.

**Expected behaviour**
It's supposed to be turned off.

**App Version**
Eg: v0.3-b3 and public.

**Screenshots**
https://cdn.discordapp.com/attachments/673606787714514964/705542733795950622/image0.png

**Comment by ConradWeiser** [comment]
Dupe of #50

**Comment by Artesians** [comment]
> 
> 
> Dupe of #50

Paper requested this one to be opened seperately

**Comment by FaizanDurrani** [comment]
Fixed with experimental reader
