### ISSUE TITLE
[BUG] Crash on auto refresh for recent updates list

### ISSUE THREAD

**Issue by acknologia** [Paperback-iOS/app#116]
**Describe the bug**
If a new update comes out while scrolling through the recent updates list. When the app auto refreshes it crashes the app

If possible if we turn off auto refresh it might fix the problem

**App Version**
Beta v0.3-b3.1

**Comment by ConradWeiser** [comment]
Bug seems to be solved in the latest public/patreon TestFlight version.
If you can somehow still replicate this on the latest version (and I'm somehow missing it) please feel free to reopen this issue!
