### ISSUE TITLE
[BUG] Paperback doesn't save settings for thumbnail size or chapter sort

### ISSUE THREAD

**Issue by Artesians** [Paperback-iOS/app#118]
**Describe the bug**
If you set your thumbnail size or default chapter sort away from medium/ascending, closing the app will take them back to default settings.

**To Reproduce**
Change your settings, close Paperback, open the app and changes won't save.

**Expected behaviour**
The settings should save on close/relaunch.

**App Version**
Eg: v0.3-b3.1

**Comment by FaizanDurrani** [comment]
Fixed in b8
