### ISSUE TITLE
[BUG] Chapters consisting of a single page won’t be marked as read

### ISSUE THREAD

**Issue by kin-patsu** [Paperback-iOS/app#119]
**Describe the bug**
Exactly what’s written in the title. The chapter won’t be marked as read in the app nor on MangaDex

**To Reproduce**
Open any chapter from a manga (the one I used is Handyman Saitou In Another World, ch 2, 9.5 and so on) If the chapter has a single page it won’t be marked as read no matter what

**Expected behaviour**
The chapter should be marked as read

**App Version**
 v0.3-b.3.1

**Comment by FaizanDurrani** [comment]
Fixed in b8.1
