### ISSUE TITLE
[REQUEST] Allow additional functionality in manga info screen

### ISSUE THREAD

**Issue by stan-snf** [Paperback-iOS/app#121]
**Description**
Allow to do a search/category search when clicking either the genre tags, or the author artist, or maybe even the scanlation group. This way, anyone can easily look at some of their favorite author's other works/other manga of the same genre/manga scanned by the same group.

**How would it improve the App?**
Improves ease of use when trying to discover new/related manga

**Additional context**
on request

**Comment by ConradWeiser** [comment]
This functionality is likely to come after Advanced Search is implemented!

**Comment by FaizanDurrani** [comment]
Added in 0.7
