### ISSUE TITLE
[BUG] Manga displays incorrectly on a fresh app boot with the Fancy Paged Reader Mode

### ISSUE THREAD

**Issue by Takanu** [Paperback-iOS/app#126]
**Describe the bug**
When you open the app for the first time, if your Reader Mode is set to Fancy Paged mode and you attempt to read any manga chapter the pages will display incorrectly - you’ll only be to see a sliver of them near the top of the screen (happens on both portrait and landscape).

The bug is fixed by changing to a different Reader Mode, then changing back to Fancy Paged mode.

**To Reproduce**
- View any chapter and set the Reader Mode to Fancy Paged
- Quit the app by closing it in the App Switcher/Viewer
- Relaunch the app and view any chapter from any Manga.

**Expected behaviour**
The Fancy Paged mode should display exactly as it does when you first change to that Reader Mode option.

**App Version**
Eg: v0.2.1-r1
Tested on iOS 13.5 Public Beta 2

**Comment by FaizanDurrani** [comment]
Fancy paged reader has been removed from the later versions of the app, it is advised to switch to the Paged reader.

**Comment by Takanu** [comment]
Can I ask why out of curiosity?  I love the tactile feel of the page flip </3

**Comment by FaizanDurrani** [comment]
The implementation had numerous issues and didn't really support double-page spreads.
I might bring it back later but it's been removed from the app until I make it again from scratch.

**Comment by Takanu** [comment]
Ah, understandable.  Thanks for the response and the great app.
