### ISSUE TITLE
[REQUEST] Language Display Enhancements

### ISSUE THREAD

**Issue by Takanu** [Paperback-iOS/app#127]
**Description**
Improve the way languages are displayed for each series by categorizing the available chapters by language when viewing chapters instead of displaying every language sequentially inside the chapters list.

Either:
- Show what languages are available when viewing the chapter list as a dropdown filter, so the chapter list only displays the language someone wants to read.
- When you attempt to view the chapter list, ask the user what language they want to view a chapter list for.

**How would it improve the App?**
- Would mean that the default app behavior of showing every language is more immediately useful for new users by showing the user what languages the manga has been translated directly on the front page for the Manga.
- Would mean that when you read chapters with multiple languages enabled, moving to the next or previous chapter doesn’t give you the same chapter you were reading but in a different language - the app should instead keep showing you chapters just for the language you requested.

**Additional context**
I think the behavior of showing all languages by default is a smart accessibility one and being able to show multiple languages at once for those people who are either studying Japanese and want that option displayed if they’re further in their studies and want to practice reading, or for those that speak multiple languages but not the most popular two languages for Manga (Japanese and English) where choosing the languages they can read gives them more reading options.

Currently however the app doesn’t do a good job of displaying that content as available languages instead just does it as a filter for the chapter list which makes it harder to browse and seamlessly read chapters.  A similar problem exists here with multiple translators having content displayed on the same Chapter List that could do with a similar kind of treatment.

**Comment by ConradWeiser** [comment]
In current versions of the application, in the settings menu, you can select what language you wish your chapters to be. 
Say, you choose English.
Any non-English chapters on any chapter list are filtered out and hidden from the user (with just a little label saying how many has been filtered out) - This way when you scroll sequentially through a manga, any non-english versions are skipped over.

I believe this covers what this enhancement is described to be!
