### ISSUE TITLE
[REQUEST] More Options For Reader

### ISSUE THREAD

**Issue by stummyhurt** [Paperback-iOS/app#129]
**Description**
More options to customize stuff like in Tachiyomi (screenshots in context)

**How would it improve the App?**
Customizable reader makes for a better reading experience

**Additional context**
Screenshots: https://i.imgur.com/K95BVU8.jpg https://i.imgur.com/s1fP2Y2.jpg
The feature that I especially miss from Tachiyomi is the ability to set the scale type to "Fit height" which makes the page fill the screen height-wise.

**Comment by FaizanDurrani** [comment]
The core idea for paperback is to have a simple manga reader with just enough customisation options to let powerusers customise it to suit their reading preferences but some of these options are just too niche and would quickly overwhelm the avg user.

For a specific option that you would like the app to have, please open a new issue, grouping multiple requests into one makes it hard to manage and keep track of them
