### ISSUE TITLE
[REQUEST] Set Default Reader Options

### ISSUE THREAD

**Issue by seansusmilch** [Paperback-iOS/app#130]
**Description**
The ability in the settings section to set default reader options and the ability to change reader settings on a per series basis

**How would it improve the App?**
Better reading experience.

**Additional context**

**Comment by KorewaWatchful** [comment]
I would also like to add that it would be nice if the app determined the best reader on first read, for example for manga set it to page reader and for manhwa set it to longstrip.

**Comment by ZeroHart** [comment]
I would like to add that even though saving the reading mode by series it would also be nice to modify the reading mode per collection.

**Comment by FaizanDurrani** [comment]
Added in 0.7
