### ISSUE TITLE
[REQUEST] Sort followed manga by when they were followed

### ISSUE THREAD

**Issue by MCnumi** [Paperback-iOS/app#131]
**Description**
Add a “Date followed” option to the sort button in the follows tab

**How would it improve the App?**
Most people follow a huge amount of manga at once that they want to check out later, but don’t remember their names. Adding this feature would be a nice addition to the current sorting system. 

**Additional context**
None

**Comment by ConradWeiser** [comment]
Addressed in a patch pending review. Thanks for the suggestion! It's a pretty solid idea.
