### ISSUE TITLE
[REQUEST] Select a Range of Chapters to Mark

### ISSUE THREAD

**Issue by stummyhurt** [Paperback-iOS/app#132]
**Description**
In the chapters list, selecting starting chapter, then tapping and holding another chapter would select all chapters in between it and the starting chapter inclusive.

**How would it improve the App?**
Much faster seletion of chapters to mark or download

**Additional context**
Video:
![ezgif-3-d819d1a848c9](https://user-images.githubusercontent.com/25081475/81223317-70a0fe00-8fab-11ea-8740-82d7dbe2a514.gif)

**Comment by FaizanDurrani** [comment]
This is already implemented in the beta builds.
