### ISSUE TITLE
[REQUEST] Easier way to download single chapters

### ISSUE THREAD

**Issue by SteveyVe** [Paperback-iOS/app#133]
**Description**
When viewing the list of all of the chapters of x manga, have a button that downloads the chapter that you want a lot easier and quicker. And an indicator to let you know which ones you've downloaded.

**How would it improve the App?**
It will make it quicker to download a small number of chapters, rather than clicking edit selecting the 1 chapter you want, then manage, and then finally queuing for the download, you can do it with a single button press.

**Additional context**
![image](https://user-images.githubusercontent.com/24597886/81362053-f311e680-90ad-11ea-9017-b03b0492daa7.png)
The "+" shows you can download the chapter
The check mark shows you have downloaded the chapter
(You can download the other chapters as well I was just too lazy to put more +'s and check marks)

**Comment by FaizanDurrani** [comment]
If you go into Edit mode you can pick and choose which chapters to download then tap "Manage" and queue them, it also shows which chapters are downloading with an icon next to the name.

**However**, do note that downloading is broken and **WILL** brick the app, you'll have to reinstall if this happens.
