### ISSUE TITLE
Separation Of Pages (Scrolling downwards) And Info while reading the manga

### ISSUE THREAD

**Issue by Sukicchi** [Paperback-iOS/app#135]
I use the scrolling when reading manga and it gets confusing if there is no separation between two pages. (It just looks like the whole manga is 1 page) maybe adding a black horizontal line after each page would help. Also while scrolling down you can put like tiny notifications to show that you are reading a new chapter. Like MR if you scroll from chapter 1 to 2 it shows “New Chapter” on a black text box.

**Comment by ConradWeiser** [comment]
Dupe of #113

**Comment by FaizanDurrani** [comment]
Option to add padding between pages added in experimental reader
