### ISSUE TITLE
Search Bar Suggestion 

### ISSUE THREAD

**Issue by Sukicchi** [Paperback-iOS/app#136]
It would make it easier to find Mangas if example I type “d” then all mangas with letter d come out then I continue with “d e m o n” then all mangas whit demon on title show up.

**Comment by AgreeToMyTerms** [comment]
Dupe of #19?

**Comment by Sukicchi** [comment]
AgreeToMyTerms Ya sorry didnt see the closed section this is my first time using GitHub. What does the closed section mean?

**Comment by AgreeToMyTerms** [comment]
Feel free to close the issue.

**Comment by FaizanDurrani** [comment]
Functionality by design
