### ISSUE TITLE
[BUG] Small navigationbar icons

### ISSUE THREAD

**Issue by tychoregter** [Paperback-iOS/app#139]
**Describe the bug**
Compared to other iOS apps Paperback seems to have smaller navigationbar icons than other apps like the App Store, Apple Music and other apps following Apples design language. 

**Expected behaviour**
I think the icon size should be just a tiny but bigger (72px on @3 devices)

**App Version**
I used v0.2 and v0.3 and it’s present on both (on multiple versions)

**Screenshots**
![0AE74CD8-73E8-4412-AA43-EBC4A63457B6](https://user-images.githubusercontent.com/37561890/81995444-acdafb00-964a-11ea-891f-ff2b3a2e4dcf.png)

**Comment by FaizanDurrani** [comment]
I don't control the icon size, SwiftUI does. So that's how Apple wants the icons to be in the tab bar

**Comment by tychoregter** [comment]
@FaizanDurrani you sure everything is working correctly? It might be using the @2 icon or something instead. Look at the difference in size between the App Store and Paperback, there’s definitely something wrong here. 
![DA4496D2-46F9-4B98-927B-F3891489D137](https://user-images.githubusercontent.com/37561890/81999646-085eb600-9656-11ea-8633-e1aaba7afa32.png)
![Uploading 8293FD43-CE09-40FB-80B5-8C950903B154.png…]()

**Comment by FaizanDurrani** [comment]
like I said, I am using the standard SwiftUI method. I am not explicitly giving a size.

Its the same implementation as this https://developer.apple.com/documentation/swiftui/tabview
