### ISSUE TITLE
[REQUEST] Adding back fancy paged reader

### ISSUE THREAD

**Issue by Aljarrash** [Paperback-iOS/app#141]
**Description**
Building the fancy paged reader again from scratch.

**How would it improve the App?**
Fancy paged is a wonderful way of reading manga because it gives your tablet/ phone a sense of realism, like you’re reading an actual manga.

**Comment by axeII** [comment]
This was great feature of paperback. Hopefully book/fancy mode will be back soon.

**Comment by FaizanDurrani** [comment]
That reader can not be adopted to be on par with the features of the normal horizontal reader so it will not be coming until we can somehow ensure feature parity between both types of horizontal readers
