### ISSUE TITLE
[REQUEST] proxy feature 

### ISSUE THREAD

**Issue by Renard88** [Paperback-iOS/app#143]
**Description**
Add proxy feature Inside the app cause some sources is not allowed in some countries  

**How would it improve the App?**
Proxy feature will help some people to read manga from not allowed sources not people can read all sources like telegram there is proxy feature inside the app 

**Additional context**

**Comment by ConradWeiser** [comment]
For sources which are blocked in other countries, I plan on forking each relevant source into a Redirector version as well.
A redirector version may be slightly slower than the normal source (less than a second of difference, most likely), but will automatically circumvent this block. 

If there are any sources that are added which fit this criteria, an issue may be opened on the [Extensions Github project](https://github.com/Paperback-iOS/extensions) and it can be taken care of there.

Note that this isn't any rejection or approval of this request, that's papers business. Simply stating that this is being addressed in other locations as well!
