### ISSUE TITLE
[BUG] Saving Backups/Saving Source Logs crash

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/app#145]
**Describe the bug**
Attempting to backup manga to a .json, or choosing the option to share source logs causes a crash.
Upon investigation, when navigating to the 'files' application, Paperback never creates a file for itself upon installation, nor does one show up after you tell it to save something.

**To Reproduce**
* Install paperback
* Verify there is no Paperback directory in your files app
* Open Paperback, tell it to save MangaDex's source logs
* Crash
* Open Paperback, add something to a watch list, tell it to backup
* Attempt to open backup, or move it
* Crash

**Expected behaviour**
Paperback to save things to the filesystem

**App Version**
Beta v0.3.0-b7

**Comment by ConradWeiser** [comment]
Note that I use an iPad, as it's been mentioned that this error may be device specific.

**Comment by FaizanDurrani** [comment]
Fixed in b8
