### ISSUE TITLE
[BUG] Oneshot consistency

### ISSUE THREAD

**Issue by IonCannon218** [Paperback-iOS/app#147]
Oneshots within a series are tagged as chapter 0 on MangaDex and shows up before chapter 1, but the oneshot shows up on the top of the chapter list next to the most recent chapter in Paperback. This is mostly a QoL thing.

**To Reproduce**
Go to any series with a oneshot. I used Jahy-sama wa Kujikenai!

**Expected behaviour**
Mangadex lists the oneshot before chapter 1: 

**App Version**
Eg: v0.3.0-b7

**Screenshots**
Mangadex: https://media.discordapp.net/attachments/676014470316949504/714586914677719120/Screenshot_20200525-221304432_1.jpg
Paperback: https://media.discordapp.net/attachments/676014470316949504/714586400145539162/image.png

**Comment by FaizanDurrani** [comment]
This is just how the sorting works, can't do much about it
