### ISSUE TITLE
[BUG] Crash when typing in "solo"/"level"

### ISSUE THREAD

**Issue by Artesians** [Paperback-iOS/app#151]
**Describe the bug**
Search for "solo," or "level," likely referencing "Solo Leveling" will crash the app. 

**To Reproduce**
Search for "solo," or "level," and the app will crash. To avoid it, you can type "Lev" and search for the title.

**Expected behaviour**
It's not supposed to crash o:

**App Version**
Eg: v0.3.0-b7

**Comment by FaizanDurrani** [comment]
Fixed in b8
