### ISSUE TITLE
[REQUEST] Improve the discovery by adding "All" tab 

### ISSUE THREAD

**Issue by P2ON** [Paperback-iOS/app#152]
**Description**
Actually it's kinda hard to search for a new manga to read when you don't know what you want. We are quickly limited by what is offered in the different sources and the different suggestions like "Popular manga manga update" "recently updated" "new titles" etc.. 

It'd be great to have a list of all the manga with a "All" tab in discovery. Sort them by rank or name. The best exemple is still MR, it wasn't perfect caused it was limited at some point (it showing 24K mangas but scrolling from top to down, there wasn't 24K It seems to me that...) 

**How would it improve the App?**

Not be restricted in your choices with only suggestions, just scroll freely until you find the title or picture that will catch your attention, maybe get you to read the synopsis and after read the manga. More Freedom in the Search for the Holy Grail.

**Additional context**

![101526691_244057420231158_1620924127843975168_n](https://user-images.githubusercontent.com/64808472/83584449-7e648780-a547-11ea-9397-b677aee93855.jpg)

Ps : Sorry for my english, i tried my best !

**Comment by ConradWeiser** [comment]
Reference matching request on the PaperbackIOS\Extensions repository [Issue 68](https://github.com/Paperback-iOS/extensions/issues/68), I think this feature would be a great addition!

**Comment by P2ON** [comment]
I hadn't seen your post because I was searching by title and hadn't understood the meaning of the title due to my low level of understanding! 

You summed it up better than I did. Ahah

Having a page for each source it would be really cool. 

It kinda hard for me to imagine out of the « MR box » to make a better proposal and make a better feature than MR. I’m stuck with all the features that was given to us all these past years.

**Comment by ConradWeiser** [comment]
The source abstract class has been updated with a method to handle this. A `Get the entire website directory` function. - We're part way there. 
I'll close this issue once it's implemented properly in the app!

**Comment by FaizanDurrani** [comment]
Instead of an 'all' tab, sources can now provide Genre/Tags to Paperback which will be show in discover.
