### ISSUE TITLE
Crash when sort by last updated

### ISSUE THREAD

**Issue by mysteryduuude** [Paperback-iOS/app#153]
So I accidentally sorted by last updated on my library page to test the different sorting choices, when last updated made my app crash. I can still open the paperback app, but once I hit the library page, the app crashes and I can't access anything from that page. Any idea on how to fix it for the time being?

**Comment by alaa13212** [comment]
Happened to me to. I'm using latest build on iPad Air 2

Best I could do was delete and reinstall the app

**Comment by ConradWeiser** [comment]
Fixed in the current builds!
