### ISSUE TITLE
[BUG] v0.3.0-b8 Paged reader does not mark chapters as read when reach last page

### ISSUE THREAD

**Issue by Mirozuki** [Paperback-iOS/app#156]
**Describe the bug**
Using paged reader on the b8 version does not mark chapter as read after reading the last page.

**To Reproduce**
Open any manga with paged reader and swipe to last page 

**Expected behaviour**
Chapter should be marked as read when reaching last page.

**App Version**
v0.3.0-b8

**Comment by FaizanDurrani** [comment]
Fixed in b8.1
