### ISSUE TITLE
[REQUEST] Page slider

### ISSUE THREAD

**Issue by jason3580** [Paperback-iOS/app#157]
Description
A slider at the bottom of the reader which you can move to navigate pages similar to the one in Apple Books for example.

How would it improve the App?
Navigating pages in a chapter currently is limited to pressing the forwards and backwards buttons which is slow. A page slider can help quickly move to a new page if you wanted to view a certain page again.

**Comment by FaizanDurrani** [comment]
Implemented in 0.7
