### ISSUE TITLE
[REQUEST] Hide home bar

### ISSUE THREAD

**Issue by aidud** [Paperback-iOS/app#158]
**Description**
Hide the Home Bar inside the App. Could be done automatically, through a switch in Settings or in a similarly convenient way.

**How would it improve the App?**
Improve screen real state and readability when the bar covers text or drawings.

**Additional context**
I've never done any IOS development, but I'm guessing it should be fairly simple, probably just setting a system flag.

**Comment by FaizanDurrani** [comment]
Duplicate of #101
