### ISSUE TITLE
[BUG] Next chapter buttons reversed

### ISSUE THREAD

**Issue by SungJinWoo-SL** [Paperback-iOS/app#160]
**Describe the bug**
The buttons to switch chapters in the reader are reversed

**To Reproduce**
Use the buttons at the bottom to go to the next chapter while reading

**Expected behaviour**
What they do now but reversed

**App Version**
v0.3.0-b8.1.2

**Screenshots**
![image](https://user-images.githubusercontent.com/56172528/85573485-f16f9400-b603-11ea-8e1b-e0999ba2eb44.png)
![image](https://user-images.githubusercontent.com/56172528/85573523-f92f3880-b603-11ea-94a4-ec8147a80441.png)

**Comment by SungJinWoo-SL** [comment]
The first chapter is chapter 2 and pressing the right button at the bottom goes to chapter 2

**Comment by ConradWeiser** [comment]
This fix is implemented and is pending review, thanks for the bug report!
