### ISSUE TITLE
[BUG]View All on the front page does not work

### ISSUE THREAD

**Issue by WillD88** [Paperback-iOS/app#161]
**Describe the bug**
Whenever I press the view all button, nothing happens
**To Reproduce**
Steps to reproduce the behaviour
Press on the view all button on the discover page
**Expected behaviour**
I expected to see all of the manga that were updated
**App Version**
v0.2.1-r1

**Screenshots**

**Comment by FaizanDurrani** [comment]
Fixed in v0.2.2
