### ISSUE TITLE
[REQUEST] Ability to zoom out while viewing manga

### ISSUE THREAD

**Issue by cmxepa** [Paperback-iOS/app#163]
Hello,
My one and only issue with the app at the moment is that you cant zoom out while reading manga. To illustrate what I mean, here's how I prefer to read manga on [Tachiyomi](https://media.discordapp.net/attachments/368510197150253068/725697298126078052/Screenshot_20200625-230001.png), and here's the only way I can read manga on [Paperback](https://media.discordapp.net/attachments/368510197150253068/725698076328591422/IMG_1547.PNG?width=2248&height=1038). It's a lot more comfy to read when I can zoom out enough that panels arent cut off at the top and bottom. This is made much worse when trying to look at any longer panels [(example)](https://media.discordapp.net/attachments/368510197150253068/725703007731318846/image.png?width=2248&height=1038). Preferably I'd be able to pinch to zoom out, but just having a custom padding option somewhere would still be a pretty good improvement for me.

Also while I'm here, I might as well ask for the bar at the bottom to be hidden while reading manga (which can be seen earlier in my screenshot).

That's all, thanks.

**Comment by FaizanDurrani** [comment]
Added in Alpha as "Pillarboxing"
