### ISSUE TITLE
[REQUEST] Add some URL Scheme

### ISSUE THREAD

**Issue by FramboisePi** [Paperback-iOS/app#164]
**Description**
We could add the following URL Scheme:

* `paperback:repo?url="https://conradweiser.github.io/extensions"`
* `paperback:source?id="MangaDex"`

And eventually some URL to access a particuliar manga, or a featured selection when they will be implemented.

**How would it improve the App?**
It would allow to add "install" buttons on the website and in the sources repos. It would also allow user to add a repo without having to type the entire URL.

**Comment by ConradWeiser** [comment]
Implemented in an upcoming patch, thanks for the idea!
