### ISSUE TITLE
[REQUEST] "Help" button on the repository settings page

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/app#169]
**Description**
A help button on the repository settings page, where when selected, automatically brings the user to the Paperback website explaining how to add repositories.

This page also has a list of all 'known' repositories, so if someone doesn't know how to use the app, the help button will give them all of the information they need.

Possible con: The website has a list of all 'known' repositories. Will Apple allow this given the contents of some of them?

**How would it improve the App?**
This would aid the kind of user who doesn't do his research on Reddit/Discord/Wherever, and still wants to add additional repositories to the app either for 18+ purposes, or additional content.

**Comment by ConradWeiser** [comment]
Perhaps a more vague method of 'help' by pointing people to the website instead of having something in-app with details on how to go about this would be a better idea.

We definitely don't want to have keys to 18+ content directly in the app, Apple reviews might knock the application for something like that.

**Comment by FaizanDurrani** [comment]
Will not be implemented due to restrictions by Apple.
