### ISSUE TITLE
[REQUEST] next chapter improvement 

### ISSUE THREAD

**Issue by ShawnisShawnn** [Paperback-iOS/app#170]
**Description**
Make it so when you’re at the last page of a chapter and when you swipe to the next page it brings you to the next chapter. Instead of having to press the next chapter button
**How would it improve the App?**
Nicer continuous reading experience 
**Additional context**
Other than that great app

**Comment by ConradWeiser** [comment]
This is already implemented in the beta version of the app, and will surface on the AppStore version next update!

**Comment by ShawnisShawnn** [comment]
> This is already implemented in the beta version of the app, and will surface on the AppStore version next update!

Oh thanks I didn’t know that. That’s some pretty fast reply
