### ISSUE TITLE
[BUG] app crashes when pressing the follow button on any manga 

### ISSUE THREAD

**Issue by 3booo6** [Paperback-iOS/app#171]
when i try to follow any manga on the app, it suddenly crashes.
this still happens on the latest patreon supporter version and the app store one too.

**Comment by FramboisePi** [comment]
Hello @3booo6,

I'm pretty sure more information will be needed to understand what's happening. Would you mind adding your iOS/iPadOS version to the issue?

If you use an iPad with an iPadOS version prior 13.4, I suggest you to update it. You can read our faq section [App crashes when trying to follow on iPad](https://paperback.moe/help/faq/#app-crashes-when-trying-to-follow-on-ipad).

**Comment by 3booo6** [comment]
hi, i'm using my jailbroken iPad pro 10.5 inch on iOS 13.1.3, i wouldn't try to update it since i will lose my jailbreak but thank you for your suggestion

**Comment by ConradWeiser** [comment]
Marking this support request as completed, sorry about the version requirement! Paperback uses some tooling available only in the more recent versions of iOS.
