### ISSUE TITLE
[BUG] (iPad 5, 13.5.1) App Lags/Crashing When Scrolling Through Manga

### ISSUE THREAD

**Issue by Kevin-Middleton** [Paperback-iOS/app#173]
**Describe the bug**
The app is laggy when scrolling through different manga titles. The app has a good chance to crash when scrolling as well if you scroll quick enough.

**To Reproduce**
Go to Discover > Latest Updates > View All, Scroll through the manga here and there will be a stutter when doing so. The same applies for manga at Discover > Search > (Applicable Search Fields). Increasing the size of the thumbnails seems to reduce the stutter a little bit (Maybe 10% per size increase), but it's still very noticeable and will have a good chance of crashing with any size of thumbnail selected. Possibly a result of too many thumbnails loading at the same time. Might be best to set a limit to see if that helps.

**Expected behaviour**
Scrolling should be smooth. The app shouldn't crash.

**App Version**
v0.2.2 (Public App Store Release), iPad 5th Gen on 13.5.1 (Newly Updated)

**Comment by Kevin-Middleton** [comment]
Also crashes when horizontally scrolling manga from Discover Tab's main screen.

**Comment by FaizanDurrani** [comment]
Is this still the case in the latest Public TestFlight release?

**Comment by FaizanDurrani** [comment]
Closing due to no response and possibly fixed in the latest builds
