### ISSUE TITLE
[BUG] Manga thumbnails obscured in search results when using hentai exclusive filter in advanced search

### ISSUE THREAD

**Issue by MikeIsNewToTheCity** [Paperback-iOS/app#176]
**Describe the bug**
Searching for manga content using the advanced search with the hentai exclusive filter option selected, yields thumbnails in the search results that are obscured by the search results header at the top of the search results page. Only the first row of thumbnails is obscured.  This problem does not occur when setting the hentai filter to either “Exclude” or “Include”, only when setting it to “Exclusive”.

**To Reproduce**
Enter the Advanced Search and set the hentai filter to Exclusive and chose a keyword (I used Isekai).

**Expected behaviour**
When using the hentai exclusive filter it is expected that the top row of thumbnails in the search results will be fully displayed rather that partially obscured by the search results header, just as is the case when using the exclude or include option with the hentai filter.

**App Version**
Public stable release version (app store version): 0.2.2
iPad Air 2 with iPadOS 13.5.1

**Screenshots**
![E354A519-2664-4010-89DD-89C7ACE300CA](https://user-images.githubusercontent.com/22383229/86557507-f72a7b00-bf1b-11ea-892e-e06fafce5968.png)

**Comment by ConradWeiser** [comment]
Hi @MikeIsNewToTheCity, Advanced Search is not supported at the moment. The public TestFlight version of the App has had that feature disabled for quite a long time, and the version you're on currently is no longer supported.

Worry not, Advanced Search will return in the future! It simply needs some refinement. 
Sorry for the inconvenience, stick around, and the feature will be back!
