### ISSUE TITLE
[BUG] Exporting source logs causes a crash

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/app#177]
**Describe the bug**
When navigating to the 'Export Source Logs' section of a source, tapping the export button causes the app to crash.

**To Reproduce**
Settings --> Sources --> Any Source --> Export Logs --> Crash

**Expected behaviour**
Source logs to be exported somewhere

**App Version**
Reported to occur by multiple users on both Alpha builds, and the current Beta build.

**Comment by FaizanDurrani** [comment]
Is this fixed in the recent builds?

**Comment by ConradWeiser** [comment]
It appears so! Fantastic~
