### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cream-png** [Paperback-iOS/app#178]
**Describe the bug**
Whenever I am reading manga and I try to swipe up on my iPhone 11 to use the gesture that lets you go between apps but it takes multiple swipes. Compared to other apps you need to pull up from the bottom and all the way to 60-65 percent up on the screen just to use the gesture without fail. Normally its very quick and you just need to swipe up without holding your figure on any other app.

**To Reproduce**
Open up any manga, I am mainly reading webtoons. So open up a vertical webtoon to reproduce easier.

Secondly scroll a little bit and hide the interface, be in reading mode without any ui in the way.

Attempt to swipe up on an iPhone that has a fullscreen display and you will get some haptic feedback unless you pull your finger all the way up.

(This also works with the ui in the way but it can be managed by doing it twice. But without the ui sometimes I swipe like 10 times until the gesture works. 

**Expected behaviour**
Was mentioned before but the gesture should be quick and let me get out of the app quicker.

**App Version**
0.3.0 (10.0.7)

**Comment by HellDuke-Astaroth** [comment]
This is isn't a bug, and more a setting that Paper has turned on to prevent people from accidentally closing the app while scrolling and reading. Idk if that will be changed back to one swipe, but for the moment, it's how the home bar works.

**Comment by cream-png** [comment]
Ok, good too know. Was a bit annoying but its something that I could get used to.
