### ISSUE TITLE
[BUG] Chapter Skipping

### ISSUE THREAD

**Issue by Nobody196** [Paperback-iOS/app#181]
**Describe the bug**
If a manga goes up in a decimal for example 1.0 to 1.5 to 2.0 it will skip from 1.0 to 2.0

**To Reproduce**
Set Manganelo as the source and "Rebirth of the divine doctor" as the manga. Start from chapter 1 and click next which will take you to chapter 2, skipping 1.5 which includes a third of chapter 1's content.

**Expected behaviour**
It should go to the next number which is 1.5 instead of the next full number which is 2, skipping if it was actually a filler can be done by the user with another next chapter tap

**App Version**
v0.3-b10.0.7

**Comment by FaizanDurrani** [comment]
Bug with the Manganelo source, open an issue at https://github.com/Paperback-iOS/extensions
