### ISSUE TITLE
[REQUEST] Go to manga page from the history tab

### ISSUE THREAD

**Issue by P2ON** [Paperback-iOS/app#183]
**Description**
Be able to go to the manga page by clicking on its name from the history tab or/and maybe directly from the reading/lecture mode

**How would it improve the App?**
It will be easier to find a manga you are reading and add it to your favorites list.

**Additional context**
I discover a manga, I read it over several days and I would like to add it to my list. I'm looking for it in the discovery tab since I have the name but I only have the image but not the source to find the right one. I'm trying several with the corresponding image but some sources have less chapter. I have to check in the chapters if there is the same number I read and if they are already read in grey.

**Comment by ConradWeiser** [comment]
Implemented and is pending review!

**Comment by ConradWeiser** [comment]
Implemented
