### ISSUE TITLE
Manga not available in search but available in updates and keeps loading [BUG]

### ISSUE THREAD

**Issue by omi-kun** [Paperback-iOS/app#184]
**Describe the bug**
There are certain mangas that do not show up when searched but appear in the updates when updated. The title is available in the updates, however when I press it keeps uploading.

Some titles that have the issue;
Naruto
Boku No Hero Academia
Mission; Yozakura
Mitama Security
SPY X FAMILY
Chainsaw Man

**App Version**
V.0.2.2

**Screenshots**
![D7B227A4-9D22-48BF-8F39-7B736BD28EE3](https://user-images.githubusercontent.com/69520027/89909775-7d636c80-dc00-11ea-87b0-e56137353548.png)

**Comment by HellDuke-Astaroth** [comment]
It appears you are on the public build, which has licensed titles such as boku no hero have been filtered out and removed from the app. It will still show in library, but is unreadable.

**Comment by omi-kun** [comment]
and is there anything I can do about it?

**Comment by ConradWeiser** [comment]
The current public build has support for loading external sources into the application! (Manganelo, MangaFox, etc.) - Try using one of those, except for MangaDex. Titles which were previously unavailable should be available for you then! 

Feel free to reopen this if you still have issues, although it should be relatively simple on the latest version!
