### ISSUE TITLE
[REQUEST] Select Downloading chapters

### ISSUE THREAD

**Issue by omi-kun** [Paperback-iOS/app#185]
**Description**
We cannot select many chapters to download at the same time and having to select chapter by chapter is quite tiring tbh. So we'd really appreciate being able to select many chapters to download instead of going one by one.

**How would it improve the App?**
more convenience.

**Comment by FaizanDurrani** [comment]
You can bulk select select chapters by going into edit mode and selecting "Select Inbetween"
