### ISSUE TITLE
[BUG] app crashes

### ISSUE THREAD

**Issue by omi-kun** [Paperback-iOS/app#186]
**Describe the bug**
As soon as I enter the app it crashes. Tried restarting and still not working.

**App Version**
v0.2.2
iOS 13.6

**Comment by FramboisePi** [comment]
Hello @omi-kun,

It may be more a question for the Discord support channel. Could you have maybe tried to download a manga? There is an issue on `v0.2.2` build with the download function that break the app...

A new public build (`v0.3.0-b10.0.13`) was released yesterday and is available on TestFlight. It should probably solve your issue. 
I suggest you to try it, you will find update instructions in the `#release` channel of [Paperback Discord server]( https://discord.gg/Ny83JV3).

**Comment by omi-kun** [comment]
what am I supposed to type here?![image](https://user-images.githubusercontent.com/69520027/89999734-42187a80-dca0-11ea-9242-c2c179d4e6ee.png)

**Comment by FramboisePi** [comment]
You don't need to redeem a code.

Just remove every Paperback version already installed (if you want you can sync your library before to be able to restore it). Then you can open the following link and install Paperback.

---

Install instructions:
- REMOVE EVERY OTHER VERSION OF PAPERBACK
- Download the TestFlight app from App Store
- Accept the invite by going here https://testflight.apple.com/join/hLKHUuEr
- Install Paperback from the TestFlight app
