### ISSUE TITLE
[BUG] Certain manga gets ignored in search and can't be followed locally

### ISSUE THREAD

**Issue by SuzumiSou** [Paperback-iOS/app#190]
**Describe the bug**
Certain manga won't show up in a search and can't be followed locally by syncing MDlist.

**To Reproduce**
Search for "Hanging out with a gamer girl" (ID:  42490).

Or

Add "Hanging out with a gamer girl" (ID:  42490). to MDlist.
Open paperback and click "sync list with MD"
Click "Follow locally" in the "manga not followed locally" prompt.

**Expected behaviour**
The manga will show up when searched / The manga gets followed locally.

**App Version**
v0.3.0-r10.0.13

**Related**

*"Restricted manga"*
I have read the paperback faq and noticed this https://paperback.moe/help/faq/#i-can-t-find-x-manga-but-it-s-on-mangadex where "restricted manga" is mentioned. However, I can't find any information online about mangadex restricted manga.
This issue #44 shows a similar situation but it's marked as fixed.

**Comment by DanielKovalevich** [comment]
It isn't so much that it is restricted, as it is just licensed and unable to be linked with MD. The solution would be to use another source for that manga.

**Comment by ConradWeiser** [comment]
If a title is not showing up in the Mangadex Source on the app, but is showing up on the website, check if the manga is owned by Viz Media. Their content is blacklisted from the MangaDex source. 
Such content might be available on other sources, though! 

Implementation of Anilist and other trackers are in the works, so a more robust version of MDlist should be on it's way, which will be able to handle manga from all sources. 

Feel free to reopen this if you still have any questions, although for the moment, what's listed is known, and unfortunately not a bug. I definitely encourage you to look into Manganelo or another option.
