### ISSUE TITLE
[BUG] Blank screen when opening manga chapter

### ISSUE THREAD

**Issue by Taeoblood** [Paperback-iOS/app#191]
**Describe the bug**
Blank screen when I open any manga chapter

**To Reproduce
Click on any manga chapter and will take me to a blank screen. 
**Expected behaviour**
To read the manga

**App Version**
0.2.2

**Screenshots**
![52397C19-A316-4946-BFC6-38C4BCD563B8](https://user-images.githubusercontent.com/70485852/91666897-40371f80-eac6-11ea-8e8d-f1353b88a878.png)

Every chapter I try to click on sends me to a blank screen it’s overlayed on the screen so I can close it unless I close the app altogether. I haven’t been able to read a single chapter on the app. I tried switching between horizontal and vertical views but no luck.

**Comment by DanielKovalevich** [comment]
Are you still able to reproduce this?

**Comment by FaizanDurrani** [comment]
App Store build is broken grab the public TestFlight build from the Releases channel in the Discord Server
https://discord.gg/Ny83JV3
