### ISSUE TITLE
[BUG] Notifications

### ISSUE THREAD

**Issue by omi-kun** [Paperback-iOS/app#192]
**Describe the bug**
Well I used to get notified of an update as soon as the manga updates but now I get notifications once a day, not including all updated mangas when I used to get notifications all day. so I refresh the library and see it.

**App Version**
v0.3.0 (10.0.13)

**Comment by DanielKovalevich** [comment]
Notifications are currently done in bulk. There many be a feature down the pipeline that will allow for more timely updates.

**Comment by ConradWeiser** [comment]
Notifications have been augmented and updated in later versions of the application. There are some limitations of background updates which are enforced by Apple, we're doing our best to keep that in check.
