### ISSUE TITLE
[REQUEST] the ability to save and crop panels/pages to the cameral roll

### ISSUE THREAD

**Issue by phanrandy31** [Paperback-iOS/app#193]
**Description**
the ability to save and crop panels/pages to the cameral roll
**How would it improve the App?**
More features, easier to use than having users use ios's built in screenshot tool and crop which is horrible to use as it includes ui

**Additional context**

![](https://cdn.discordapp.com/attachments/728672233639116871/751988113986945044/image0.png)

![](https://cdn.discordapp.com/attachments/728672233639116871/751988114595250286/image1.png)

**Comment by FaizanDurrani** [comment]
Dupe of #137
