### ISSUE TITLE
Library search is case-sensitive

### ISSUE THREAD

**Issue by alaa13212** [Paperback-iOS/app#194]
**Describe the bug**
Search in library page is case-sensitive 

**To Reproduce**
Searching for manga title that is all caps like "NEW GAME!"
If you type "new" or "New" it will not show up

**Expected behaviour**
All mange with "new" in their name will show, regardless of capitalization

**App Version**
v0.3.0-r10.0.13
I'm on iPadOS 14.0 Beta 8

**Screenshots**
None

**Comment by DanielKovalevich** [comment]
What sources does this affect?

**Comment by alaa13212** [comment]
Search in "Discovery" tab works for all sources I use, regardless capitalization
This issue. affect "Library" tab when I filter manga I already follow

**Comment by ConradWeiser** [comment]
Addressed in an upcoming patch, thanks for the bug report!
