### ISSUE TITLE
[REQUEST] Manga merging from different sources

### ISSUE THREAD

**Issue by tejassharma96** [Paperback-iOS/app#195]
**Description**
Neko, an Android Mangadex client (https://github.com/CarlosEsco/Neko) has a feature that lets you merge from another source for a specific manga if it's only partially available on Mangadex. I'm sure I'm oversimplifying it by wondering whether it's possible to easily port that logic over to Paper, but it would be really cool to have.

**How would it improve the App?**
Mangadex has extremely high quality translations, but often it doesn't have every chapter in a manga (due to legal reasons I assume), and it would be great to use those high quality, scanlator group-approved versions of the manga when possible, but then use another source for the remaining chapters.

**Additional context**
Missing manga between chapters 87 and 122  
![Screenshot_20200919-165432](https://user-images.githubusercontent.com/8764853/93691383-5454b800-fa99-11ea-835a-820be3fb262e.png)

Merge popup to select manga to merge with   
![Screenshot_20200919-165440](https://user-images.githubusercontent.com/8764853/93691394-70f0f000-fa99-11ea-83c8-a1c40e09db40.png)

Merged manga, with the scanlator group replaced by "Merged Chapter" and all chapters available.   
![Screenshot_20200919-165449](https://user-images.githubusercontent.com/8764853/93691438-02606200-fa9a-11ea-862f-4d17519f78d1.png)

Apologies if this has already been requested, I did a quick search and didn't find anything.

**Comment by ConradWeiser** [comment]
That's certainly a neat idea by Neko, although Paperback is trying to get away from centralizing around MangaDex. Ideally, the app will not be focused on a single source. I'm not sure if a feature targeting just a specific source is something under consideration. It's F's call, I'm a little unsure about this one though.

**Comment by moonpen** [comment]
I guess it would be handy to have it let you know what other sources have the same title available regardless.

**Comment by ConradWeiser** [comment]
Manga Merging has been implemented in the current Alpha thanks to Paper! - The feature will trickle down to public releases on next release.

The feature implementation allows you to merge manga into a title present in your library. An ANY_SOURCE --> ANY_SOURCE transition, and is not constrained to just MangaDex

**Comment by tejassharma96** [comment]
That's awesome, thanks!
