### ISSUE TITLE
Please add some chinese sources

### ISSUE THREAD

**Issue by natonzyh** [Paperback-iOS/app#200]

**Comment by ConradWeiser** [comment]
Can you please link some Chinese sources which you’d like to see integrated? I am not aware of any good source fitting that criteria

**Comment by natonzyh** [comment]
thank you for your reply!!

Here are some sources:
https://www.manhuaren.com/
http://cocomanhua.com/
https://www.manhuadui.com/
https://www.manhuagui.com/
https://www.manhuadb.com/
http://dmzj.com/

**Comment by natonzyh** [comment]
And you can get many other language sources from android manga app “tachiyomi”.

**Comment by ConradWeiser** [comment]
I've moved this request over to the extensions-foreign board. 
We've recently redone how sources work, meaning that new sources are starting to become a higher priority again. Stay tuned!
https://github.com/Paperback-iOS/extensions-foreign/issues

**Comment by Aarson974** [comment]
Second that. Please change bainianmanga to manhuagui. The former have way less manga available and even classic(berserk, gto etc...) are not available, contrary to manhuagui.

**Comment by TheNetsky** [comment]
@Aarson974 please create a issue with your requested sites here
https://github.com/Paperback-iOS/extensions-foreign/issues
