### ISSUE TITLE
[BUG] Search

### ISSUE THREAD

**Issue by omi-kun** [Paperback-iOS/app#201]
**Describe the bug**
So after the latest update supposedly the search has improved since they're separating sources and all but it's not workin at all, I've searched a couple of mangas in all sources and it's still not showing results.

Eg: v0.3.0 (11.0.34)

**Screenshots**

![image](https://user-images.githubusercontent.com/69520027/96709239-78166100-13ab-11eb-8c27-b60af0aa09cb.png)

**Comment by FaizanDurrani** [comment]
Update sources from Settings > Source > Official repo
