### ISSUE TITLE
add option to crop borders and stretch and upscale to screen 

### ISSUE THREAD

**Issue by aarish21** [Paperback-iOS/app#202]
these feature will help getting more viewing area and also helpfull for small screen iphone

**Comment by nickdtsag** [comment]
I miss this feature so much from tachiyomi. All the wasted black bars or white empty (page) space in width gets cropped and you end up using much more screen real estate. Especially with the tall screens that phones have now, it makes a big difference.

**Comment by FaizanDurrani** [comment]
Can you provide an example of what you mean? It's not exactly clear from the less than ideal description.
Open another issue and follow one of the issue templates.

**Comment by stummyhurt** [comment]
I've created a similar request with a description and an example #232

**Comment by ConradWeiser** [comment]
Doing image processing on all of the pages loaded from the internet tends to be a more resource intensive task. There's no magic "Get rid of whitespace" function. You'd have to load and process each page as you see them. 

I'd have to look into how Tachiyomi does it, but it removes some of the 'simplicity' which we're aiming for with Paperback.
