### ISSUE TITLE
[BUG] DOWNLOADED CHAPTERS

### ISSUE THREAD

**Issue by omi-kun** [Paperback-iOS/app#203]
**Describe the bug**
after the latest update I can't access any of my downloaded chapters unless I remove them and if I try to download em again all pages are marked x red.

**Expected behaviour**
Fix the problem and be able to read downloaded chapters and download them.

**App Version**
Eg: v0.3.0

**Screenshots**
![image](https://user-images.githubusercontent.com/69520027/97085694-1e729880-1630-11eb-8973-2f63a5959712.png)
![image](https://user-images.githubusercontent.com/69520027/97085696-20d4f280-1630-11eb-9f95-e3f6ed8f9bcb.png)

**Comment by FaizanDurrani** [comment]
Switch to experimental reader from settings
