### ISSUE TITLE
[REQUEST] Background Manga Downloading

### ISSUE THREAD

**Issue by YourKalamity** [Paperback-iOS/app#205]
**Description**
Download items in queue with app in the background, unsure if this is possible with the way iOS aggressively puts apps to sleep, but an example of background downloading is Google Maps offline maps.

**How would it improve the App?**
Allows the user to do other things whilst manga is downloading

**Additional context**
None needed

**Comment by ConradWeiser** [comment]
Unfortunately with how iOS handles background tasks, this isn't possible.
If you are simply downloading ONE object, you are allowed to put the application to the background and it will finish there. I assume this is what Google Maps is doing. Downloading one bundle of some sort, and then extracting it when the app is started again.

You can validate this behavior yourself if you were to use Netflix or something, and were to tell it to download multiple pieces of media. The one which was started will finish, the others in the queue will not continue until the app has been opened again.

Sorry! Believe me, this has been talked about internally before with some of the QA members and other beta testers. We'd very much like this as well, though iOS is it's own beast, I suppose.
