### ISSUE TITLE
 Please add some vietnamese sources[REQUEST]

### ISSUE THREAD

**Issue by Huynh12345678** [Paperback-iOS/app#206]
**Description**
 Please add some vietnamese sources

**How would it improve the App?**
How would the feature improve the app?
it makes the app more perfect !

**Additional context**
http://nhattruyen.com/
http://truyen48.com/index.html
https://ln.hako.re/

**Comment by ConradWeiser** [comment]
I've moved this request over to the foreign extensions github board!
https://github.com/Paperback-iOS/extensions-foreign
