### ISSUE TITLE
[REQUEST] Add an "Updates" tab

### ISSUE THREAD

**Issue by Khavont** [Paperback-iOS/app#207]
**Description**
A tab which shows the most recently updated chapters would be really helpful, such as on Tachiyomi.

**How would it improve the App?**
Using the app would be a lot easier.

**Comment by ConradWeiser** [comment]
In the latest version of the app, in your library, the user can sort by 'Last Updated' - This brings all of the titles which were, as the title implies, last updated to the top of your list.

This accomplishes the same as having its own separate tab.
