### ISSUE TITLE
[REQUEST] Incognito Mode

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/app#208]
A toggle somewhere which will not log anything you search, or read in the search history, or reading history sections.

**Comment by ConradWeiser** [comment]
Incognito mode staged, pending review and possible feature evolution at https://github.com/FaizanDurrani/Paperback-Source/pull/28

**Comment by FaizanDurrani** [comment]
Added in version 0.4.0 (2.2.2-Beta)
