### ISSUE TITLE
[REQUEST] Orientation lock

### ISSUE THREAD

**Issue by vregat** [Paperback-iOS/app#209]
**Description**
Orientation lock button while reading

**How would it improve the App?**
While in landscape mode, the picture is too big to read. This button would allow readers lock the reading page in portrait mode.

**Additional context**
Low priority as it is possible to lock orientation system-wide. But it would me more convinient

**Comment by ConradWeiser** [comment]
Duplicate of https://github.com/Paperback-iOS/app/issues/91
It's on our backlog!
