### ISSUE TITLE
[REQUEST] Hide Discover/Search results based off of language filters

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/app#213]
**Description**
Currently, chapters on the MangaDetails objects are filtered based off language settings. Meaning if you are set to English only, and there are some Japanese chapters, the Japanese chapters will not appear in the list.

Sometimes (and more frequently), if a Manga is not English, all of the chapters are not English.

Implement functionality into the app, where when you're on Search/Discover pages, that if a manga has only filtered languages, it should be hidden completely instead of the view. (nHentai is a big offender here)

**How would it improve the App?**
Users browsing Manga will no longer see titles which have '0' chapters in them, due to language settings.

**Comment by FaizanDurrani** [comment]
This is not possible due to how the app works, at search there's no information about what type of chapters there are for a manga (that can only be known by querying the actual chapters most of the time).
