### ISSUE TITLE
[BUG] Library editing (select in library) not working properly 

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#215]
**Describe the bug**
When using the select system that was recently added, the app now firstly, does not bring up the menu (highlighting the apps manga in the library with the selectable circle) until you scroll down and then scroll back up which will then bring the menu up like it supposed to be. Secondly this menu then never goes away once you click done as it should, instead having you scroll down and then back up to fully clear it making the library go back to normal. This will still move selected manga to other tabs like normal which is expected behavior.

**To Reproduce**
1. Go to the library and at the top left tap edit and then select
2. Scroll down and then back up for the overlay to actually show up 
3. Clicking Done at the top left will not close the overlay 
4. After you've clicked done scroll down and then up to make the overlay disappear 
5. Selecting stuff and moving it will work 

**Expected behaviour**
The select overlay would normally show up immediately when pressing select and would go away normally once "Done" it hit instead of staying.

**App Version**
 v0.4.0 (2.0.2-Alpha)

**Screenshots**
[First video](https://cdn.discordapp.com/attachments/757959539051069591/798204709030199317/MUFN8522.MP4)

[Second](https://cdn.discordapp.com/attachments/757959539051069591/798204721592270848/video0.mp4)
Almost full bug video i'd watch both

**Comment by FaizanDurrani** [comment]
Fixed with v0.4.0 (2.0.4-Alpha)
