### ISSUE TITLE
[BUG] Search not exiting when scrolling

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#216]
**Describe the bug**
When searching in the library the keyboard does not disappear when you scroll after searching for what you want to find like the pre-promises patch. You need to select a manga or go into the tab editor to make it go away which is just leaving the page completely. 

**To Reproduce**
1. Go to the library
2. Search anything
3. Try and exit through scrolling
4. You can exit by selecting a manga or doing into the tab editor

**Expected behaviour**
You scroll keyboard goes away and it exits search

**App Version**
v0.4.0 (2.0.2-Alpha)

**Screenshots**
[Here](https://cdn.discordapp.com/attachments/757959539051069591/798219266565603338/video0.mov) is a video of this.

**Comment by ConradWeiser** [comment]
Potential fix staged, thanks for the heads up. I wasn't aware of this one. 
Will close this issue when the adjustment is merged into the dev builds.

**Comment by Ekomonster** [comment]
Fixed, but a better one is going to be implemented

**Comment by FaizanDurrani** [comment]
Better version implemented in the latest Alpha
