### ISSUE TITLE
[BUG] Manga width doesn't follow when rotating screen on iPad

### ISSUE THREAD

**Issue by NoaHimesaka1873** [Paperback-iOS/app#219]
**Describe the bug**
Manga width doesn't follow when rotating screen on iPad

**To Reproduce**
Turn the iPad while reading manga.

**Expected behaviour**
Manga should scale accordingly to horizontal resolution.

**App Version**
v0.4.0-r.1.0.3
Tested on iPad Pro (12.9-inch) (4th generation) running iPadOS 14.2

**Screenshots**
[Link to screen video recording](https://youtu.be/EQxKyYyERok)
![5ED160BE-1D8B-47CA-AA41-8ECD67F8DFD7](https://user-images.githubusercontent.com/39993457/104533209-4f71d080-5655-11eb-9629-bc422ccaec98.png)
![104AE53F-967D-4E71-91B1-846430B6D226](https://user-images.githubusercontent.com/39993457/104533239-58fb3880-5655-11eb-8f0e-b9d6594f364d.png)

**Comment by FaizanDurrani** [comment]
Fixed in alpha
