### ISSUE TITLE
[BUG] When using Select All, only selects Mangadex and not all on that tab

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#222]
**Describe the bug**
When using Select and then all from the bottom right, the app only selects manga from Mangadex and not all the manga on that tab. It can also seem really random at times but we think it's the only manga from Mangadex.

**To Reproduce**
1. Go to the library's 
2. Press edit top left
3. Press Select
4. Go to your all tab or a tab with manga not from Mangadex and some with
5. Press the bottom left
6. Tap all
7. It will not select all but only some

**Expected behavior**
It should select all the manga on the tab that you are on.

**App Version**
0.4.0 (2.0.6-Alpha)

**Screenshots**
[Here is a video](https://cdn.discordapp.com/attachments/704454488030969890/800134435231498310/video0.mp4)

**Comment by ConradWeiser** [comment]
I can't replicate this with a small library. I'll update this after trying it with something considerably larger.
