### ISSUE TITLE
[BUG] Content settings for H manga don't work.

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#223]
**Describe the bug**
When you go into content settings and select No H Both or Only H none of them do anything as you can still search and read H manga.

**To Reproduce**
1. Go to content settings
2. Select Hide H and save, an error will show up (a toast bottom of your screen)
3. Go to any H manga and it will show and be readable.
4. Same happened for the Only H setting it just does nothing 

**Expected behaviour**
Hide H should hide all H manga (not searchable or readable) and Only H should only show H manga

**App Version**
v0.4.0 (2.0.6-Alpha)

**Screenshots**
![IMG_3317](https://user-images.githubusercontent.com/48167942/104827069-fefe9c80-5827-11eb-9af0-17f3aae7c752.PNG)
![IMG_3316](https://user-images.githubusercontent.com/48167942/104827071-002fc980-5828-11eb-9aea-ee3ce51f78a9.PNG)
Imma not include a video cause its about H manga.

**Comment by Ekomonster** [comment]
Works now,

**Comment by Rhexia** [comment]
It works for me. I have some titles from nHentai (old repo).

Hide H, Show All, Only H works perfectly. (0.4.0 2.2.2 Beta)

**Comment by Ekomonster** [comment]
It does not seem to work with Mangadex perfectly, please take a look at the video.
[Here](https://discord.com/channels/673606787290759230/704454488030969890/807078386299568188)

**Comment by ConradWeiser** [comment]
The way that this is handled is getting rewritten. I'm attaching this to the 0.6 update milestone. This should be handled properly upon release.

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.2-Beta)
