### ISSUE TITLE
[BUG] Search working with only a few sources in when all sources chosen

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#224]
**Describe the bug**
Search does not work for the MangaNelo source and is incredibly slow with Mangalife
I'd say this needs a **bit more testing** to see if this is the case with other sources so please comment if anything is found.

**To Reproduce**
1. Make Manganelo the homepage and choose one manga you see
2. Search that manga
3. It should not show up
4. This also happened with Mangalife a lot but I have gotten it to show up

**Expected behaviour**
If it shows it on the homepage it should also show up in the search when the name is typed correctly 

**App Version**
v0.4.0 (2.0.6-Alpha)

**Screenshots**
[Here is a link to a video](https://cdn.discordapp.com/attachments/757959539051069591/800047722341072906/video0.mp4)

**Comment by FaizanDurrani** [comment]
Not an app issue
