### ISSUE TITLE
[BUG] Edit tab not working and temporarily blocks out half of the library

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#225]
**Describe the bug**
After editing the name of a tab and pressing the done at the top right it'll go back to the library but half the library will be blocked and the name of the tab will not be changed. A video is included as a very good visual of this at the end.

*Note: that if you press the done on the tab your editing and then done at the top right it will not cause this. 
**A video will be at the end to clarify**

**To Reproduce**
1. Go to the library
2. Go to the edit tab menu from the top left
3. Edit any tab
4. Press the done at the top right after your change thee name
5. DO NOT press the done on the tab your editing
6. You will be brought back to the library and it will be half blacked out and the tab will have its previous name 

**Expected behaviour**
After editing the name of the tab and pressing done the name of the tab should be changed when you are brought back to the library with nothing blocking the library

*Note: I see no reason why there are 2 "Done" one to leave the tab editing and one on the tab your editing. The one at the top right should function as both as the old build (pre-promises) 

**App Version**
v0.4.0 (2.0.6-Alpha)

**Screenshots**
[Video of the bug](https://cdn.discordapp.com/attachments/757959539051069591/800259520210665482/video0.mp4)
[Video of the note where the bug does not occur](https://cdn.discordapp.com/attachments/757959539051069591/800259525050761226/video0.mov)

**The second done I am talking about. Its on the tab you edit.**
![image0](https://user-images.githubusercontent.com/48167942/104833779-45282000-5869-11eb-8d7e-cb29e2e1dd0e.jpeg)

**Comment by Ekomonster** [comment]
Intended, mistake by me.

**Comment by FaizanDurrani** [comment]
Tab not being renamed if you don’t press “done” next to the tab is intended behaviour. A black overlay appearing in the library is a bug

**Comment by Ekomonster** [comment]
This is fixed from what I know.
