### ISSUE TITLE
[REQUEST] Dont bring up the source list every time you search

### ISSUE THREAD

**Issue by nar1n** [Paperback-iOS/app#227]
**Description**
Dont bring up the source list every time you search

**How would it improve the App?**
99% of the time you are already on the source you want to search it so bringing up the source list is redundant

**Comment by ConradWeiser** [comment]
Paper's been working on an alternative search page in the alpha. This should be solved by the addition.

**Comment by ConradWeiser** [comment]
System added to beta

**Comment by FaizanDurrani** [comment]
A new (experimental) search tab has been added to the version 0.4.0 (2.2.9-Beta) which improves upon the shortcomings of the previous searching method.
