### ISSUE TITLE
[BUG] Chapter Progress Does Not Update Unless Switching Tabs

### ISSUE THREAD

**Issue by BedHedd** [Paperback-iOS/app#228]
**Describe the bug**
The chapter progress will report a value of 1 if a user exits from the reader or marks a chapter as read. For this bug, it relies on having a user exit from the chapter

**To Reproduce**
Open a chapter either from the series or chapters tab, read a up to a desired page, close the reader using close button, check the page progress for value of 1.

**Expected behaviour**
The page progress should report the exact chapter when the user closes the reader. If a user switches between the series and chapter tab (and vice versa), the page progress will be updated on the switched tab.

**App Version**
Eg: v0.4.0-r1.0.3

**Screenshots**
![image](https://user-images.githubusercontent.com/27317528/105646122-b7999100-5e63-11eb-8938-04b96dea88a8.png)

**Comment by FaizanDurrani** [comment]
Fixed in alpha
