### ISSUE TITLE
[REQUEST]Add a marker when new chapters of a manga release

### ISSUE THREAD

**Issue by joshn77** [Paperback-iOS/app#229]
ex.
![4B300F3B-384A-4BB6-BFF5-204A3AC6A6BF](https://user-images.githubusercontent.com/77570347/105710744-7cc25680-5f52-11eb-93f6-3f009b29891a.jpeg)

**Comment by ConradWeiser** [comment]
Paperback already has badge notifications when an update of a manga comes out. 
For example, if a title has 2 new chapters, the manga tile (the image you tap on to navigate to said manga) will have a '2' icon on it in the same place you've shown off in your screenshot.
