### ISSUE TITLE
[BUG] Searching in Merge page is broken

### ISSUE THREAD

**Issue by kin-patsu** [Paperback-iOS/app#233]
**Describe the bug**
While merging series, searching for a manga won't filter the other manga nor give any result

**To Reproduce**
1. Open any manga
2. Tap "Merge"
3. Write anything in the search bar

**Expected behaviour**
Unrelated manga are filtered out while showing only related ones

**App Version**
v0.4.0-b2.2.3

**Screenshots**
![IMG_0539](https://user-images.githubusercontent.com/19828171/106981026-2676c400-6759-11eb-9e29-fb8c57ea6377.PNG)

**Comment by Rhexia** [comment]
Known issue from the Alpha version of the app.

**Comment by ConradWeiser** [comment]
Fix implemented in dev-build - Will close this when the feature trickles down to a beta release.

**Comment by FaizanDurrani** [comment]
Fixed in version 0.4.0 (2.2.9-Beta)
