### ISSUE TITLE
[BUG] Sort by name has some manga showing out of order

### ISSUE THREAD

**Issue by kin-patsu** [Paperback-iOS/app#234]
**Describe the bug**
While the library is sorted by name, a few manga will appear at the wrong place (example, a manga starting with H may appear among others starting with K)

**Expected behaviour**
Manga should be properly sorted

**App Version**
v0,4,0-b2.2.3

**Screenshots**
![IMG_0540](https://user-images.githubusercontent.com/19828171/106981512-085d9380-675a-11eb-9a17-cde4556645b7.PNG)

**Comment by ConradWeiser** [comment]
Thanks for the report! We'll look into it.

**Comment by kevin41714** [comment]
![774C9E72-7A44-4218-83E9-7CA0A5FFA157](https://user-images.githubusercontent.com/77117543/107854679-8d484d00-6deb-11eb-948f-cccc51e46b24.png)
Also having this issue, no idea why though

**Comment by NikiBelufski** [comment]
I have the same issue, but I also noticed that the order is wrong almost all the time for further letters. When the first letter is the same, the order should take the second, if same then keep going until a different letter and put them in order, but those that are grouped by the first letter are not always(rarely in fact) ordered properly considering the second or further letter.

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0
