### ISSUE TITLE
[BUG] Selecting manga glitches every cover

### ISSUE THREAD

**Issue by kin-patsu** [Paperback-iOS/app#236]
**Describe the bug**
While in Select mode, tapping on any manga will glitch every cover on the screen for about a second

**To Reproduce**
1. Go into Select Mode
2. Select any manga

**Expected behaviour**
Covers don't become white

**App Version**
v0.4.0-b2.2.3
**Screenshots**

https://user-images.githubusercontent.com/19828171/106983240-7a83a780-675d-11eb-91e9-78e27a5f586b.mp4

**Comment by Rhexia** [comment]
Known bug to the beta.

**Comment by Ekomonster** [comment]
Known bug.

**Comment by HellDuke-Astaroth** [comment]
Known bug.

**Comment by FaizanDurrani** [comment]
Fixed in version 0.4.0 (2.2.9-Beta)
