### ISSUE TITLE
[BUG] Scrolling in the history makes images unload and infinitely load 

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#237]
**Describe the bug**
Scrolling in the history makes images unload and infinitely load 

**To Reproduce**
Go to history and scroll down and then up, they will be loading infinitely and if they were loaded in they won't be there anymore and keep loading

**Expected behaviour**
Just load images like normal

**App Version**
v0.4.0 (2.2.2-Beta 

Note: this is in the list in alpha chat but I am adding it here for others

**Comment by ConradWeiser** [comment]
Fix implemented in a developers build, stay tuned
