### ISSUE TITLE
[BUG] Sort by last updates seems completely random

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#238]
**Describe the bug**
Sort by last updates seems completely random 

**To Reproduce**
Go to library and sort by "last updated"

**Expected behaviour**
Should order the manga by what time they were last updated

**App Version**
v0.4.0 (2.2.2-Beta)

Note: this is in the list in alpha chat but I am adding it here for others

**Comment by FaizanDurrani** [comment]
Fixed in version 0.4.0 (2.2.18-Beta)
