### ISSUE TITLE
[BUG] Stuff is mark as read and at the last chapter even when its not been read at all. 

### ISSUE THREAD

**Issue by Ekomonster** [Paperback-iOS/app#239]
**Describe the bug**
Manga's are marked as read with a page number being at the end as well even when it's not been read at all. 

Also, when stuff has been read it'll be unread, and when u go to all chapters and back it'll turn back to normal.

**To Reproduce**
Go to a manga that you have read before and when its updated, go to it and even if you have not read the lastest chaper it'll be marked as read and with what I think is the previous chapters progress.

**Expected behaviour**
If it has not been red it should be white (unread) with no progress

**App Version**
v0.4.0 (2.2.2-Beta)

Note: this is in the list in alpha chat but I am adding it here for others

**Comment by FaizanDurrani** [comment]
Added in 0.7 Build 16
