### ISSUE TITLE
[REQUEST] Bookmark System

### ISSUE THREAD

**Issue by DarkSxarlet** [Paperback-iOS/app#245]
**Description**
If it’s not to much trouble, would adding a page/chapter bookmark system be possible ??

**How would it improve the App?**
I don’t know about improving but I think bookmarking a favourite moment/chapter
would be great

**Comment by ConradWeiser** [comment]
The last time I had a conversion with @FaizanDurrani about this, page/chapter bookmarks is likely out of scope of Paperback. I'm not sure if we plan on implementing this. 
I'll leave the issue open for a tad longer to ensure that this decision is final.

**Comment by TheNetsky** [comment]
Dupe of https://github.com/Paperback-iOS/app/issues/159 :)
