### ISSUE TITLE
[REQUEST] Filter/Sort by Source

### ISSUE THREAD

**Issue by kevin41714** [Paperback-iOS/app#248]
**Description**
The ability to filter/sort your library by their source

**How would it improve the App?**
With the manganelo fiasco on top of the discontinuation of mangasee, I'd like to suggest being able to filter/sort your library by source. 

Currently if your library is using different sources, there's no way to distinguish the affected manga if you wanted migrate to another source, other than pulling the manga names from the code of the JSON Backup which is a convoluted and messy method. It seems apparent to me that there needs to be a better way.

Being able to filter by source would be a much more streamlined fix, on top of just being a good QOL I'd personally use a lot.

**Comment by unkn0wn234** [comment]
Technically, in the current Beta with the ability to create your own tabs and organize your library you could just create tabs for each source. Just a thought not trying to say your idea isnt valid or anything

**Comment by FaizanDurrani** [comment]
The feature to sort using sources is planned, however, since the current library has no relation with sources it might bring heavy performance impacts for the lookup. Unless this performance impact is resolved it is not possible to implement this.

Will be put on hold until further notice.
