### ISSUE TITLE
[BUG] Unsyncing Ghost Manga

### ISSUE THREAD

**Issue by kevin41714** [Paperback-iOS/app#252]
**Describe the bug**
When attempting to sync my library with Mangadex, there will always be 3 manga that it will say are not followed locally but upon attempting to follow locally, no manga will actually be added.

The 3 manga are always there but syncing other manga works fine, e.g. I have 20 manga I just followed on Mangadex, during syncing it would say there's 23 manga that aren't followed locally, but after the sync only 20 manga would be followed.

**Expected behaviour**
I am unsure on whether there's actually 3 manga in my Mangadex list that just aren't carrying over to Paperback, or whether the app just thinks there's 3 missing from the library but they're actually synced properly. 

I'm leaning on the former because I've already confirmed one manga is not carrying over from Mangadex to Paperback, Yakuza Reincarnation. Talked about it in Discord here: https://discord.com/channels/673606787290759230/702052855623843861/806940963024273418

Was going to go through my library to cross reference and see if I could find the 2 other manga missing but I'm also suffering from the bug where Sorting by Name isn't showing in order (https://github.com/Paperback-iOS/app/issues/234) so haven't been able to do that

**App Version**
v0.4.0 (2.2.9-Beta)

**Comment by ale-ben** [comment]
Same issue here, I follow 4 mangas on MD, 1 of them sync without problems, the other 3 won't sync.
The app will prompt me to follow locally but upon clicking it nothing will happen.
Tried on 3 different devices (iPad Air 2 gen, iPad air 3 gen, iPhone 11 Pro) all with the latest iOS.

Working manga: [Solo Leveling](https://mangadex.org/title/31477/solo-leveling)
Not working manga: 
- [Dr. Stone](https://mangadex.org/title/20882/dr-stone)
- [Funouhan](https://mangadex.org/title/13033/funouhan)
- [Kaifuku Jutsushi no Yarinaoshi](https://mangadex.org/title/21758/kaifuku-jutsushi-no-yarinaoshi)

None of those are with N tag.
Tried following the guide on your troubleshooting but no result.

App Logs: 
[27-02.Paperback.txt](https://github.com/Paperback-iOS/app/files/6055193/27-02.Paperback.txt)

**Comment by Rhexia** [comment]
> 
> 
> Same issue here, I follow 4 mangas on MD, 1 of them sync without problems, the other 3 won't sync.
> The app will prompt me to follow locally but upon clicking it nothing will happen.
> Tried on 3 different devices (iPad Air 2 gen, iPad air 3 gen, iPhone 11 Pro) all with the latest iOS.
> 
> Working manga: [Solo Leveling](https://mangadex.org/title/31477/solo-leveling)
> Not working manga:
> 
>     * [Dr. Stone](https://mangadex.org/title/20882/dr-stone)
> 
>     * [Funouhan](https://mangadex.org/title/13033/funouhan)
> 
>     * [Kaifuku Jutsushi no Yarinaoshi](https://mangadex.org/title/21758/kaifuku-jutsushi-no-yarinaoshi)
> 
> 
> None of those are with N tag.
> Tried following the guide on your troubleshooting but no result.
> 
> App Logs:
> [27-02.Paperback.txt](https://github.com/Paperback-iOS/app/files/6055193/27-02.Paperback.txt)

Are you using Mangadex Unlocked ? 
Get it here : https://paperback.moe/help/guides/adding-repos/#what-is-an-external-repository
If you are on the Public Testflight, get Mangadex Unlocked in the Classic Sources.
If you are on the Patreon Testflight, you need to use the promises sources,

**Comment by ale-ben** [comment]
> > 
> 
> > 
> 
> > Same issue here, I follow 4 mangas on MD, 1 of them sync without problems, the other 3 won't sync.
> 
> > The app will prompt me to follow locally but upon clicking it nothing will happen.
> 
> > Tried on 3 different devices (iPad Air 2 gen, iPad air 3 gen, iPhone 11 Pro) all with the latest iOS.
> 
> > 
> 
> > Working manga: [Solo Leveling](https://mangadex.org/title/31477/solo-leveling)
> 
> > Not working manga:
> 
> > 
> 
> >     * [Dr. Stone](https://mangadex.org/title/20882/dr-stone)
> 
> > 
> 
> >     * [Funouhan](https://mangadex.org/title/13033/funouhan)
> 
> > 
> 
> >     * [Kaifuku Jutsushi no Yarinaoshi](https://mangadex.org/title/21758/kaifuku-jutsushi-no-yarinaoshi)
> 
> > 
> 
> > 
> 
> > None of those are with N tag.
> 
> > Tried following the guide on your troubleshooting but no result.
> 
> > 
> 
> > App Logs:
> 
> > [27-02.Paperback.txt](https://github.com/Paperback-iOS/app/files/6055193/27-02.Paperback.txt)
> 
> 
> 
> Are you using Mangadex Unlocked ? 
> 
> Get it here : https://paperback.moe/help/guides/adding-repos/#what-is-an-external-repository
> 
> If you are on the Public Testflight, get Mangadex Unlocked in the Classic Sources.
> 
> If you are on the Patreon Testflight, you need to use the promises sources,

Feel dumb for not reading that -.-
Now it works perfectly, thanks!
