### ISSUE TITLE
Nothing loading

### ISSUE THREAD

**Issue by Fernando-Mendez** [Paperback-iOS/app#253]
I'm honestly not sure anymore if it's that I don't know how to setup the app or what but I get nothing whenever I use the app. No content at all with the MangaDex source.

**Comment by FaizanDurrani** [comment]
Join the discord server and use the support channel FYI get help in setting up the app.

also, ensure that you’re on the MangaDex Unlocked source to get all the content from mangadex, if that doesn’t work, try getting other sources.

For a guide on how to get more sources, join the discord server.

https://discord.gg/Ny83JV3
