### ISSUE TITLE
[BUG] getViewMoreItems is not called when there is not enough titles

### ISSUE THREAD

**Issue by FramboisePi** [Paperback-iOS/app#256]
**Describe the bug**
On large devices, when opening the **View more** window of a homepage section, if there is not enough titles on the page, the app won't try to show more when the user scroll.

[`getViewMoreItems`](https://github.com/Paperback-iOS/extensions-common/blob/c235c1876747abeb57ea8a15dc9908912651468c/src/base/Source.ts#L156) method seems to only be called one time.

If there is enough titles (~40 on an iPad) or if the screen is small (when using Split View for example), the method is called when scrolling though the page and all titles are shown.

**To Reproduce**
* Install **ComicExtra** on a large device.
* On the homepage of the source press **View** next to "Recently Added Comics".
* Scroll to let the app get the next titles.

**Expected behaviour**
All titles present on the 7 pages of [www.comicextra.com/recent-comic](https://www.comicextra.com/recent-comic) should appear.

**Current behaviour**
Only titles present on the first page are shown.
![IMG_39A28FE27865-1](https://user-images.githubusercontent.com/25133304/108498256-e4976300-72ac-11eb-96d5-95efbd2b10e5.jpeg)

**App Version**
v0.4.0-b2.2.13

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.2-Beta)
