### ISSUE TITLE
[BUG]Alpha 2.2.13 Bug - Download Clear in Library

### ISSUE THREAD

**Issue by Akiawa** [Paperback-iOS/app#259]
**Describe the bug**
App freeze when clearing downloads through long press in library.

**To Reproduce**
Long press in library -> Delete downloaded chapters.

**Expected behaviour**
It's suppose clear downloads without any issues

**App Version**
v0.4.0 (2.2.13) - Alpha

**Screenshots**
https://user-images.githubusercontent.com/36525308/108641934-1c9ad380-7470-11eb-973e-10cdb6213ffa.mp4

**Comment by ConradWeiser** [comment]
Can you please verify if this is still an issue on the 0.5 release of the app? I'm having a difficult time reproducing the issue on my own devices

**Comment by Akiawa** [comment]
Late reply, I think Paper fixed it on 0.5.0 release.
