### ISSUE TITLE
[BUG] [v0.4.0 (2.2.15-Beta)] Cannot open manga tile in discover tab after tapping source selection button.

### ISSUE THREAD

**Issue by uttiya10** [Paperback-iOS/app#261]
**Describe the bug**
After opening and closing the source selection screen, manga tiles become non-interactive

**To Reproduce**
1. Open app
2. Tap source selection button to open screen
3. Close the screen by tapping on a manga tile in the background
4. Notice how the manga tiles become non-interactive

**Expected behaviour**
After closing the source selection menu, you should be able to interact with a manga tile to open it

**App Version**
v0.4.0-b2.2.15

**Comment by Rhexia** [comment]
This bug can be reproduced on v0.4.0-b.2.2.15, iOS 14.4 - iPhone Xs Max

**Comment by uttiya10** [comment]
Fixed in v0.4.0-b2.2.18
