### ISSUE TITLE
[REQUEST]A better profile view.

### ISSUE THREAD

**Issue by Akiawa** [Paperback-iOS/app#263]
**Description**
I have recently been ip banned from Mangadex. I couldn't access my stats because it is currently tied with the "Mangadex Profile". Even though I can access to my stats offline, it's inconvenient to turn off wifi and turn it back on to see the stats.

**How would it improve the App?**
It makes an easier access to your stats even if cannot access to Mangadex because of an ip ban. 

**Additional context**
A video to show the current situation
https://user-images.githubusercontent.com/36525308/109902953-263eeb00-7c69-11eb-8f85-4895f5496338.mov
An example of my idea.
![Connection](https://user-images.githubusercontent.com/36525308/109902964-2b9c3580-7c69-11eb-8172-0cd565866c99.png)

**Comment by ConradWeiser** [comment]
We fully intend on adding trackers in the near future. The UI as well will likely get a good amount of adjustments and improvements before a 1.0 release. It's safe to say that the current 'Profile' section will be redone, as soon as 0.7
