### ISSUE TITLE
[REQUEST] ePub implementation when integrating Komga with PaperBack

### ISSUE THREAD

**Issue by pandeynmn** [Paperback-iOS/app#264]
**Description**
Please look into implementing an ePub reader from local Komga source so we could read the books that we downloaded. 

**How would it improve the App?**
We can read Light Novels from our own sources and since the logic for getting manga and epub should be almost the same considering it will be from the same source I think it is worth looking into.

**Comment by GameFuzzy** [comment]
The Komga extension is already close to being finished on the latest alpha build.

**Comment by pandeynmn** [comment]
> The Komga extension is already close to being finished on the latest alpha build.

Yeah I already asked paper about the ePub for Komga. He said no special implementation in the source would be required and he is looking into displaying ePubs in the app
