### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mrleamerz** [Paperback-iOS/app#266]
**Describe the bug**
When I open the app it shows a black screen with no manga loaded 

App version 0.4.0 (1.0.3)
![34BD493B-BC88-4E42-AFC5-B93790389465](https://user-images.githubusercontent.com/80484543/110843300-bb477280-826d-11eb-8dd7-24774656b653.jpeg)

**Comment by DishankJ** [comment]
Paperback doesn't host manga the sources do. MangaDex has been down and been undergoing a server update too so it must have been the reason why the manga weren't loading for you. You can switch to MangaDex Unlocked source for faster load times and a few minor other features if you wish to.

**Comment by ConradWeiser** [comment]
MangaDex is down at the moment as well, so their source will not return any results. Please reference our website at https://paperback.moe - There is a section on how to add other sources to the application.
