### ISSUE TITLE
[REQUEST] A tab for mangas that you've finished reading

### ISSUE THREAD

**Issue by ChrisDudeBoi** [Paperback-iOS/app#270]
**Description**
There's a tab for mangas that you are currently reading or planing to, also for the ones you've dropped. There should be a tab for the mangas you've finished reading. 

**How would it improve the App?**
You could watch this tab for you to remember what you've read before, if you want to read it again you can find it here quickly, and if you want to recommend it to a friend you can give recommendation about a manga you've read.

**Comment by ConradWeiser** [comment]
You can make a custom tab called 'Finished' yourself and move content as it's done. 
This is not something that we can make automatic. There are too many different ways for users to read a manga.

- Did the user start halfway and only read the last half?
- Did the user read from start to finish, hitting every single chapter?
- Did the user read only parts, and decide to drop it?

We can know when a Manga is called Completed as that's provided by the source, but if one of the bullet points above was to be implemented, it seems a little.. Out of scope of the project as a whole.
