### ISSUE TITLE
[REQUEST] iPad keyboard support & default library view

### ISSUE THREAD

**Issue by Chromagram** [Paperback-iOS/app#272]
**Description**
1. iPad keyboard support would be amazing, since iPadOS now supports a lot more keyboard functions and a lot of people are getting them. At base, features like using the arrow keys to scroll between pages and hotkeys to perform certain common actions would be great.

2. For me, when I open my library tab, I usually just read the newest chapters of ongoing manga and re-read completed much less frequently. I’d love to be able to choose settings on the default view for the library tab. For me, I’d just want to be able to tap on the tab and have it show the Ongoing tab as default, but the feature could also be enhanced by allowing a specific default layout with things like custom tags. 

**How would it improve the App?**
1. The iPad keyboard support would allow quick and easy navigation, as a lot of us now keep our hands on the keyboard when trackpad mode is in use. Hotkeys especially would make navigation and shortcuts easier to access.
 
2. Default library customization would allow the library tab, the most personal part of the app, to act the most conveniently for each individual user.

**Comment by dvydra** [comment]
I agree with this. Even just space to move forward would be a huge quality of life improvement.

Thanks for all your work.

**Comment by Chirishman** [comment]
I also would really like Keyboard Support. Looking at the three years without a dev comment or triage tagging on it looks like it's not on the roadmap though...

**Comment by FaizanDurrani** [comment]
Added in 0.8.7-r2
