### ISSUE TITLE
Cant download manga

### ISSUE THREAD

**Issue by barendbotje** [Paperback-iOS/app#276]
Wherry is the download button cant rond it anywhere and i have the patreon version 
![FDDEA5B0-4F3B-4C9B-B76B-B14C0020AB73](https://user-images.githubusercontent.com/80960524/111778527-13592700-88b5-11eb-822c-129ef76db26f.png)

**Comment by ConradWeiser** [comment]
Reference the gif below. Feel free to re-open this if you still have issues.
![](https://cdn.discordapp.com/attachments/794353299343933450/821848033994080366/download.gif)
