### ISSUE TITLE
[REQUEST] Source: readcomiconline.to as a source

### ISSUE THREAD

**Issue by ash10r** [Paperback-iOS/app#277]
**Description**
I confirmed with some devs in discord that the initial reason for not adding it in previous builds is no longer an issue.

**How would it improve the App?**
Is better than the 2 current alternatives

**Additional context**
Why it’s better:
Readcomiconline.ru : smaller catalog 
Comicextra: uses half the resolution of readcomiconline, so not as sharp on large displays like iPads.
Hence better than both current sources in quality and quantity.

**Comment by ConradWeiser** [comment]
This belongs in https://github.com/Paperback-iOS/extensions-promises/issues
Fortunately, I BELIEVE one of our Discord members, Aurora, is working on this source currently!
