### ISSUE TITLE
[REQUEST] Use Experimental search in Merges

### ISSUE THREAD

**Issue by BedHedd** [Paperback-iOS/app#279]
**Description**
The current merge uses a library search. This causes issues as the library does not have a way to differentiate between sources though this request https://github.com/Paperback-iOS/app/issues/273 might also work. 

The new experimental search has identifiers for sources. 

**How would it improve the App?**
It would make merging more user friendly. Without labels, you are using the cover to differentiate between sources. Furthermore, this would also make it easier to migrate sources if your primary source dies, and reduce the number of clicks. Currently to add a source, you must use the search bar in discover to find another source, add it to your library, and merge from there (you have to do it this way if you want a particular cover). 

**Additional context**
An alternative might be to move the merge feature into the experimental search, as when you wouldn't need to add the series to your library and you would only have the library source. This would also solve a library search bug https://github.com/Paperback-iOS/app/issues/280#issue-836755156

If this suggestion is implemented, cover selection would be needed (ie being able to change the cover from the series or having a option to switch between using the cover of first or second selected series.  Currently, when 2 series are merged, the cover of the second series will be the default.

**Comment by FaizanDurrani** [comment]
Added in 0.7 Build 16
