### ISSUE TITLE
[BUG] App Still Crashes

### ISSUE THREAD

**Issue by IssueTissue** [Paperback-iOS/app#281]
**Describe the bug**
- The app crashes when I open the ‘history’ tab.

**To Reproduce**
- By clicking on the clock button. On a previous version, both the settings and history tab would crash the app. Now after updating to the latest version, only the history tab crashes.

**Expected behaviour**
- To open my history.

**App Version**
v0.5.0-r1.0.5

**Screenshots**
- It’s literally just gonna be a picture of the history tab.

**Comment by ConradWeiser** [comment]
There is not enough information here to replicate this issue. Can you please provide your app logs as a response please? You can export the logs from the bottom of your settings page.

**Comment by IssueTissue** [comment]
Sure here u go!

[INFO] [2021-03-28T13:29:17.362Z] [reloadSources():48] Loading MangaLife version: 2.1.5
[INFO] [2021-03-28T13:29:17.369Z] [reloadSources():48] Loading Manganelo version: 2.1.1
[INFO] [2021-03-28T13:29:17.371Z] [reloadSources():48] Loading MangaDex version: 3.0.0
[INFO] [2021-03-28T13:29:17.424Z] [sceneDidBecomeActive(_:):41] Scene did become active
[INFO] [2021-03-28T13:29:17.469Z] [processQueue():268] No downloads queued
[INFO] [2021-03-28T13:29:17.667Z] [reloadSources():48] Loading MangaLife version: 2.1.5
[INFO] [2021-03-28T13:29:17.669Z] [reloadSources():48] Loading Manganelo version: 2.1.1
[INFO] [2021-03-28T13:29:17.670Z] [reloadSources():48] Loading MangaDex version: 3.0.0
[INFO] [2021-03-28T13:29:17.812Z] [init():56] Network change detected; STATUS: satisfied; EXPENSIVE: false
[INFO] [2021-03-28T13:29:17.814Z] [getRequest(url:includeAuth:callback:):242] [REQUEST] URL: https://api.paperback.moe/ping
[INFO] [2021-03-28T13:29:18.157Z] [updateAllSources():106] AutoSourceUpdate - Bato.To not found locally, ignoring
[INFO] [2021-03-28T13:29:18.158Z] [updateAllSources():106] AutoSourceUpdate - ComicExtra not found locally, ignoring
[INFO] [2021-03-28T13:29:18.160Z] [updateAllSources():106] AutoSourceUpdate - Guya not found locally, ignoring
[INFO] [2021-03-28T13:29:18.162Z] [updateAllSources():106] AutoSourceUpdate - MangaPark not found locally, ignoring
[INFO] [2021-03-28T13:29:18.164Z] [updateAllSources():106] AutoSourceUpdate - MangaPill not found locally, ignoring
[INFO] [2021-03-28T13:29:18.166Z] [updateAllSources():106] AutoSourceUpdate - Mangakakalot not found locally, ignoring
[INFO] [2021-03-28T13:29:18.168Z] [updateAllSources():106] AutoSourceUpdate - Mangasee not found locally, ignoring
[INFO] [2021-03-28T13:29:18.170Z] [updateAllSources():106] AutoSourceUpdate - ReadComicsOnline not found locally, ignoring
[INFO] [2021-03-28T13:29:18.172Z] [updateAllSources():106] AutoSourceUpdate - ReadComicsOnlineTo not found locally, ignoring
[INFO] [2021-03-28T13:29:18.284Z] [start():51] [AsyncOperation] RequestOperation - https://manga4life.com
[INFO] [2021-03-28T13:29:18.286Z] [start():51] [AsyncOperation] Delay Operation - 400ms
[INFO] [2021-03-28T13:29:18.368Z] [refreshAuthentication():120] Not authenticated
[INFO] [2021-03-28T13:29:18.478Z] [updateAllSources():106] AutoSourceUpdate - MangaMint not found locally, ignoring
[INFO] [2021-03-28T13:29:18.526Z] [getRequest(url:includeAuth:callback:):249] [RESPONSE] URL: https://api.paperback.moe/ping
[INFO] [2021-03-28T13:29:18.528Z] [init():68] Is connected to network: true
[INFO] [2021-03-28T13:29:18.530Z] [getRequest(url:includeAuth:callback:):242] [REQUEST] URL: https://mangadex.org/settings
[INFO] [2021-03-28T13:29:18.886Z] [refreshAuthentication():120] Not authenticated
[INFO] [2021-03-28T13:29:24.053Z] [getRequest(url:includeAuth:callback:):249] [RESPONSE] URL: https://mangadex.org/settings
[INFO] [2021-03-28T13:29:39.164Z] [sceneDidBecomeActive(_:):41] Scene did become active
[INFO] [2021-03-28T13:29:40.276Z] [refreshAuthentication():120] Not authenticated

**Comment by FaizanDurrani** [comment]
This is a sort-of known issue, it will be addressed in a future release. For the time being, the solution is to clean your read history, if you want to do this send your backup to Paper#1932 on discord.
