### ISSUE TITLE
[REQUEST] Stop reloading pages every tab change

### ISSUE THREAD

**Issue by Gikona** [Paperback-iOS/app#285]
**Description**
Basically stop reloading the mangas when you change tabs or click on a manga

**How would it improve the App?**
Removes annoying (IMO) delay between checking mangas or switching between tabs

**Additional context**

https://user-images.githubusercontent.com/47604520/112725308-f2d24200-8f30-11eb-8116-a523f18e0f9b.MP4

(What happens after I go back to the main page after favoriting the manga)
This also happens if you switch from, for example, favorites to discover tabs.

I suppose this is happening because the app is refreshing the lists every time, but other manga apps usually only do that on startup then you’d have to manually reload, if you wanted, by pulling down on the page.

I guess another thing that could be added is to also remember where you are scrolled through the pages.

**Comment by PythonCoderAS** [comment]
In addition, al pages in a chapter should stay loaded sit shy the page doesn’t need to be re-downloaded if I scroll up.
