### ISSUE TITLE
Lock Orientation 

### ISSUE THREAD

**Issue by JohnleDo** [Paperback-iOS/app#290]
**Description**
I used the MangaStorm app for about 10 years now and the one thing I loved about the app was being able to lock the orientation to prevent it from going portrait to landscape. This tends to happen when I'm laying down and trying to read and the only way to prevent this was by pulling down the IOS menu and locking it from there. I think adding it into the settings to remember the orientation would be nice or do it like MangaStorm and have a lock button in the chapter to be able to toggle that on and off.

**How would it improve the App?**
Helpful for those who tend to read while laying down on their side and not wanting to have to pull down the IOS menu to lock it and then unlock when not using the app.

**Comment by TheNetsky** [comment]
Duplicate  of https://github.com/Paperback-iOS/app/issues/91 :)
