### ISSUE TITLE
[BUG] single page chapter scrolling issue

### ISSUE THREAD

**Issue by retguy** [Paperback-iOS/app#291]
**Describe the bug**
Scrolling down when on a single page chapter sends you back a chapter instead of forward.

**To Reproduce**
Go to a single page chapter, in my case it was “My Company’s Small Senpai”, Chapter 20, on the Manganelo source. Scroll down and on the second attempt of scrolling down it’ll send you back to chapter 19. I think it might just be tapping the screen after the first try that’ll do it.

**Expected behaviour**
Scrolling down should have sent me to chapter 21

**App Version**
0.5.0(1.0.6)

**Screenshots**
I recorded what happened, if you look for “ret guy” in the discord, you should be able to find the video I sent to the support channel.

**Comment by Akiawa** [comment]
Here's the video from the #support channel. 
https://discord.com/channels/673606787290759230/702052855623843861/826179619425615914
https://user-images.githubusercontent.com/36525308/112916292-44fc9a00-90ce-11eb-97fe-f3ce3f127bf1.mov

**Comment by PythonCoderAS** [comment]
For me, I can only scroll up to go backwards, but I can’t scroll down at all.

**Comment by FaizanDurrani** [comment]
Fixed in 0.7
