### ISSUE TITLE
[BUG] Alphabetical order broken (potentially when using multiple sources)

### ISSUE THREAD

**Issue by PerMetersaker** [Paperback-iOS/app#292]
**Describe the bug**
The alphabetical sorting can end up being skewed. I believe this could be a case of having different sources in the library, but I also found some cases where even the same source can be out of order
**To Reproduce**
Not 100% sure, my assumption has to do with using other sources

**Expected behaviour**
The manga should be sorted in proper alphabetical order

**App Version**
v0.5.0-r1.0.6

**Screenshots**
Some R's mixed with the S's. 'Sa' coming before 'Se' (this is in reversed alphabetical, though the same issues arises with regular alphabetical)
![1](https://user-images.githubusercontent.com/81595242/112908804-373f1880-90be-11eb-8f51-29038d04910c.png)
Some Q's mixed with R's
![2](https://user-images.githubusercontent.com/81595242/112908805-37d7af00-90be-11eb-808e-98e4be9df199.png)

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0
