### ISSUE TITLE
[REQUEST] Help Tab For Appstore Release

### ISSUE THREAD

**Issue by LewdFtw** [Paperback-iOS/app#297]
Description
A clear description of the feature
-For AppStore release (or new builds) there should be a tab in the bottom or in settings labeled as help and have the videos that Carl bot post in the discord in the #support channel there.

How would it improve the App?
How would the feature improve the app?
-This would help people new to Paperback that don't want to join the discord and just install the app and use it immediately. This will also save people time because joining the discord and asking for help then waiting for a response instead of going to settings and watching a short video/ reading a little will save minutes-hours of people's time.

**Comment by FaizanDurrani** [comment]
Will not be implemented due to restrictions by Apple
