### ISSUE TITLE
[BUG] Merged Manga of Deleted Sources Remain

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#303]
**Describe the bug**
if I delete a source and mangas from that source were merged, the deleted source still remains.

**To Reproduce**
1. Merge two manga
2. Delete one source
3. Open manga from library

**Expected behaviour**
Only one source should show

**App Version**
Eg: v0.5.0-1.0.6

**Comment by FaizanDurrani** [comment]
This is by design. The reason it works this way is that if you ever remove a source you can go back and see what chapter you last read for a manga on that source it since the chapter list remains.

**Comment by PythonCoderAS** [comment]
> This is by design. The reason it works this way is that if you ever remove a source you can go back and see what chapter you last read for a manga on that source it since the chapter list remains.

Will there be a way to purge these sources? Or do I have to go through each item and unmerge?

**Comment by FaizanDurrani** [comment]
You have to go through and unmerge, that being said, I don't really see the issue with just having them there.
