### ISSUE TITLE
[BUG] Page reloading to the top after exiting manga

### ISSUE THREAD

**Issue by danielysantas** [Paperback-iOS/app#304]
**Describe the bug**
When you open a manga in any section (Hot Manga, Latest Releases, etc) and back out, it takes you back to the top of the list. Say you’ve spent 5 minutes scrolling down, looking for manga to read, open one and back out of it, it sends you to the top, effectively making you have to scroll all the way down again.

**To Reproduce**
1. Open any section in any source.
2. Scroll down and open a manga
3.  Back out of the manga

**Expected behaviour**
The page should stay where you opened the manga, instead of reloading you back to the top.

**App Version**
v0.5.0-r1.0.6

iPhone 12 - iOS 14.4.2

**Comment by danielysantas** [comment]
Here’s a video example of the bug: https://imgur.com/gallery/fvQT8oJ

**Comment by Akiawa** [comment]
This issue is probably the same as https://github.com/Paperback-iOS/app/issues/285
