### ISSUE TITLE
[REQUEST] Query each manga daily for chapter changes

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#305]
**Description**
I understand that a lot of manga websites have ways to check the latest updates for manga, but not all websites have such a system, since someone only link the chapters and not the actual manga itself. I propose having the app query each source with the manga IDs of every manga stored under Paperback and download & parse the chapter list. The current chapter list should ideally be stored persistently, and the stored chapter list can be compared with the new list for either new chapters or maybe even updates to existing chapters.

**How would it improve the App?**
This would allow still finding out about new manga for sources that don't have an easy way to see the latest updates.

**Comment by FaizanDurrani** [comment]
The app already does this, however, *when* the background job runs is dependant on iOS.
