### ISSUE TITLE
[BUG] Only Manga/chapters from one source is being updated

### ISSUE THREAD

**Issue by DottyPottyLotty** [Paperback-iOS/app#306]
**Describe the bug**
Currently I am using three sources: Manga4Life, Manganelo and Mangahub. Every time i refresh the library it would less than a second and only new chapters would be fetch for Manga4Life while the other two is ignored. 

**To Reproduce**
No exact way to reproduce. This has happened since day one of me using the app.

**Expected behaviour**
I refresh library. Fetching updated manga will show up and fetching new chapters will show up after. New chapters indicator will show up on the newly updated manga but only for Manga4Life but not Manganelo and Mangahub.

**App Version**
v0.5.0-r1.0.6

**Screenshots**
![image](https://user-images.githubusercontent.com/78997291/113495344-73e29800-9534-11eb-887b-c50b593111f0.png)

**Comment by ConradWeiser** [comment]
This is a source issue. Manganelo may require some updates to function correctly. (We've noticed this source has some issues while doing some other paperback work, it's on the line to get fixed soon)
MangaHub isn't a part of the source-list we quality control usually, you may need to contact the source developer there about this.

I'm closing this issue as it's a source problem and not an app problem. We're aware and will try to get at least Manganelo patched up!
