### ISSUE TITLE
[BUG] Searching "All Sources" does not search all sources

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#307]
**Describe the bug**
When I search for something using All Sources, I don't see results from all sources.

**To Reproduce**
1. Have ~10+ sources
2. Search for something, probably a simple character like "a" or "b"
3. Count the number of sources
4. Manually repeat the search for every source and count which sources show results.

**Expected behaviour**
Search results for every source should show up.

**App Version**
Eg: v0.5.0-1.0.6

**Comment by FaizanDurrani** [comment]
The search feature in Discover is deprecated and will be replaced with the new search tab. You can enable that from settings > paperback labs > reworked search.

Do not submit issues for the reworked search until it is stable as it is incomplete and most of the issues are already known.
