### ISSUE TITLE
[BUG] Select mode will select mangas right below currently rendered mangas

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#308]
**Describe the bug**
If I tap the Select mode on the library, and start scrolling down, mangas that are right below the ones currently shown will be selected, even though I didn't selected them.

**To Reproduce**
1. Turn on selected mode
2. Start scrolling but not too fast

**Expected behaviour**
This to not happen.

**App Version**
Eg: v0.5.0-1.0.6

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0
