### ISSUE TITLE
[REQUEST] Allow switching chapter tabs without u following and re-following manga

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#309]
**Description**
I should be able to change the tab a manga is located in without u following the manga and then re-following the manga.

**How would it improve the App?**
It would be more convenient.

**Comment by ConradWeiser** [comment]
You're able to do this from the library. Select all of the titles you want to move with the 'mark' feature. There is a context menu which lets you bulk change your content to another tab.

**Comment by PythonCoderAS** [comment]
> You're able to do this from the library. Select all of the titles you want to move with the 'mark' feature. There is a context menu which lets you bulk change your content to another tab.

The Select option has its own problems (see #308), but if I have a manga in one tab, read it, and then want to change tabs (such as from Reading to Completed), I shouldn't have to go all the way to my library just to edit one manga.

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.2-Beta)
