### ISSUE TITLE
[BUG] Unable to trigger chapter overlay from landscape mode

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#310]
**Describe the bug**
In landscape mode, I am unable to tap on the chapter to bring up the overlay that lets me go to the next page or exit the chapter. 

**To Reproduce**
1. Start reading a chapter
2. Enter landscape mode
3. Try to exit the chapter

**Expected behaviour**
The overlay should show up as usual.

**App Version**
Eg: 0.5.0-1.0.6

**Comment by FaizanDurrani** [comment]
Tap the center of the screen.

**Comment by PythonCoderAS** [comment]
It seems to only work at the top of the screen, not the center, which is a bit unintuitive.

**Comment by FaizanDurrani** [comment]
Uh no, it's working on the whole center column for me, Can you record a video?

**Comment by PythonCoderAS** [comment]
How would a screen recording show the location where I'm tapping?
