### ISSUE TITLE
[BUG] No scroll bar on iPad (within chapter)

### ISSUE THREAD

**Issue by ash10r** [Paperback-iOS/app#311]
**Describe the bug**
No scroll bar present when a chapter is opened to speed scroll through pages.

**To Reproduce**
Open any chapter on an iPad with v 0.5.0 (1.0.6) aka public build
iPadOS 14.4.2

**Expected behaviour**
I was told in support this is already present on iPhones. Hence me submitting a bug instead of a feature request. 

**App Version**
v 0.5.0 (1.0.6)

**Screenshots**
Taken on a page immediately after swiping (in case scroll bar hides on idle. Mode : horizontal pages )
![1058735E-7CCE-4716-8517-726ECCF0367E](https://user-images.githubusercontent.com/78199278/113609828-f620a880-9669-11eb-8f0c-2d9543b3821a.png)

**Comment by FaizanDurrani** [comment]
Intended behaviour, scrollbars appear when you zoom in on horizontal reader.
