### ISSUE TITLE
[BUG] Repos are being cached

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#314]
**Describe the bug**
The contents of repositories are being cached, so they do not update whenever I create a new bundle.

**To Reproduce**
1. Add a local repo
2. Download an extension
3. Change the extension version
4. Try to open the repo again in the app

**Expected behaviour**
When a user opens the repo page, it should be redownloaded.

**App Version**
Eg: v0.5.0-1.0.6

**Screenshots**

**Comment by FaizanDurrani** [comment]
Paperback does not cache the repository page, this can be noticed by running `npm run serve` and observing that the repository page does indeed fetch changes immediately.

**Comment by PythonCoderAS** [comment]
You're right, I'm pretty sure NGINX is the one caching the contents.
