### ISSUE TITLE
[REQUEST] Alternate Source Finder

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#320]
**Description**
Each manga could have a button that uses the manga name to find copies of the manga in other sources and automatically merged them together.

**How would it improve the App?**
It would be easier to replace sources if they went down or had other issues.

**Comment by ConradWeiser** [comment]
If you'd be willing to psudo-code out an algorithm which can do this, I'd be extremely impressed.
There's no guarantee that two sources upload a manga at the same time. Upload dates will always be different. This is not a reliable service.

**Comment by PythonCoderAS** [comment]
Maybe the merging won't be fully automatic, and the user could choose which ones to merge. It could be as simple as opening the search window with the title pre-pasted.

**Comment by ConradWeiser** [comment]
This will be handled by the migration function in 0.6
