### ISSUE TITLE
[BUG] Sometimes when I finish a chapter and swipe to start the next chapter, the "last page" overlay appears on the first page of the new chapter, not allowing me to interact with anything. Restarting the app is the only way to fix it. 

### ISSUE THREAD

**Issue by Pkron17** [Paperback-iOS/app#322]

**Comment by TheNetsky** [comment]
Please use the "Bug Report" template for submitting bugs, these reports are missing crucial information.
I'd recommend closing this issue and making a new one that follows the "Bug report" template.
https://github.com/Paperback-iOS/app/issues/new/choose
