### ISSUE TITLE
[BUG] In two-page mode, one or both of the pages of a downloaded chapter won't load. It just stays on the spinning load symbol. 

### ISSUE THREAD

**Issue by Pkron17** [Paperback-iOS/app#323]
I've found that swapping to single page mode and back instantly loads it

**Comment by TheNetsky** [comment]
Please use the "Bug Report" template for submitting bugs, these reports are missing crucial information.
I'd recommend closing this issue and making a new one that follows the "Bug report" template.
https://github.com/Paperback-iOS/app/issues/new/choose
