### ISSUE TITLE
[BUG] I'm getting a lot of errors while downloading chapters. The download will get anywhere from 10%-90% done then just error and move on to the next. If I keep trying, sometimes they work, but it takes a lot of repeating. 

### ISSUE THREAD

**Issue by Pkron17** [Paperback-iOS/app#324]

**Comment by TheNetsky** [comment]
Please use the "Bug Report" template for submitting bugs, these reports are missing crucial information.
I'd recommend closing this issue and making a new one that follows the "Bug report" template.
https://github.com/Paperback-iOS/app/issues/new/choose
