### ISSUE TITLE
App Category is Wrong

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#332]
**Describe the bug**
Looking at the screen time info, it shows the app as category "other". It should be in the "information & reading" category

**To Reproduce**
Use the app some, then look at your screen time. 

**Expected behaviour**
Should be under the "information & reading" category 

**App Version**
v0.5.0-r1.0.6

**Screenshots**
![image](https://user-images.githubusercontent.com/657766/114576729-67072800-9c49-11eb-973a-3d170f74ea49.jpeg)

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0
