### ISSUE TITLE
[BUG] Tags Overflow

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#334]
**Describe the bug**
Source tags overflow their source's height 
**To Reproduce**
Download a source with lots of big tags

**Expected behaviour**
Padding should be added to prevent overflowing.

**App Version**
Eg: v0.5.0-1.0.6

**Screenshots**
![image](https://user-images.githubusercontent.com/13932583/114906196-cc911b00-9de7-11eb-9d75-5d503452390f.png)

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.2-Beta)
