### ISSUE TITLE
[BUG] Manga Icons in history disappear 

### ISSUE THREAD

**Issue by TheNetsky** [Paperback-iOS/app#335]
**Describe the bug**
Manga icons in the history tab seem to load fine at first glance. However after removing a manga from the history, the icons would disappear and the loading icon appears. However the icons never return and it'll always be the loading icon until the app is restarted.

**To Reproduce**
Steps to reproduce the behaviour
Open History, remove an item from the History.

**Expected behaviour**
The icons shouldn't have to reload and if they do, the icon should re-appear.

**App Version**
Eg: v0.5.0-r1.0.6
Ipad iOS 13.5

**Screenshots**
https://cdn.discordapp.com/attachments/705193595715452958/832585415361429514/image0.png
https://cdn.discordapp.com/attachments/705193595715452958/832585415600242688/image1.png

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.2-Beta)
