### ISSUE TITLE
[BUG] Source icons don't have any colors

### ISSUE THREAD

**Issue by TheNetsky** [Paperback-iOS/app#336]
**Describe the bug**
In the search/source select the source icons don't have any colors.

**To Reproduce**
It never has/had any colors. It's always reproducible. 

**Expected behaviour**
The icons should reflect the source icon colors.

**App Version**
iPad iOS 13.5
r1.0.6

**Screenshots**
[Icon list with no colors](https://cdn.discordapp.com/attachments/705193595715452958/831242306363195452/image0.png)
[Icon list with colors](https://cdn.discordapp.com/attachments/705193595715452958/831240678113673257/image0.png)

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.2-Beta)
