### ISSUE TITLE
[BUG] Manga chapters load at random pages

### ISSUE THREAD

**Issue by rintendou** [Paperback-iOS/app#341]
**Describe the bug**
Opening new chapters sometimes loads the manga on the page of the previous chapter. The solution as of right now is by going to and opening the second to last chapter and just scroll through until you reach the next chapter.

**To Reproduce**
I cannot reproduce this bug.

**Expected behaviour**
Reset progress of each chapter before loading the chapter up.

**App Version**
v0.5.0-1.0.6

**Screenshots**

**Comment by FaizanDurrani** [comment]
This should be fixed in the reader rewrite in 0.7
