### ISSUE TITLE
[REQUEST] Ability to hide chosen sources from 'All' in Search

### ISSUE THREAD

**Issue by DishankJ** [Paperback-iOS/app#342]
**Description**
Basically an option to let us hide certain sources from searching a manga in "all" category in Search tab. So if we want to search a manga in that hidden source we can open that category from Search.

**How would it improve the App?**
Sources like Guya are used for only reading a few manga and we don't need to search or add a manga from that source so hiding it from "all" from search tab would be beneficial and less tough to find a manga.

**Comment by FaizanDurrani** [comment]
Added in 0.7 Build 16
