### ISSUE TITLE
Beta full in Testflight

### ISSUE THREAD

**Issue by deepakkavoor** [Paperback-iOS/app#350]
Hi, I’m trying to download the beta version from TestFlight on my iPad, and it says “This beta is full”. Could you increase the max testers limit?

**Comment by TheNetsky** [comment]
We're already at our limit of 10k users. 3k Patreons spots and 7k Public spots

You'll sadly have to wait till the reset on July 1st.

**Comment by ErikHumphrey** [comment]
@deepakkavoor Surprise, there was a reset on June 5. There are still slots open now.
