### ISSUE TITLE
[BUG] Downloading any page as an image crashes reader

### ISSUE THREAD

**Issue by angadsri** [Paperback-iOS/app#353]
Holding any page → ‘Save’ → ‘Save as Image’ closes the reader on iOS. Tapping any manga to resume reading doesn’t work, until the app is quit and re-opened.

**Comment by TheNetsky** [comment]
Ehh, can you please follow the proper bug report format? We're missing a lot of information here.

**Comment by angadsri** [comment]
> Ehh, can you please follow the proper bug report format? We're missing a lot of information here.
> https://github.com/Paperback-iOS/app/issues/new/choose

Thank you for sharing that link! Sorry, I think I missed it on mobile.
