### ISSUE TITLE
[BUG] Downloading any page as an image crashes the reader

### ISSUE THREAD

**Issue by angadsri** [Paperback-iOS/app#354]
**Describe the bug**
While reading a manga, trying to save a panel as an image crashes the reader, and makes it impossible to resume reading without relaunching the app.

**To Reproduce**
Press and hold any page → ‘Save’ → ‘Save as Image’

**Expected behaviour**
Image is saved, reader does not quit/one can keep reading

**App Version**
0.5.0 (1.0.11)

**Screenshots**
N/A

**Comment by TheNetsky** [comment]
Well, it isn't actually locking your view, it's just a bit awkward.

You need to touch the black area to exit the saving view. (behind the badly drawn red lines)
![IMG_0176](https://user-images.githubusercontent.com/56271887/120804166-a6b10880-c544-11eb-8375-606ca9b90d5c.PNG)

You can also disable page saving by clicking the gear icon and uncheck "enable image saving".
![IMG_0177](https://user-images.githubusercontent.com/56271887/120804204-af094380-c544-11eb-8a0a-925d70c74d28.PNG)

**Comment by angadsri** [comment]
> Well, it isn't actually locking your view, it's just a bit awkward.
> 
> 
> 
> You need to touch the black area to exit the saving view. (behind the badly drawn red lines)
> 
> ![IMG_0176](https://user-images.githubusercontent.com/56271887/120804166-a6b10880-c544-11eb-8375-606ca9b90d5c.PNG)
> 
> 
> 
> You can also disable page saving by clicking the gear icon and uncheck "enable image saving".
> 
> ![IMG_0177](https://user-images.githubusercontent.com/56271887/120804204-af094380-c544-11eb-8a0a-925d70c74d28.PNG)

Sorry, friend, but you misunderstand the problem. Here's a screen recording, hope it helps!

https://user-images.githubusercontent.com/9767464/120883607-ab42f300-c610-11eb-909d-f6fa7e0707f1.MOV

**Comment by TheNetsky** [comment]
Hmm odd, I can't seem to replicate that. :s 
We'll let the issue open and maybe a dev knows this bug. 👍

**Comment by angadsri** [comment]
Much appreciated!

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.4-Beta)
