### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by itadoris** [Paperback-iOS/app#355]
**Describe the bug**
When you type something into the search bar of the Paperback app and then switch to a different app OR go to ur app history and then back into Paperback, instead of the text that you typed being there, it disappears.

**To Reproduce**
Go into Paperback.
Type something into the search bar.
Go back to your app history, and/or switch applications.
Go back into Paperback.
Your search will not be there

**Expected behaviour**
Instead of the text disappearing, it is expected that it remains there even after viewing app history OR changing in between apps.

**App Version**
v0.5.0-r1.0.11

**Screenshots**
![2403D92C-3DFD-4225-BC69-F3D9770BC974](https://user-images.githubusercontent.com/83465138/120895696-d89a9b80-c626-11eb-8432-53f0f68d97de.png)
![06AAABDC-D4EC-4DBB-BA1A-351AB04D25B2](https://user-images.githubusercontent.com/83465138/120895702-dd5f4f80-c626-11eb-990a-8a6b9274341b.png)

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0
