### ISSUE TITLE
[BUG] next chapter load issue

### ISSUE THREAD

**Issue by aerovalky** [Paperback-iOS/app#357]
**Describe the bug**
when i swipe to a new chapter the next chapter will be completely blank with 0/0 pages until i back out to the chapter list and select the chapter again (happens with all manga just using the current manga im reading as example)

**To Reproduce**
by swiping to the next chapter 

**Expected behaviour**
the next chapter should load properly 

**App Version**
0.5.0 (1.0.11) i am also using an iphone 12 pro ios 14.6

**Screenshots**
when i swipe to next chapter from chapter 96
![image](https://user-images.githubusercontent.com/77658649/121060073-28e13d00-c790-11eb-9fdc-34425a93dfae.png)

after i select the same chapter from the chapter list
![image](https://user-images.githubusercontent.com/77658649/121060165-46aea200-c790-11eb-84ae-b63a3320df5d.png)

**Comment by TheNetsky** [comment]
What manga and what source is this?

**Comment by aerovalky** [comment]
> What manga and what source is this?
 
kichikujima and manganelo

**Comment by FaizanDurrani** [comment]
This happens when the source deletes the chapter after the app has fetched it. Simply refresh your chapter for that title and it should be fixed.
