### ISSUE TITLE
[BUG] App crashes after exiting reader or manga info page

### ISSUE THREAD

**Issue by Benwor28** [Paperback-iOS/app#358]
**Describe the bug**
After either exiting the reader or the manga information page, the app crashes. It only happens sometimes but when it does happen, the next time I exit the manga or manga page it appears to have a higher chance to crash again.

**To Reproduce**

1. I open a manga from the mangalife recently updated section
2. I read the new chapter Edit: new information, reading a chapter is not needed
3. I close the chapter or info page, app crashes
4. I do those steps again after opening the app but with a different manga, and it crashes

**Expected behavior**
For it not to crash

**App Version**
v0.5.0-r1.0.11
Also happened in previous versions, had not gotten it on video before now.

**Screenshots**
Videos below takes place after the first crash
Edited video to make shorter in order to make file smaller to attach:
https://user-images.githubusercontent.com/64277468/122239342-78a5bf80-ce86-11eb-8525-12dec107ad65.mp4

For full video where I am reading the chapter and without editing see: 
https://drive.google.com/file/d/13j_fyqNfWcjP7asajzyhKPtbbTqoDuEw/view?usp=drivesdk
If you want to skip the reading go to 1:20

**Comment by Benwor28** [comment]
Right after making this, it crashed again

**Comment by FaizanDurrani** [comment]
Is this still an issue in 0.6.2?

**Comment by Benwor28** [comment]
I don't know if it's been fixed but it has not happened in a quite a bit. The last time I remember thinking about this bug was when I was updating to v0.6.0. So I assume it has not happened since then.
