### ISSUE TITLE
Expired Beta

### ISSUE THREAD

**Issue by omi-kun** [Paperback-iOS/app#360]
So my beta has expired, I checked the discord channel and the latest beta is full, os there any other way to solve this or should I wait for the next beta which correctly if I'm wrong will be in July?

**Comment by TheNetsky** [comment]
Please just use Discord for these kind of issues the next time, it's a whole lot easier (especially if you're already in the Discord lol)
Currently the public Testflight is full, you can however still join if you become a Patreon supporter.
Else you can side load via AltStore.
