### ISSUE TITLE
[REQUEST] Allow removal of default “paperback” source

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#361]
**Description**
Please allow the default "paperback" source to be removed or otherwise disabled. 

**How would it improve the App?**
Would allow the user to remove a potentially unwanted source. 

**Additional context**
![image](https://user-images.githubusercontent.com/657766/123510003-f61bbd80-d646-11eb-97cd-4bd3e29ec47f.png)

**Comment by nar1n** [comment]
Removal of the default source will come with the next major update (0.6.0)

**Comment by henderea** [comment]
Hmm. Well, the main reason I want to remove it is because my library refresh has slowed down a fair bit and I'm getting an error every time right now:

```
[ERROR] [2021-06-26T10:18:45.305Z] [main():54] [Paperback] Filter update manga failed [PaperbackError(300)] JSError SyntaxError: JSON Parse error: Unrecognized token '<' - parse@[native code]
[ERROR] [2021-06-26T10:18:45.307Z] [main():54] asyncFunctionResume@[native code]
[ERROR] [2021-06-26T10:18:45.309Z] [main():54] [native code]
[ERROR] [2021-06-26T10:18:45.310Z] [main():54] promiseReactionJobWithoutPromise@[native code]
[ERROR] [2021-06-26T10:18:45.312Z] [main():54] promiseReactionJob@[native code]:627:72
```

**Comment by nar1n** [comment]
An update was just pushed. This should hopefully be fixed now?

**Comment by henderea** [comment]
Much better. Thanks!
