### ISSUE TITLE
[BUG] 0.6.0 “Browse Official Repo” gets restored from backups and can’t be removed

### ISSUE THREAD

**Issue by BaronKrause** [Paperback-iOS/app#362]
In 0.6.0 if you do a fresh install there is just 1 source, the Paperback one and no repos. If you restore from your previous versions backup it will restore the previous repos including the  “Browse Official Repo” that contained the Paperback source and just like before it can’t be removed as if it still thinks it’s an official system default repo.

iI’s not serious as it doesn’t seem to break anything, but I’m assuming the repo wasn’t added (or made visible) for a reason and restoring gets around that.

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.2-Beta)

**Comment by BaronKrause** [comment]
> Fixed in 0.6.0 (2.0.2-Beta)

Just checked on 2.0.3 beta and it still restores the “Browse Official Repo” repository from backups that had it and it isn’t removable after it’s restored.

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.4-Beta)
