### ISSUE TITLE
[BUG] Downloaded chapter counts missing on library view

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#365]
**Describe the bug**
The library view no longer shows how many chapters you have downloaded for a series. 

**To Reproduce**
Download chapters for a series and look at it in the library view. 

**Expected behaviour**
Should show a badge with the number of downloaded chapters, like in previous versions. 

**App Version**
0.6.0-1.0.2

**Screenshots**

**Comment by Akiawa** [comment]
I believe that was removed by Paper.

Discord message : https://discord.com/channels/673606787290759230/676014470316949504/856956178172084236

**Comment by henderea** [comment]
Hmm, can't get that link to work on my phone, but if the change was intentional, then I suppose I'll just live with it.
