### ISSUE TITLE
[BUG] Frequent error when closing reader

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#368]
**Describe the bug**
Often, when closing the reader, I get an error popup. This appears in the logs:

```
[ERROR] [2021-07-07T13:10:46.906Z] [ChapterPageVie:imageDownloader:32] sourceId is nil, this should never happen. 
[ERROR] [2021-07-07T13:10:46.912Z] [ChapterPageVie:imageDownloader:32] sourceId is nil, this should never happen. 
```

**To Reproduce**
Read a chapter, then close it out. I'm not sure, but it may only happen with chapters you didn't download ahead of time. 

**Expected behaviour**
The error is harmless, but it probably shouldn't be happening

**App Version**
v0.6.0-1.0.2

**Screenshots**

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.4-Beta)
