### ISSUE TITLE
[BUG] Crash when accessing download queue details view

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#373]
**Describe the bug**
App crashes when I try to access the full download queue. I've sent in the crash report via test flight. Couldn't find any logging for the crash.

**To Reproduce**
While downloading multiple chapters, try to access the full queue view. It will crash the app. It has happened for me every single time I do that since the 0.6.0 update. 

**Expected behaviour**
It shouldn't crash.

**App Version**
v0.6.0-1.0.2

**Screenshots**

**Comment by FaizanDurrani** [comment]
Is this still relevant with 0.6.0 (2.0.6)?

**Comment by henderea** [comment]
I'm on the Patreon build, and it's only at 2.0.5, with no available test flight updates. And on that version, yes, it's still happening.

**Comment by FaizanDurrani** [comment]
What iOS version are you on? What Device do you have? What source are you downloading from? What manga were you downloading the chapters from?

**Comment by henderea** [comment]
iOS 14.7.1 (latest). iPhone 12 Pro Max. MangaDex, though I'm pretty sure I've gotten it with other sources. And it happens regardless of which manga.

**Comment by henderea** [comment]
Forgot to post this sooner, but the issue is fixed on 2.0.13
