### ISSUE TITLE
[REQUEST] Adding refresh chapters function to current refresh manga details button

### ISSUE THREAD

**Issue by TheNetsky** [Paperback-iOS/app#375]
**Description**
Adding this function will make it easier for users to refresh their stored chapters. Currently users need to exit out and go back to their library in order to click this button. One button to refresh all of the manga's data on the manga's page would make a lot of sense and ease in accessibility. 

**How would it improve the App?**
Making the one button on the manga screen fresh all a manga's properties makes it easier to users to refresh the manga's data. Instead of opening all kinds of menus to perform various actions.

**Additional context**
Perhaps renaming this button to "refresh manga data" instead of just details.

**Comment by FaizanDurrani** [comment]
Opening a title in Paperback 0.7 automatically refreshes the chapterlist now
