### ISSUE TITLE
[BUG] Horizontal reader bugs

### ISSUE THREAD

**Issue by Windmilll** [Paperback-iOS/app#378]
Bug 1. The status bar does not hide
**Description** 
The upper part of the screen which has the status bar is permanently blank. The time and battery status hides but the space is unusable for page space.
**Replicate** 
In horizontal reader, tap in the middle of the screen and zoom in, the top part of the screen will be blank.
**Expected** 
The top part of the screen where the status bar is, should be usable and hidden like in vertical reader or like the shounen jump app.
v0.5.0-r1.0.13 

Bug 2. Leaving the app then reopening causes pages to not be preloaded
**Description** 
while in horizontal reader, exitting the app then reopenning the app causes pages ahead to not be preloaded.
**Replicate** 
Be in horizontal reader in a manga, exit the app and wait a few seconds. Reopen the app and continue reading. The pages ahead will not be preloaded and they will only load once you swipe to them. The chapter must be reloaded for the preloading to re-enable
**Expected** 
Page preloading to always be active even after leaving the app and reopening
v0.5.0-r1.0.13 

Bug 3. The first double page never loads
**Description** 
The first double page of a chapter never loads unless you swipe forwards and back
**Replicate** 
Be in horizontal double page/auto-mode on landscape, open a new chapter. Wait. The page will never load unless forward and then swipe back.
**Expected**
For the first double pages to load properly
v0.5.0-r1.0.13

**Comment by Akiawa** [comment]
First "bug":

I don't believe it is really a bug, more like the page is not fit for the screen. 

Second Bug:
Already reported here; https://github.com/Paperback-iOS/app/issues/345

**Comment by Windmilll** [comment]
> First "bug":
> 
> I don't believe it is really a bug, more like the page is not fit for the screen.

Should the page size not be the same as the screen size? To reiterate I am referring to when zooming in and the page not fitting the screen space.
