### ISSUE TITLE
[REQUEST] Show followed mangas in search page

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#380]
**Description**
In the search menu, mangas that are already in our library should have a marker. This would look like the "downloaded chapters" marker but be on the bottom left and have no number.

**How would it improve the App?**
It would be much easier to consume new manga without repeatedly opening up existing mangas.

**Comment by Akiawa** [comment]
Duplicate of : https://github.com/Paperback-iOS/app/issues/122
