### ISSUE TITLE
[REQUEST] Move Cloudflare bypass to the discover page on the top left

### ISSUE THREAD

**Issue by MasterBladeX** [Paperback-iOS/app#382]
**Description**
I think that having the Cloudflare bypass on the front discover page will be less tedious than the system right now. As of right now you have to go into settings, external sources then the source then Cloudflare bypass. With this feature, you wouldn't have to go anywhere besides the discover page. It's a one-click and then you can access it instead of going into settings.

**How would it improve the App?**
This will improve the app by making Cloudflare bypass a lot quicker and easier to then ever to do. The button will also be out of the way so there should not be any problems with the GUI.

**Comment by Akiawa** [comment]
Implemented in 0.6 (2.0.1)
