### ISSUE TITLE
[BUG] Prevent empty "Genres" from being shown on the homepage

### ISSUE THREAD

**Issue by FramboisePi** [Paperback-iOS/app#384]
**Describe the bug**
An empty "Genres" row is shown on the homepage when the sources implements `getTags()` but does not return any tags.

**To Reproduce**
1. Install a source like Bato.to
1. Go to the homepage

 - An empty Genres row is shown.
 
![IMG_F2031870264C-1](https://user-images.githubusercontent.com/25133304/128470530-619b7830-a98b-4a58-8f38-76adfeb22a5e.jpeg)

**Expected behaviour**
This row could be masked when it does not contain anything

**App Version**
v0.6.0-b1.0.5
iPadOS 13.4.1 and iOS 14.6

---

On a second though, I'm not sure if it's related:

 - Sometimes, the first section label is also replaced by `Genres` (it may be useful to refresh a few times to see that).
 
![IMG_035D9A6E9E29-1](https://user-images.githubusercontent.com/25133304/128471105-69aff578-6d22-44a2-8c5d-cac5f0129d36.jpeg)

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.4-Beta)
