### ISSUE TITLE
[REQUEST] Display badges for unread chapters

### ISSUE THREAD

**Issue by tejassharma96** [Paperback-iOS/app#387]
**Description**
Currently you can see badges for (I think - it isn't super clear what triggers the visibility of the badge) number of updated chapters in your library. I'd like to be able to see the number of unread chapters as a badge generally (even if I just added the manga to my library)

**How would it improve the App?**
It'd be an easy and convenient way to visually see the number of remaining chapters for each manga without actually having to click into the manga and then click "all chapters".

**Comment by FaizanDurrani** [comment]
Duplicate of #123
