### ISSUE TITLE
[BUG] Installed trackers won’t update their installed status immediately

### ISSUE THREAD

**Issue by midi1996** [Paperback-iOS/app#389]
**Describe the bug**
Adding a tracker from the repo will not update its installation status until you close and go back to the repo browse menu. 

**To Reproduce**
1. Add tracking repository (https://paperback-ios.github.io/trackers-main/main) named PaperTrack
2. Click on "Browse PaperTrack"
3. Install tracker

**Expected behaviour**
The entry should show "REFRESH"

**App Version**
v0.6.0-r2.0.5

**Screenshots**
Video: 

https://media.discordapp.net/attachments/883026981082521660/883046545853939733/video0.mp4

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.6)
