### ISSUE TITLE
[BUG] Clearing updates removes the last badge instead of its own badge

### ISSUE THREAD

**Issue by jtcrde** [Paperback-iOS/app#391]
**Describe the bug**
When clearing updates on a manga, it always removes the last badge instead of its own badge.

**To Reproduce**
1. Open library with manga updates
2. Tap and hold on any manga
3. Select "Clear Updates"

**Expected behaviour**
The badge of the manga that's being cleared should be cleared rather than the last.

**App Version**
v0.6.0-r2.0.5

**Screenshots**
Video:
https://cdn.discordapp.com/attachments/702052855623843861/883057525073772564/video0.mp4

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.6)
