### ISSUE TITLE
[BUG] No back button for Anilist "Enabled Extentions"

### ISSUE THREAD

**Issue by UnityGrave** [Paperback-iOS/app#392]
**Describe the bug**
There is no way to go back to the main settings menu after pressing the Anilist option in "Enabled Extensions" category.
Note: I am using iOS 13.5 iPhone XS Max

**To Reproduce**
Steps to reproduce the behaviour
1. Open settings tab
2. Tap on "External Trackers"
3. Tap on "Anilist" in the Enabled Extensions category above the Available Repositories category.

**Expected behaviour**
There should be a back button to return to the main settings screen.

**App Version**
v0.6.0-r2.0.5

**Screenshots**
Video:
https://cdn.discordapp.com/attachments/702052855623843861/883062567210201138/video0.mp4

**Comment by FaizanDurrani** [comment]
Fixed in 0.6.0 (2.0.6)
