### ISSUE TITLE
[BUG] Duplicate Sources in Manga

### ISSUE THREAD

**Issue by delhunter** [Paperback-iOS/app#393]
**Describe the bug**
Each manga has the same source it is from listed twice in all chapters tab. 

**To Reproduce**
Appeared immediately after updating to 0.6, no settings were touched other than paperback login.

**Expected behaviour**
Each manga should only show the source once.

**App Version**
0.6

**Screenshots**
https://cdn.discordapp.com/attachments/883026981082521660/883046838473728031/image0.png
https://cdn.discordapp.com/attachments/874720156570513449/883077455399755776/image0.png

**Comment by FaizanDurrani** [comment]
Attach the backup you imported, also, were these there before the MD -> MD migration?

**Comment by delhunter** [comment]
It was before the MD to MD migration, and I didn't import a backup after installing 0.6. I decided to try a fresh install of the app and then used the last backup I made before the issue, and now everything is back to normal. No idea what caused the issue the first time around but I was able to fix it this way.

**Comment by delhunter** [comment]
Yes, I noticed the duplicates before migrating. They even show up in the
migration menu but selecting discard doesn’t discard them.

**Comment by FaizanDurrani** [comment]
Try again after running database repair from the settings
