### ISSUE TITLE
[BUG] Cannot unmerge sources 

### ISSUE THREAD

**Issue by ripleyo1z** [Paperback-iOS/app#399]
**Describe the bug**
Cannot unmerge a manga source.

**To Reproduce**
Pressing unmerge.

**Expected behaviour**
It is supposed to remove a manga source after selecting.

**App Version**
V. 0.6

**Screenshots**
If applicable, add screenshots to help explain

https://user-images.githubusercontent.com/90029053/132149168-af9b1fa4-9d9a-4b0d-9ee5-cf33f763392c.MP4

 your problem.

**Comment by FaizanDurrani** [comment]
Try using the Database Repair button in the settings and try again
