### ISSUE TITLE
[BUG] UNUSED Top bar on Horizontal View

### ISSUE THREAD

**Issue by vegedb** [Paperback-iOS/app#400]
**Describe the bug**
UNUSED Top bar on Horizontal View

**To Reproduce**
Read any comic on a 4:3 iPad on horizontal view.

**Expected behaviour**
Should fill the full height of the page. 

**App Version**
Public Release 0.6.0 (2.0.13)

Below is a GIF of Pinching and Zooming. The portion of the top side is **unused**.

**Screenshot**

White TOP bar
![white](https://user-images.githubusercontent.com/72070424/132699953-ea510ec8-f94a-4e30-a893-b07ba9e9fd8a.gif)

**Comment by Windmilll** [comment]
For what it‘s worth, after a bit of luck I have a quick workaround before this is fixed.

Be in a chapter with the overlay hidden. Press power button to lock device. Unlock device then show then hide the overlay, it should disappear the top bar.

**Comment by FaizanDurrani** [comment]
Added in 0.7 Build 16
