### ISSUE TITLE
[BUG] Share button not working

### ISSUE THREAD

**Issue by Saval-0** [Paperback-iOS/app#402]
I don't know if that's a bug or just a feature that is not implemented in the app yet but if I try to share something by clicking on the button, nothing happens.

Open a manga/manwha of your choice, click on the share icon.

After clicking the icon the IOS share menu should appear and let you share the desired content.

v0.5.0-r1.

https://user-images.githubusercontent.com/39965322/133568982-46e3f907-57fc-411c-afd3-56006103b183.mp4

**Comment by FaizanDurrani** [comment]
It is that way by design, the sources that implement that feature will open the manga in the browser
