### ISSUE TITLE
[REQUEST] Support the GIFs

### ISSUE THREAD

**Issue by Huynh12345678** [Paperback-iOS/app#404]
**Description**
support GIFs to appear animation on GIFs

**How would it improve the App?**
help the app can handle the GIFs images

**Comment by FaizanDurrani** [comment]
Added in 0.7

**Comment by hyoretsu** [comment]
Not sure if I should open another issue for this, but GIFs in manga covers aren’t supported.

**Comment by Celarye** [comment]
> Not sure if I should open another issue for this, but GIFs in manga covers aren’t supported.

Yes, a new issue is required.
