### ISSUE TITLE
[REQUEST] AltStore 3rd Party Repo

### ISSUE THREAD

**Issue by n0k0m3** [Paperback-iOS/app#405]
**Description**
An AltStore 3rd Party Repo for the app in an `apps.json` file at root of this repo, and a redirect from paperback.moe to the raw https://raw.githubusercontent.com/Paperback-iOS/app/master/apps.json (for example)

**How would it improve the App?**
Make it easier to update the app using AltStore beta

**Additional context**
- Repo format (`apps.json`) can be similar to this: https://9ani.app/api/altstore
- Trigger app.json update with a github action from your private repo after pushing release to this repo/manually trigger
- Method to fetch url for latest release ipa and update it in `apps.json`: 
  - GET https://api.github.com/repos/Paperback-iOS/app/releases -> `content[0]["assets_url"]` -> `assets_url`
  - GET `assets_url` -> `content[0]["browser_download_url"]`

**Comment by Celarye** [comment]
This has been added as far as I'm aware of: [altstore.json](https://github.com/Paperback-iOS/app/blob/6f40b8104d4ea045c41dd6962ac9d19636889acd/altstore.json).

**Comment by n0k0m3** [comment]
Thanks gonna close this issue. Solved by 6f40b81
