### ISSUE TITLE
Undefined is not an object MangaDex [BUG]

### ISSUE THREAD

**Issue by GigaMichaelMa** [Paperback-iOS/app#406]
**Describe the bug**
On addition to any non-cloudflare extension from https://paperback-ios.github.io/extensions-promises/, will result in an error.
Webview works fine and I can even login.  

**To Reproduce**
adding an non-cloudflare extension, scrolling to the extension on the homepage, or interacting with any of the UI in said extensions' homepage 
 
**App Version**
Public 0.6.0 (2.0.18) on ipad ios 14.4.2, installed via altstore 1.4.6

**Screenshots**
![IMG_0007](https://user-images.githubusercontent.com/47281827/135799662-993c48f4-2b7a-4f5b-a64d-b243b439d22c.PNG)

**Comment by TheNetsky** [comment]
You say "all" sources, so which have you tried, I only see MangaDex. MangaDex is known broken on that repo.

**Comment by GigaMichaelMa** [comment]
Just tried all the sources on that repo, and they work fine...  Just restarted the app and now all of them work (besides MangaDex). Any repos with a working mangadex extension?

**Comment by TheNetsky** [comment]
Next time, please use Discord. This is a very common problem and not an issue. You can get it from the External Repos channel within the Discord. 

Please close this issue.

**Comment by GigaMichaelMa** [comment]
Gotcha, thanks
