### ISSUE TITLE
[BUG] Paperback is not correctly displaying a chapter numbering.

### ISSUE THREAD

**Issue by apiweb** [Paperback-iOS/app#413]
**Describe the bug**
Some chapters do not have a sequential numbering or are special chapters in some manhwas, and they are usually named with prefixes. Such as ".1" or ".5".
However, Paperback cannot display these "special" chapters correctly.

**To Reproduce**
When looking on some sites (like HiperDex, for example) Manwa: Our Office Story, we can see that the last chapter was 61.5.

<img width="1161" alt="Screenshot 2021-11-07 at 21 36 30" src="https://user-images.githubusercontent.com/5881027/140662920-a05b826c-9467-4f71-8f37-8ae3c5fcd8f7.png">

-----

When I look up this Manhwa in Paperback, on the search page, it shows that the last chapter is 61.5. Correct.

![IMG_0030](https://user-images.githubusercontent.com/5881027/140662878-f715a7c3-0aa3-4277-be65-f282c21ba0e2.PNG)

-----

But when I go into the chapter view and go to the last chapter (61.5), it doesn't appear.

![IMG_0031](https://user-images.githubusercontent.com/5881027/140663087-c5b34271-6e20-4107-ae0a-88a2b61e45af.PNG)

-----

Chapter 61.5 is erroneously displayed as chapter 5, not chapter 61.5.

![IMG_0032](https://user-images.githubusercontent.com/5881027/140663095-5f3f4882-5a75-4f84-abe4-d3eabc476ec9.PNG)

-----

This problem is happening to every chapter of any manga that has a broken number. Some of the works below have chapters with broken numbers, like "125.1" or "145.5":
Our Office Story
My Kingdom (Secret Wars)
His Place

**Expected behaviour**
The listing of chapters should allow the display and correct ordering of works that have broken numbers:
Chapter 160
Chapter 161
Chapter 161.1
Chapter 162
Chapter 163
Chapter 163.1
Chapter 163.2
Chapter 163.3
Chapter 164

**App Version**
v0.6.2-r1.0.0

**Additional**
I don't know if this is a mistake by Paperback itself or the scrapper's extension on the site.
I looked at the code of the [extensions-common](https://github.com/Paperback-iOS/extensions-common) project, and I saw that in the [Chapters](https://github.com/Paperback-iOS/extensions-common/blob/63e6bb4a4e4a512aedca7c61a9d7c3080c240476/src/models/Chapter/index.ts#L23) model, the chapNum property only accepts Numbers.

```
/**
   * An identifier of which chapter number this is, in a given {@link Manga}
   */
  chapNum: number
```

I believe this may be causing a problem, but I'm not sure.

**Comment by FaizanDurrani** [comment]
Extension issue, has nothing to do with the app.
