### ISSUE TITLE
[REQUEST] Download Button on Title Page

### ISSUE THREAD

**Issue by Gruwen** [Paperback-iOS/app#415]
**Description**
A download button on the main title page.

**How would it improve the App?**
It’ll provide functionality and a better user experience than have to go to chapter list, then select, then download, then the popup if it’s in your library or not.

**Additional context**
An additional button besides the ones already on the title page. The button could be clicked to download a manga. 

Once clicked, if the title is not in your library, a popup will appear asking if you want to add it or download without adding it. Then, another popup will appear with two options: Download All or Download Individually if manga has more than one chapter. If individually, will switch to chapter list to select which chapter you wish to download. After selection download will begin. 

![2E0C5809-BDBD-42E9-AD44-D78F5D46EA81](https://user-images.githubusercontent.com/26881845/141153538-e6cdd49a-0e83-4978-aa31-08bc1aaf0daa.jpeg)

**Comment by XenitXTD** [comment]
With a popup list where you can say download all or select chapters or range of chapters to download

**Comment by FaizanDurrani** [comment]
Added in 0.7 build 16
