### ISSUE TITLE
[REQUEST] Unread Chapters Badge

### ISSUE THREAD

**Issue by Kapoopy** [Paperback-iOS/app#416]
**Description**
A clear description of the feature

Basically, a badge on the title cover that shows the unread chapters like Tachiyomi's. 

**How would it improve the App?**
How would the feature improve the app?

The feature would improve the app by allowing the users to check how many unread chapters are there efficiently instead of clicking the title and scrolling down to check how many unread chapters are there. By adding this feature, I think you can just completely remove the update count since the unread feature will also include the new updated chapter. This feature allows the users to browse their library efficiently.

**Comment by Akiawa** [comment]
DUPLICATES OF https://github.com/Paperback-iOS/app/issues/274 AND https://github.com/Paperback-iOS/app/issues/387 AND https://github.com/Paperback-iOS/app/issues/123
