### ISSUE TITLE
[REQUEST]Option to turn a page completely with one touch

### ISSUE THREAD

**Issue by coey0814** [Paperback-iOS/app#422]
**Description**
iPadOS 15.1
v0.6.2-r1.0.0
When turning a page in 'Vertical' mode, it skips 80% of the pages instead of completely turning one page at a time. 20% of the previous page remains. (With Tap sides to Navigate option enabled)
(I don't know if it's a bug or the dev's intention.)
For example, in the case of a paperback sample book, there are 5 pages, but 7 touches are required to read the entire book.

**How would it improve the App?**
1. You can see a lot of books with fewer touches. Eyes and hands are relaxed.
2. When you watch cartoons(manga), the content fits exactly as the author intended, So, peace of mind comes without complexity.

**Additional context**
Thank you for your hard work.

**Comment by FaizanDurrani** [comment]
Functionality is intended in vertical to keep a reference point to resume from. Completely turning it over might cause the reader to lose track of where they were while reading.

This isn't required in the horizontal reader because pages are isolated instead of being joined together.
