### ISSUE TITLE
[BUG] Chapters won't update when refreshing the library

### ISSUE THREAD

**Issue by Gigaplex1** [Paperback-iOS/app#425]
**Describe the bug**
Some Titles don't update new chapters while on the Library Overview. They only update when opening the Manga in the Library directly, therefore it's easy to miss new chapters.

**To Reproduce**
Refresh library and then go to individual manga which seem to have no new chapter. If there was a new chapter they will update it as soon as you open the manga.

**Expected behaviour**
All chapters should be updated when the library gets refreshed globally.

**App Version**
v0.6.2-r1.0.0

**Screenshots**
Here is an example with the title "A Happy couple" where you can see, that the chapter was released a day ago, but didn't show as "new chapter" until opened manually.
[https://imgur.com/a/SyrRrgd](https://imgur.com/a/SyrRrgd)

**Comment by FaizanDurrani** [comment]
The update depends on the titles being reported as “updated” by the source. Sometimes the title in your library can be pushed off the “updated” list on the source because of newer unrelated updates. Which is why the source stops reporting as “updated”.
