### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by ReeceMMI** [Paperback-iOS/app#428]
**Description**
A clear description of the feature
-It would be great if you could view the sources comments. It doesn't have to allow you to comment, just being able to view them at the end of the chapter, or even by clicking on a button that makes a popup for the current chapter would be nice.

**How would it improve the App?**
How would the feature improve the app?
-It would be a nice feature because I feel like people like seeing other peoples reactions on chapters a good deal.

**Additional context**

**Comment by FaizanDurrani** [comment]
Will not be implemented in the near future. The current design doesn’t support comments.
