### ISSUE TITLE
[REQUEST] Filter Mangadex Site Redirects 

### ISSUE THREAD

**Issue by Jewelio** [Paperback-iOS/app#429]
**Description**
A clear description of the feature
An option to filter out chapters that redirect to another website. Ex. Comikey
**How would it improve the App?**
How would the feature improve the app?
Will help the reader avoid blank chapters that won't load images since it’s a site redirect.
**Additional context**
An Arte chapter from Comikey. https://mangadex.org/title/c66d2a14-e0a2-4488-9023-abdab7249d61/arte ![10AFB40D-9E46-458D-B741-3F682EEC6487](https://user-images.githubusercontent.com/61297269/146629508-1794bed8-c8a0-4fbc-b42f-643ea1501080.png)

**Comment by FaizanDurrani** [comment]
This should be done source side, open an issue on the extensions-sources repository
