### ISSUE TITLE
[BUG] Cloudflare Bypass Not Working

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#431]
**Describe the bug**
Whenever I do a cloudflare bypass, it stays stuck in the checking browser page.

**To Reproduce**
1. Go to toonily source in homepage
2. Click the cloud icon 

**Expected behaviour**
Bypass to work

**App Version**
Eg: v0.6.2-r1.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/13932583/147390096-3ef38bdd-2df7-4002-ab53-77d248ab460d.png)

**Comment by Akiawa** [comment]
Keep trying, you didn't try hard enough.

**Comment by PythonCoderAS** [comment]
> Keep trying, you didn't try hard enough.

I waited 3 minutes!
