### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#433]
**Description**
A clear description of the feature

An alternative additional navigation medium 

**How would it improve the App?**
How would the feature improve the app?

This is one of those features you didn't know it's value until you experience it. This is a game changer when reading you can navigate from the comfort of your hand positioning without having to adjust every time for changing chapters etc

**Additional context**

![image](https://user-images.githubusercontent.com/5268461/147843861-460aede8-1da1-4dbb-9996-098bc23a0442.jpeg)

So when you press and hold a little wheel pops out with options to show chapter list or got to next or previous chapters or close etc

So where does it's value lie? When you reading for a while you will generally get into a comfortable form and this allows you to navigate without having to do anything except press and hold anywhere on the screen to do some standard actions

This is valuable on iPhones but it is monumental on iPad as you can have hands in corners and not make major movements to achieve simple objectives

**Comment by FaizanDurrani** [comment]
Not possible, Tap and bold gesture is linked to image saving.

alternatively, the new readers will eventually feature “one-handed” layout configuration soon after 0.7 release.

**Comment by XenitXTD** [comment]
@FaizanDurrani please seriously reconsider this

You can make image saving an option in this wheel

I Cannot stress how valuable this navigation alternative is to normal gestures

You only need to experience it in the mangaMax app to understand its value

I hate to mention other apps but this made that app stand out among others, this feature alone
