### ISSUE TITLE
[REQUEST] Chapter Page Thumbnail View

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#434]
**Description**
A clear description of the feature

The ability to view page thumbnails

**How would it improve the App?**
How would the feature improve the app?

The app does a phenomenal job of keeping track of where you are in a chapter including it's end, this would allow one to easily got to first page to reread something without having to manually scroll back

**Additional context**

Currently only way to go back to start or a chapter is by manually doing so a page viewing or jump to start would solve this

**Comment by FaizanDurrani** [comment]
A seek bar has been implemented in 0.7
