### ISSUE TITLE
[REQUEST] Background Downloads

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#435]
**Description**
A clear description of the feature

Ability to allow downloads to continue in the background without app on and in focus

**How would it improve the App?**
How would the feature improve the app?

Sometimes one wants to put something on download and while they wait do other things but the downloads stop if the device goes to sleep or app loses focus. Being able to do this in the background means you can rest assured that things will be downloaded and no need to check

**Additional context**

**Comment by nar1n** [comment]
This is currently not possible due to a limitation by iOS itself. Some apps like Altstore try to bypass this by playing a silent audio to force the app to run in background but this would kill battery life as downloading manga would take much longer than tasks ran by Altstore.

**Comment by XenitXTD** [comment]
Will look into this 

I find this interesting as MangaRock Achieved this as well as auto downloading new chapters years ago

**Comment by FaizanDurrani** [comment]
Not possible, limitation of iOS. The audio playback hack is against ToS.
