### ISSUE TITLE
[REQUEST] Chapter List View Button Move

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#437]
**Description**
A clear description of the feature

Move the chapter list view to a button with quicker access

**How would it improve the App?**
How would the feature improve the app?

Makes getting to chapter view quick and easy especially useful when migrating over to app

**Additional context**

So currently the more you do with a manga the further the chapter list view option slides down

Add more merges down it goes last chapter read push it down meaning there is no quick access to chapter view we just need a butting to get there

![image](https://user-images.githubusercontent.com/5268461/147844149-d70efff7-9cf7-460b-8d31-9bf0674bb353.jpeg)

![image](https://user-images.githubusercontent.com/5268461/147844153-ba7f0e01-d58b-4fe7-88fd-0daf93b6f16f.jpeg)

**Comment by FaizanDurrani** [comment]
Fixed in 0.7
