### ISSUE TITLE
[REQUEST] Latest Chapter on Thumbnail in Library view

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#438]
**Description**
A clear description of the feature

Show latest chapter on thumbnail in library view with a color background that shows if you have read it or not

**How would it improve the App?**
How would the feature improve the app?

This allows you to see chapter count for mangas you haven't read yet if you waiting for it to build up, it allows you to see latest chapter on ones you are following and with a simple background color you can know if you have read it or not and get an at a glance view on what you are tracking has updated with a chapter you have not read

**Additional context**

![image](https://user-images.githubusercontent.com/5268461/147844268-bff33860-b398-4c97-99ed-ffef20732623.jpeg)

**Comment by FaizanDurrani** [comment]
Not possible, there can be multiple sources merged into a single manga, determining the latest chapter for each merged source for every manga in the library will cause massive performance drawbacks.

**Comment by XenitXTD** [comment]
@FaizanDurrani i understand this multisource issue

But this ties with the other ticket where you set a primary merge source that becomes your tracker source and with that you can track chapters on your primary selected merge source and change it any time

I see that ticket has been considered and if so any chance of reopening and linking this to that?

**Comment by XenitXTD** [comment]
@FaizanDurrani please consider this in conjunction of setting a primary merge source

Once you define the source or primary that becomes the one to track and showing chapter numbers etc should be possible as now users can define what they want to track simply by setting primary and this becomes linked to that setting

**Comment by FaizanDurrani** [comment]
That does indeed solve the multi-source issue. While I won't make this a priority, I will try to get this in the final version of 0.7.
