### ISSUE TITLE
[REQUEST] Notifications: More Information

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#439]
**Description**
A clear description of the feature

More information in app notifications like what mangas were updated from a source

**How would it improve the App?**
How would the feature improve the app?

Currently you get notifications that just say source updated 4 manga with no indication as to what, without clear indication as to what is updating the notifications are just pointless ATM

**Additional context**

![image](https://user-images.githubusercontent.com/5268461/147844285-55213f85-9a11-4cf1-9652-80f5ee68cad9.jpeg)

EDIT: I know you get individual notifications 

But it would be neat if group notifications would be like

4 updates from MangaDex
Apotheosis, Naruto, one piece, Tales of Demons and Gods

**Comment by FaizanDurrani** [comment]
You can change to per manga notification from settings

**Comment by XenitXTD** [comment]
@FaizanDurrani the grouped notification doesn't give a breakdown of what updated

And the alternative is a notification per update

Ideally you would like a group notification with a list of what was updated
