### ISSUE TITLE
[BUG]library view layout display bugs

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#440]
**Describe the bug**

The layout of manga in the library sometimes has random gaps in it

**To Reproduce**
Steps to reproduce the behaviour

It's a display issue, in collections with no specific trigger just listing and seeing it

**Expected behaviour**

As is visible below there are gaps when listing chapters

![image](https://user-images.githubusercontent.com/5268461/147844326-19af7e15-7b25-47c3-8452-ef4dd4d3ce03.png)
![image](https://user-images.githubusercontent.com/5268461/147844330-8a12e58b-7792-4d82-9a9f-1e481dbae1bc.png)

**App Version**
Eg: v0.2-wip.3.1

V0.6.2-R1.0.0

**Screenshots**

**Comment by FaizanDurrani** [comment]
You have update grouping turned on, disable that

**Comment by XenitXTD** [comment]
Thanks

Didn't connect that dot
