### ISSUE TITLE
[BUG] FaceID requires manual trigger

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#441]
**Describe the bug**

When in library and viewing manga as you exit faceid is required but is automatic but requires manual tap to trigger

**To Reproduce**
Steps to reproduce the behaviour

Launch app, go to library and Face ID automatically authenticates, open manga to view description go back out now it authenticates again but this time or each time you must manually tap to trigger Face ID

**Expected behaviour**

FaceID should just automatically work, only requiring input where it couldn't trigger because you were out of focus etc

**App Version**
Eg: v0.2-wip.3.1

**Screenshots**

![image](https://user-images.githubusercontent.com/5268461/147844391-b32d45d5-986e-4c5a-a35a-da4a74109bd9.png)

**Comment by FaizanDurrani** [comment]
By design according to Apple’s guidelines

**Comment by XenitXTD** [comment]
@FaizanDurrani are you sure, not questioning your abilities just experience with apps says otherwise

But most other apps I interact with automatically trigger Face ID unless there is a failure to authenticate then it will wait to do this manually

I cannot stress how UX destroying this is when I go to library view a manga and have to manually trigger Face ID every single time I go out and view another etc

**Comment by FaizanDurrani** [comment]
Do you have “automatic faceid unlock” checked in settings?

**Comment by XenitXTD** [comment]
🤦‍♂️🙈
