### ISSUE TITLE
[BUG]Pull to Refresh Collections Updating all?

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#442]
**Describe the bug**

So when you go into a collection, in my case it has 6 manga pull to refresh to see if there is updates should be quick but takes long as it appears to trigger for all manga

**To Reproduce**
Steps to reproduce the behaviour

Have several manga overall in several collections, put one or two in a new collection and pull to refresh that collection and it takes long

**Expected behaviour**

Would expect a pull to refresh to be as quick as the amount of manga in that collection but now all bookmarks as a whole

**App Version**
Eg: v0.2-wip.3.1

V0.6.2-r1.0.0

**Screenshots**
If applicable, add screenshots to help explain your ![image](https://user-images.githubusercontent.com/5268461/147844442-41feebb7-6eb0-401a-8848-0446e2f5f0a5.png)problem.

**Comment by FaizanDurrani** [comment]
This is the indented behaviour at the moment. Will be updated in 0.7.
