### ISSUE TITLE
[BUG] Chapter Downloads will partially complete

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#444]
**Describe the bug**

So when bulk downloading, chapters will partially complete and the download move on without finishing it off

**To Reproduce**
Steps to reproduce the behaviour

Bulk download a 400+ continue doing things forget about it and device sleeps or you swap out and some chapters are only partially downloaded

**Expected behaviour**

It should continue and complete partials or redownload them without you haveing to remove download and require it

**App Version**
Eg: v0.2-wip.3.1

V0.6.2-r1.0.0

**Screenshots**

![image](https://user-images.githubusercontent.com/5268461/147844618-4f632484-2310-4f2a-82bd-6c4d858a47c1.png)

**Comment by FaizanDurrani** [comment]
It’s not partially complete, it errored out. Usually that happens when the source is slow or there are network problems.

**Comment by XenitXTD** [comment]
@FaizanDurrani would it help the app to have a toggle to filter out completed chapters so one can easily see what "failed" and what's in progress so as to reset downloads?

**Comment by FaizanDurrani** [comment]
I am not sure if that would be helpful, you can already see what downloads have failed simply by scrolling through the chapter list, the "failed" icon is quite visible.

You can also just select all the chapters again and queue them for download, it will skip the already downloaded ones.
