### ISSUE TITLE
[BUG] Pull to Refresh in other places triggers for manga library

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#446]
**Describe the bug**

So a pull to refresh in merge for instance will trigger a refresh in library

**To Reproduce**
Steps to reproduce the behaviour

Go to library open a manga tap merge in the search window pull down to refresh then close merge exit the mange description view and see the library refreshing which takes time

**Expected behaviour**

Pull to refresh should happen in that view not in another location

**App Version**
Eg: v0.2-wip.3.1

v0.6.2-r1.0.0

**Screenshots**

https://user-images.githubusercontent.com/5268461/147844775-a88c802f-f885-48d7-851d-e399de23a32b.MOV

**Comment by FaizanDurrani** [comment]
This is fixed in the manga view rework in 0.7
