### ISSUE TITLE
[BUG] Collections drag reorder overwrites others in edit mode

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#447]
**Describe the bug**

When creating collections if you are still in edit mode aka keyboard out and you drag it freaks or sometime doesn't move other times renames other collections 

**To Reproduce**
Steps to reproduce the behaviour

Go to bookmarks create serveral collections while in edit mode drag one from bottom up and you will see it's affect on other collections

**Expected behaviour**

Should be able to just reorder without it affecting other list items

**App Version**
Eg: v0.2-wip.3.1

V0.6.2-r1.0.0

**Screenshots**
https://user-images.githubusercontent.com/5268461/147844850-1d435b7c-c062-41c1-b3e1-bcb6ba8d2303.MOV

**Comment by FaizanDurrani** [comment]
Fixed in 0.7
