### ISSUE TITLE
[REQUEST] Separate first row buttons into two rows

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#448]
**Description**
On merged manga, the buttons on the first row are really tiny, and it would be nice if they were in two rows instead.

**How would it improve the App?**
It would make the buttons easier to use

**Additional context**
![image](https://user-images.githubusercontent.com/13932583/147862011-e5a85c72-90a8-434f-93bf-695bd8decc6d.jpeg)

**Comment by XenitXTD** [comment]
I actually think they are too big, so if this is considered it should be a configurable setting?

**Comment by FaizanDurrani** [comment]
The detail view is complete redesigned in 0.7

**Comment by PythonCoderAS** [comment]
> I actually think they are too big, so if this is considered it should be a configurable setting?

It depends on the device you use. They'll be much smaller on something like the iPhone 12 mini than on an iPad Pro.

**Comment by XenitXTD** [comment]
I am using iPhone 12

Would love an iPad just for manga and media tho

Looking forward to the v0.7 redesign they appear quite confident
