### ISSUE TITLE
[BUG] Anilist Traker - Unable to select or change status

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#449]
**Describe the bug**

Unable to select or change the status of a tracker linked to a manga

**To Reproduce**
Steps to reproduce the behaviour

Go to a bookmark add a tracker for tracking 

Try to manage it and select and change status nothing happens

**Expected behaviour**

Since there is no documentation on if this should be possible it is assumed you should be able to change the status as you can update chapters and unless you change the status it won't update or add to Anilist 

**App Version**
Eg: v0.2-wip.3.1

v0.6.2-r1.0.0

**Screenshots**

![image](https://user-images.githubusercontent.com/5268461/147867750-b49189f2-93b6-442d-837e-5fde82fe1707.png)

**Comment by FaizanDurrani** [comment]
Fixed in 0.7
