### ISSUE TITLE
[BUG] Collection Filter/Order settings

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#450]
**Describe the bug**

When trying to select the global filter options, when you select a sort by option the slider slides over to collections 

**To Reproduce**
Steps to reproduce the behaviour

Open you bookmarks

Go into a collection or all mange where you have filter options

Select the global tab, try changing the sort option and it slides over to the collection tab and global stays set to sort by name

**Expected behaviour**

Ability to set it under the global tab

Note: the apply globally button does affect the global tab just it creates a inconsistent experience when you are trying and slider slides giving the experience that it's defaulting to the collection 

**App Version**
Eg: v0.2-wip.3.1

V0.6.2-r1.0.0

**Screenshots**

![image](https://user-images.githubusercontent.com/5268461/147867837-1b6f2a52-fe8d-4ee2-b4ff-4024d231a8ad.png)

**Comment by FaizanDurrani** [comment]
Intended behaviour, when you are change a setting you’re making an override for that specific collection which is why the slider switches to collection to reflect that this collection has an override. You can apply the override to all collections by pressing apply globally.
