### ISSUE TITLE
[BUG] Recent Search List is Random

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#452]
**Describe the bug**

So the list of recent searches is random and not in order of your recents history

**To Reproduce**
Steps to reproduce the behaviour

Go to your searches if you have a recents list you can easily see the randomization behaviour by simply deleting one of the searches

**Expected behaviour**

List should be a fixed ascending order of your search history from most recent to least

**App Version**
Eg: v0.2-wip.3.1

v0.6.2-r1.0.0

**Screenshots**

![image](https://user-images.githubusercontent.com/5268461/147868121-6241c088-7970-4dea-8a9a-8b00be50e2aa.jpeg)![image](https://user-images.githubusercontent.com/5268461/147868124-ec01d696-f051-4c28-ba16-ed685fb3bed2.png)

**Comment by FaizanDurrani** [comment]
Added in 0.7 Build 16
