### ISSUE TITLE
[REQUEST] Collection Subfolders/Tags

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#454]
**Description**
A clear description of the feature

Either the ability to have subfolders on collections or tags where you can tag mangas

**How would it improve the App?**
How would the feature improve the app?

So when you bookmarks collections become large you like to break them down into small chunks to be easier to digest and browse and organize 

So having a manga collection with a genre subfolder like "shonen" would help to organize things as that grows

Alternatively tagging might help here

**Additional context**

**Comment by FaizanDurrani** [comment]
Searching via tag is planned but subfolders will not be implemented, you can have a title in more than one collection so just make multiple collections for now.
