### ISSUE TITLE
[REQUEST] Auto Download New Chapters on select manga

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#455]
**Description**
A clear description of the feature

The ability to select certain mangas namely those you are actively tracking to auto download new chapters

**How would it improve the App?**
How would the feature improve the app?

This would remove the need to manually manage this, and then your manga you are actively tracking can always be ready regardless of connectivity

**Additional context**

Use the ability in IOS to periodically check for downloads to download individual chapters, this has been done before

How would one know which to do?

If a primary source is defined aka in the merge you can track a manga its status and latest releases based on the primary source

Ticket logged to that effect here

https://github.com/Paperback-iOS/app/issues/436

**Comment by FaizanDurrani** [comment]
> Use the ability in IOS to periodically check for downloads to download individual chapters, this has been done before
Where exactly have you seen this functionality?

As far as I am aware, background downloads are not possible, and anything queued for download from a background job won't start unless you're in the app.

**Comment by XenitXTD** [comment]
@FaizanDurrani i have seen this in different ways in several apps and manga apps of old had this 

Reading up on this you can use background support or background fetch but the interval is at iOS discretion to execute and not triggerable on demand

Referring to samples

https://developer.couchbase.com/tutorial-background-refresh-ios-uikit

https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background

However I will acknowledge you knowledge my far outstrip mine and I am at your mercy for its viability

**Comment by FaizanDurrani** [comment]
As I said, queuing from the background is possible but they won't be downloaded unless the app is in the foreground.

And queued downloads aren't really useful when you have to wait for them to download anyways when you start the app.

**Comment by XenitXTD** [comment]
@FaizanDurrani I believe there is still value in this request with the ability to auto download updates in the background while you are in the app

Would you consider this where new chapters auto download as soon as app is launched for anything you set to do so?

**Comment by FaizanDurrani** [comment]
Sure, open a feature request for auto queuing chapter downloads based on updates.

However, a pre-requisite for that would be to allow titles to always be checked for updates (on app launch, for instance) instead of relying on the source to provide a list of updated titles, so the said feature would not be implemented unless the pre-requisite is satisfied.
