### ISSUE TITLE
[REQUEST] Option to Have Downloads in the Bottom Toolbar

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#460]
**Description**
A clear description of the feature

Rather than Set this, optionally have it as a setting where once set the downloads section has a dedicated space on the toolbar

**How would it improve the App?**
How would the feature improve the app?

It will allow you to at any point jump to your downloads and see the progress or what's there or pick up reading from there. 

**Additional context**

Would also be nice that while you can view a queue when something is actively downloading it shows it at the top of this page Page

Something like this?

![IMG_0715](https://user-images.githubusercontent.com/5268461/147927451-a64abbba-d354-41f9-84e5-1ab67e39dfd7.PNG)

Mind me using the library page as reference but then you can add filter options like normal library pages here to filter updated etc

**Comment by TheNetsky** [comment]
On 0.7 we already have 5 icons on the toolbar, I personally think it would be too cluttered. The download tab within the library tab is enough. Besides that, I think most of the userbase doesn't download manga regardless.
So I disagree with this.

**Comment by FaizanDurrani** [comment]
As @TheNetsky has stated, the History/Recents button is back in the bottom tab bar in 0.7 so adding another button would make it cluttered.

That being said, I do acknowledge that the Library tab is overall a bit tedious to navigate on iPhones and to address that the Library tab will be getting some UX modifications for iPhones in 0.8.

**Comment by XenitXTD** [comment]
@FaizanDurrani @TheNetsky any chance to make this a setting?

I don't know the complexity involved or even if you would consider this but being able to toggle this would be nice for those who heavily use it...

People that come from regions with Poor Connectivity will download on wifi when available and read when not, I am confident your user base will explode once this app is officially published and there will be more people that value this?

**Comment by TheNetsky** [comment]
It would still make more sense to have it within the user's library regardless. Paper said he'll overhaul the library. So all you're asking for is a way to maybe save 1 tap on the screen? I personally don't think it's worth it.

**Comment by XenitXTD** [comment]
Will await the redesign then and see
