### ISSUE TITLE
[REQUEST] Unread Chapters/Updates/Latest Chapters Feature Expansion

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#465]
**Description**
A clear description of the feature

This is an expansion of other requests with a bit additional, where the ability to see the latest chapter as well as the unread counts as well as updates since last viewed

**How would it improve the App?**
How would the feature improve the app?

So there are a couple of states around chapters on manga, first being able to see the latest chapter, second being able to at a glance see how many unread chapters you have and lastly to see how many updates have happened since you last viewed or inspected your library

Being able to get a glance of these numbers in library view is of value to all users in several ways, some being that you can easily see what has a lot of chapters if you looking to pick up something new and don't want to start something you are tracking but has low chapter counts, seeing your unread chapters for similar reasons will at a glance let you decide to continue because enough chapters have built up and lastly if you are actively tracking a manga seeing update counts since you last viewed the app helps

**Additional context**

Optionally on top of this, the ability to clear update counts is also valuable as if you have taken a look at your library and decide that everything you want to update on you have read and everything else you are waiting on can clear not to bug you, this way it will show you updates since that last cleared state.

this requires 3 markers and below are just some suggestions for this.

1 latest chapters

So have a view of the Latest Chapter / Max Chapter in bottom right with a color background that signals if you have read the latest chapter... this is of benefit for using color to quickly see what you have not read the latest chapter of instantly

Example Unread chapter is latest chapter number with red background
![IMG_44E8F3021CFF-1 2](https://user-images.githubusercontent.com/5268461/147932545-ee6aa8a9-067f-40a4-bd4c-98bd7d60192c.jpeg)

Read Chapter with blue background
![IMG_44E8F3021CFF-1 4](https://user-images.githubusercontent.com/5268461/147932558-f20ded3e-9a67-450d-b62b-e839a6f44a6a.jpeg)

2 showing both unread chapter counts as well as updates however on can clear the update counts as a means of tracking updates since last viewed.

![IMG_44E8F3021CFF-1](https://user-images.githubusercontent.com/5268461/147932618-83e7f6be-76de-493d-ba77-356266d68524.jpeg)

The reason for having both update counts and unread is one is to track your progress the other to track updates since you last viewed it with the ability to clear

the benefit of also using colored background on chapter count is so that when there is no unread chapters and it doesn't show a 0 but hides it you can see you are up to date and have read all available chapters while at the same time being able to quickly view what you are up to date on and what not simply by color identification.

The following tickets have been logged for this in parts but I have extended and summarized it here.

#416 #387 #438

The Unread and Latest chapter is made possible by #436 and the updates already exists, only the ability to clear those in bulk is not.

**Comment by TheNetsky** [comment]
https://github.com/Paperback-iOS/app/issues/249 ?

**Comment by XenitXTD** [comment]
@TheNetsky Thanks for that

I tried reading through all the tickets but I missed that one
