### ISSUE TITLE
[BUG] Deleted Chapters Persist on Updated Manga

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#470]
**Describe the bug**
If a manga has updates, and one of the previous chapters are deleted, the deleted chapter persists unless manually deleted.

**To Reproduce**
Re: Above

**Expected behaviour**
Deleted chapters to also be deleted via the app

**App Version**
Eg: v0.6.2-r1.0.0

**Screenshots**
N/A

**Comment by FaizanDurrani** [comment]
Paperback 0.7 now tries to remove any chapter discrepancy between the source and the local database.
