### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by viroid1** [Paperback-iOS/app#473]
**Describe the bug**
When I launch Paperback I get a blank/black screen and this error message pops up

**To Reproduce**
Launching Paperback

**Expected behaviour**
The app should normally load titles and images

**App Version**
v0.6.2-r1.0.0

**Screenshots**
![IMG_1241](https://user-images.githubusercontent.com/97866704/149708565-f76bdaa8-e798-43b2-ba30-d90620de3937.png)

**Comment by Akiawa** [comment]
This is not a bug. It is intended. Paperback does not come with copyrighted content.

**Comment by viroid1** [comment]
got it thank you

**Comment by Akiawa** [comment]
I would recommend you joining the Paperback Discord server and use the #welcome channel
