### ISSUE TITLE
[REQUEST] Forgive Me - Allow me back into discord server

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#474]
I understandably got blacklisted in your servers as I got a spam link from a trusted source that ultimately rippled to your server

It took me a day or two to understand not being an avid discord user

I have since reset everything on my account and ask if you guys will be kind enough to unban me from your server please

**Comment by FaizanDurrani** [comment]
To protect our members, we will **not** be unbanning you. Feel free to join the server with a different account.
