### ISSUE TITLE
[REQUEST] Share button to open manga chapter in other apps

### ISSUE THREAD

**Issue by frykauf** [Paperback-iOS/app#478]
**Description**
Share button on force touch in chapter list (you could also have it when selecting multiple chapters), and in reader view as seperate button.

**How would it improve the App?**

It would allow users to read chapters in other apps - effectively using Paperback as library manager/downloader.
Which is also useful because we don’t have that on iOS either.

**Additional context**
It is definitely more useful that just the option to share single pages for instagram.

**Comment by FaizanDurrani** [comment]
This isn't in the scope of Paperback at the moment
