### ISSUE TITLE
[BUG] - App crashes when scrolling the chapter list 

### ISSUE THREAD

**Issue by fma16** [Paperback-iOS/app#48]
**Describe the bug**
The app crashes when scrolling the list on the chapter view

**To Reproduce**
Go to follow tab
Open Solo Leveling under « Reading » list
Click to the chapter list icon
Scrolling the list
Languages selected : English, French

**Expected behaviour**
The app shouldn’t crash

**App Version**
Eg: v0.2-wip.6.1

**Screenshots**

**Comment by FaizanDurrani** [comment]
Let me know if the issue is fixed in the latest WIP build

**Comment by fma16** [comment]
Nope, still happens. You need to have at least a chapter downloaded (in the middle of the list) for the crash to happen.
I’ll send you the log.

**Comment by ConradWeiser** [comment]
Tested on the latest App Store version of Paperback, this issue appears to be resolved in a previous patch. Thanks for the bug report! If this still somehow occurs for you, please feel free to reopen this issue and we'll look a little deeper.
