### ISSUE TITLE
[BUG] Searching within a collection searches the entire library

### ISSUE THREAD

**Issue by Hasnain271** [Paperback-iOS/app#481]
**Describe the bug**
When you open a collection and search on the search bar for a specific manga in that collection, it searches your entire library instead of that one specific collection.

**To Reproduce**
Click a collection in your library tab and try to search for a manga not in that collection. 

**Expected behaviour**
Search for manga only in the collection you are in.

**App Version**
 v0.6.2-r1.0.0

**Screenshots**
I have attached a video showing my problem.

https://user-images.githubusercontent.com/25558632/152096463-5501a5a4-4470-4347-8813-a84505a6dc98.mp4

**Comment by FaizanDurrani** [comment]
Fixed in 0.7 build 16
