### ISSUE TITLE
PaperbackError 300: JSError Undefined

### ISSUE THREAD

**Issue by ChrisBryann** [Paperback-iOS/app#484]
![IMG_6665](https://user-images.githubusercontent.com/63214365/153079751-b6e1b7f8-576c-4d36-9f04-defa12837ce2.jpg)

I was about to refresh my manga from Toonily for latest updates, but I got the error shown above instead. I couldn't fetch the latest updates for any Toonily manga that I bookmarked, but for the rest of the sources, I didn't get this error. Please help. Thank you!

**Comment by TheNetsky** [comment]
Would be nice if you used Discord instead. We're missing a LOT of crucial info here.

**Comment by ChrisBryann** [comment]
I am in the discord channel but I don't see a text channel for bug issue report

**Comment by TheNetsky** [comment]
Please check again.
And read the entirety of the "welcome" channel please.
