### ISSUE TITLE
[REQUEST] Swipe gestures for going back or exiting (iOS like)

### ISSUE THREAD

**Issue by Syklou** [Paperback-iOS/app#485]
**Description**
Being able to exit the About section of the manga by swiping down (like in the Photos app of iOS)
Being able to exit a chapter by swiping down to exit (just like in most of iOS, good example is Photos app)
**How would it improve the App?**
Well, you wouldn't have to reach all the way to the x when you are reading a chapter or reaching all the way to the *close* in the about section of a manga 
**Additional context**
I don't think additional context is needed

**Comment by FaizanDurrani** [comment]
Added in 0.7 build 16
