### ISSUE TITLE
[REQUEST] Unread chapter font color change

### ISSUE THREAD

**Issue by REKTL** [Paperback-iOS/app#490]
**Description**
Request to change the color of read vs unread chapters in the chapter list to something more easily distinguished. The current scheme is simply light grey vs. white which can be difficult to see in certain lighting. 

**How would it improve the App?**
Simple fix to discern read vs. unread chapters in the chapter list.

**Additional context**
The addition of the red font “current page” tag in the experimental features does help tremendously. However if we are changing the format of the chapter list view already. I’ve always found it difficult to discern between the read/unread colors when reading in brighter lit rooms; more so since the 0.7 update.  It would be my imagination but background color seems darker than before and it accents the lighter colors on the page. Since seeing the red font tag it occurs to me it could be beneficial to alter the font color scheme to something more easily distinguishable.

**Comment by FaizanDurrani** [comment]
Old view is deprecated, use the reworked view instead
