### ISSUE TITLE
[BUG] Incorrect page numbers on new reader

### ISSUE THREAD

**Issue by rintendou** [Paperback-iOS/app#491]
**Describe the bug**
New reader page doesn't not properly update when moving onto the next chapter. Instead of saying (starting page)/(last page), it takes the (last page) of the previous chapters and makes it the (starting page) of the new chapter. Issue fixes once you reach page 2.

**To Reproduce**
Go to any manga and move onto the next chapter using the new reader. 

**Expected behaviour**
Progress should say page 1/36 instead of 59/36.

**App Version**
Eg: v0.7 (3)

**Screenshots**
Video attached.
https://user-images.githubusercontent.com/83848755/153695871-8037274e-f0f5-4776-8dd7-98f2880a7dad.MOV

**Comment by FaizanDurrani** [comment]
This should be fixed past 0.7-r31, reopen if it isnt
