### ISSUE TITLE
[BUG] Incorrect reader

### ISSUE THREAD

**Issue by rintendou** [Paperback-iOS/app#492]
**Describe the bug**
If you select the new manga view rework, but did not select the new reader. If you click read using the rework, it puts you in the new reader.

**To Reproduce**
Turn on the new manga rework but disable the new manga reader. Then, open up any manga by clicking "Read Now" on the manga page.

**Expected behaviour**
Should use the old manga reader.

**App Version**
v0.7 (3)
**Screenshots**
Video attached.

https://user-images.githubusercontent.com/83848755/153790224-5e860bbb-a207-483c-bc61-8322c1a540ab.MOV

**Comment by FaizanDurrani** [comment]
Fixed in 0.7 Build 16
