### ISSUE TITLE
[REQUEST] Add grouping function in library

### ISSUE THREAD

**Issue by LE0riginZ** [Paperback-iOS/app#494]
**Description**
Having a grouping/catalogue function for library to group our manga into folders

**How would it improve the App?**
Helps with organisation of our favourite manga (group into genres like shounen, seinen, GOATed series, etc.)

**Additional context**
NIL

**Comment by XenitXTD** [comment]
Is this not the purpose of collections?

Where you create a collection essentially a folder and then move manga into one or more?

**Comment by LE0riginZ** [comment]
How to add a collection was a little hard to find, but i've found it alr, thank you
