### ISSUE TITLE
[BUG] The app sometimes jumps to the end of the next chapter

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#499]
**Describe the bug**
When I use the "Pull to Next Chapter" feature, it'll sometimes open to the bottom of the next chapter instead of the top.

**To Reproduce**
Go to a chapter and pull down. It doesn't happen 100% of the time, although the next chapter being pre-downloaded may make a difference

**Expected behaviour**
The next chapter to open at the top

**App Version**
Eg: v0.6.2-r17

**Screenshots**

**Comment by Akiawa** [comment]
Update. Idiota.

**Comment by PythonCoderAS** [comment]
> Update.

Will that fix the bug?

**Comment by FaizanDurrani** [comment]
New reader in 0.7 fixes this issue
