### ISSUE TITLE
[REQUEST] Adding a black bar between pages in longstrip mode.

### ISSUE THREAD

**Issue by angodee** [Paperback-iOS/app#50]
**Description**
Adding a black bar between pages in longstrip mode. 
**How would it improve the App?**
It'd be pretty useful to easily be able to differentiate one page from another. 
**Additional context**
![Image (2)](https://user-images.githubusercontent.com/63850753/79561634-f49d4f80-80a9-11ea-9769-fc1b4a0e7dcc.jpeg)

**Comment by MoaYenrai** [comment]
In my opinion this should only be added as an optional feature, since the feature will make the experience of reading webtoons worse.

**Comment by nevoreko** [comment]
Agreed, pages are made to be continuous, it would be a downgrade

**Comment by angodee** [comment]
Never really thought about it. 

I was too accustomed to MR lol

**Comment by FaizanDurrani** [comment]
Implemented in experimental reader
