### ISSUE TITLE
[BUG] New reader's double tap feature

### ISSUE THREAD

**Issue by rintendou** [Paperback-iOS/app#501]
**Describe the bug**
The double tap feature of the new reader is slightly buggy. It's slower than the old reader and it also flashes your screen black. Rarely, it teleports you to a random page of the chapter you're on.

**To Reproduce**
Double-tap zoom using the new reader.

**Expected behaviour**
Just like the old reader.

**App Version**
Eg: v0.7 (all builds)

**Screenshots**
https://user-images.githubusercontent.com/83848755/157677385-c1131b8c-b962-43f7-b239-158ac86fe666.MOV

**Comment by FaizanDurrani** [comment]
Fixed in 0.7 Build 17
