### ISSUE TITLE
[REQUEST] Bookmarks in "Source" tabs

### ISSUE THREAD

**Issue by Akiawa** [Paperback-iOS/app#502]
**Description**
Bookmarks already appear on the source main page but not when you're opening stuff.

**How would it improve the App?**
It'll let you know what you read while browsing

**Comment by DecliningLotus** [comment]
It'd be super useful to have this, especially since the library section itself is inconsistent with detecting new releases. I tend to just scroll through the 'latest updates' tab of a source but it lacks the bookmark icon making it harder to notice which releases are related to me.
