### ISSUE TITLE
[BUG] iPad slide over on chapters page renders strangely

### ISSUE THREAD

**Issue by Windmilll** [Paperback-iOS/app#504]
**Describe the bug**
The layout on ipad slide over view or the 1/4 multitask view cuts off buttons and requires scrolling to get to manga information.

**To Reproduce**
Open Paperback in slide over or in 1/4 multitasking view and access a manga.

**Expected behaviour**
Move information up and be able to access everything or be able to choose between information page and chapter list.

**App Version**
V0.6.2 r-17

**Screenshots**
![69611F3B-DE02-482B-971E-0CCE8CAEEC78](https://user-images.githubusercontent.com/87407761/158050636-7547e29d-b531-427d-bf9c-5f5139f84f2b.jpeg)
![485FCA08-7D59-40EB-94CB-91FF5AE7E8F5](https://user-images.githubusercontent.com/87407761/158050642-8213fb01-a463-4e96-b083-a02f0cc0b6e9.jpeg)

**Comment by FaizanDurrani** [comment]
Use the new reworked manga view in 0.7
