### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#506]
**Describe the bug**
On iOS 15.4, saving an image causes the manga chapter to close, and I can't get back into it without restarting the app. 

**To Reproduce**
Started after iOS 15.4 update: turn on image saving in the reader, and try to save an image to the camera roll. The image saves, but the chapter closes. 

**Expected behaviour**
It should keep the chapter open

**App Version**
0.7-r19 (also tried r17 and an uninstall and reinstall of r19 that cleared my data)
iOS 15.4
iPhone 13 Pro Max

**Screenshots**

**Comment by FaizanDurrani** [comment]
Fixed in the new readers, use them instead
