### ISSUE TITLE
[BUG] Issues with orientation switch on iPhone

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#511]
**Describe the bug**
On iPhone, when I'm in a library/collection and I switch to landscape orientation (which is never on purpose), the top bar of the app disappears. When I switch back to portrait, the top bar comes back, but it has the wrong thing in the top-left corner (looks like a "sidebar" icon from iPad instead of the back button it *should* be), and I'm unable to get back to the collection list without restarting the app.

**To Reproduce**
On iPhone, open up the library or a collection, and switch to landscape orientation. You'll see the top bar missing. Change back to portrait, and you'll see the "sidebar" icon in the top-left, and you'll be unable to get back to the collection list.

**Expected behaviour**
The top bar should stay the same regardless of any orientation changes.

**App Version**
0.7-r19
iPhone 13 Pro Max

**Screenshots**
Initially, in Portrait
![image](https://user-images.githubusercontent.com/657766/158864586-7b3a12db-299b-4e3f-a40f-4993d751c105.jpeg)
Switch to Landscape
![image](https://user-images.githubusercontent.com/657766/158864615-17926fea-3e42-4a70-8a66-930af22835aa.jpeg)
Switch back to Portrait
![image](https://user-images.githubusercontent.com/657766/158864645-e1e7ec5f-12ae-4fa9-9ce4-a641537b6b90.jpeg)

**Comment by FaizanDurrani** [comment]
What iOS version is this?

**Comment by 0lsn** [comment]
The same thing is happening to me with your [Public Release 0.6.2 (1.0.0)]. Could you somehow unlock this one Patreon feature that allows us to use the new experimental view feature so we can fix the orientation bug ourselves? I am signing the IPAs myself.

**Comment by henderea** [comment]
Actually, I was seeing this on the list of series, and the new view is only for the manga info and the reader, not the list of series. So turning that on wouldn't fix my issue. And I tried, so I know that for a fact.

On that note, this is still happening with 0.7-r24, which is the latest available to me right now as a Patreon supporter. As mentioned, enabling the experimental manga view doesn't help, though I'm not sure why it would, since that's a different screen. Though the issue happens on the manga list even if I do the rotation while viewing the info on a manga.

As a new discovery, it seems like the back button might be returning sometimes when I go away from the app and come back (without closing it), so there might be something fixing it when the app wakes up from standby. It seems a bit inconsistent, so I can't say for sure.

**Comment by FaizanDurrani** [comment]
Hmm, since this isn't a huge issue atm I'll be pushing it to 0.8 since the library is getting a refresh in 0.8 anyways.
