### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DRBPTR** [Paperback-iOS/app#512]
Every time I save a panel, it closes the manga & then I can’t open that manga or any other manga until I close out and reopen the app. I have the latest available public version.

**Comment by henderea** [comment]
This is apparently an issue with iOS 15.4, and if you turn on the new manga view and reader in the experimental feature settings, you'll be able to do it fine. It's only the old reader that has the issue.

**Comment by DRBPTR** [comment]
> This is apparently an issue with iOS 15.4, and if you turn on the new manga view and reader in the experimental feature settings, you'll be able to do it fine. It's only the old reader that has the issue.


![C42E970A-8B68-49C1-BBE0-B5C7D56F333F](https://user-images.githubusercontent.com/101838563/159128267-73ab7a8a-d043-4f83-8771-df1b2c6d753a.png)

There’s nothing in those settings for me.

**Comment by TheNetsky** [comment]
> > This is apparently an issue with iOS 15.4, and if you turn on the new manga view and reader in the experimental feature settings, you'll be able to do it fine. It's only the old reader that has the issue.
> 
> ![C42E970A-8B68-49C1-BBE0-B5C7D56F333F](https://user-images.githubusercontent.com/101838563/159128267-73ab7a8a-d043-4f83-8771-df1b2c6d753a.png)
> 
> There’s nothing in those settings for me.

What's your app version and are you a Patreon?

**Comment by DRBPTR** [comment]
> > > This is apparently an issue with iOS 15.4, and if you turn on the new manga view and reader in the experimental feature settings, you'll be able to do it fine. It's only the old reader that has the issue.
> > 
> > 
> > ![C42E970A-8B68-49C1-BBE0-B5C7D56F333F](https://user-images.githubusercontent.com/101838563/159128267-73ab7a8a-d043-4f83-8771-df1b2c6d753a.png)
> > There’s nothing in those settings for me.
> 
> What's your app version and are you a Patreon?



Whatever the most recent public version is.

**Comment by DRBPTR** [comment]
![DAE4D784-153C-46A9-98A4-907127C87F62](https://user-images.githubusercontent.com/101838563/159131284-22e4b608-4076-418c-9a0e-8593d23ad67e.png)

this is the version I have
