### ISSUE TITLE
[REQUEST] In new reader, respect reading direction for chapter arrows

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#513]
**Description**
In the new reader, right now when I have my reading direction set to right-to-left, the chapter change arrow on the right side goes to the next chapter instead of the previous one. 

**How would it improve the App?**
The chapter change arrows would actually make sense for the reading direction. The old reader behaves as I would expect, with the right-side arrow going to the previous chapter. 

**Additional context**

**Comment by henderea** [comment]
Ah, and on a similar topic, the scroll bar (or whatever that is) at the bottom of the new reader should probably match the reading direction too.

**Comment by FaizanDurrani** [comment]
Chapter chevrons now respect the reader direction (starting from 0.7 build 23), open a separate issue for the page selector
