### ISSUE TITLE
[BUG] Inconsistent Search/Cancel button

### ISSUE THREAD

**Issue by elfensky** [Paperback-iOS/app#514]
**Describe the bug**
Selecting a tag when using search disables the search button. I then need to select the text input, and press "cancel" to initiate the search

**To Reproduce**
Have MangaDex as your source. Select a tag in the search tab. 

**Expected behaviour**
The search button should remain enabled when only tags are selected with no text. It should change to "cancel" only once I pressed it and initiated a search. 

**App Version**
2.1.8

**Screenshots**
[Video showcasing the issue](https://youtu.be/5aNOriEHlZU)

**Comment by FaizanDurrani** [comment]
Fixed in 0.7-r30
