### ISSUE TITLE
[BUG]Can't open any other manga after saving from one

### ISSUE THREAD

**Issue by ZipperedJon** [Paperback-iOS/app#518]
**Describe the bug**
After saving to images it closes the current manga and won't be able to open any other manga until force closing the app

**To Reproduce**
1. Open manga you want to save a panel from
2. Hold click on the panel
3. Save>Save to photos
4. Try to open manga to read again

**Expected behavior**
Should let you continue reading after saving the image

**App Version**
v0.6.2-r1.0.0

**Screenshots**
Small Video to show issue: https://i.imgur.com/JaBSQzd.mp4

**Comment by FaizanDurrani** [comment]
Fixed in the reader rework, accessed from experimental settings
