### ISSUE TITLE
[BUG] Chapter not always marked read when reading in double page

### ISSUE THREAD

**Issue by DanielKovalevich** [Paperback-iOS/app#52]
**Describe the bug**
The chapter isn't always marked read when I am reading in the horizontal double page reader. I noticed that I could sometimes get it to mark read if I dragged to the right even more.

**To Reproduce**
Read in the double page reader and go to the end of a chapter. Doesn't always mark as read.

**Expected behaviour**
It should be marking as read. 

**App Version**
v0.2-wip.6.1

**iOS Version**
13.4.5 (beta)

**Comment by FaizanDurrani** [comment]
Should be fixed in b8.1
