### ISSUE TITLE
[BUG] Performance issue?

### ISSUE THREAD

**Issue by henderea** [Paperback-iOS/app#520]
**Describe the bug**
On my iPhone, when downloading a lot of chapters, my phone often heats up a lot and drains the battery. I'm not sure if the issue is with the app or with the MangaDex source, but it happens consistently when I'm downloading a lot (and I only do that from MangaDex). 

**To Reproduce**
Queue a lot of chapters (probably at least 20 regular length ones to be sure) for download on an iPhone and wait for it to heat up. I suspect cpu monitoring might tell you something too. 

**Expected behaviour**
Ideally it wouldn't heat up my phone so much. It also impacts battery life a lot. 

**App Version**
0.7-r24 (though it's been going on for a fairly long time; I can't remember exactly how far back)
iPhone 13 Pro Max (though it may not be iPhone-specific; iPads probably just don't heat up as much)
iOS 15.4 (and earlier versions)
Source: MangaDex ("primary" repo)

**Screenshots**

**Comment by FaizanDurrani** [comment]
It's downloading a lot of files and writing them to storage, that's to be expected.
Have you tried downloading files over large periods of time with other apps? (ex: Genshin)

**Comment by henderea** [comment]
Not a whole lot, but I suppose you have a point. Though when I download a lot in the BookWalker Global app, I don't usually see this issue. So it might just be the page-by-page download method. Maybe some sort of grouped download might be better if sources supported it.

**Comment by FaizanDurrani** [comment]
Source websites aren't really made with downloading in mind so none of them support grouped downloads.
BookWalker is its own source for content so they probably have an optimized delivery system that ensures low filesize and efficient content delivery.
