### ISSUE TITLE
[REQUEST] Option To Disable New Page Scroller

### ISSUE THREAD

**Issue by MiBinger** [Paperback-iOS/app#522]
Hello!
**Description**
I love all the new changes coming to the UI, the view rework and new reader are great but I'm wondering if it would be possible to have this new UI while also disabling some of the features. The old method of scrolling + zooming was perfect, this new one feels clunky and unresponsive. I am also finding it difficult for me to hide the chapter overlay when testing this new view. The previous view I was able to tap once in order to hide/reveal the overlay, with the new one it feels like I am fighting with it to work correctly.

**How would it improve the App?**
I think having the New UI matched with the previous method of navigation for chapters would be the best option. The old method of scrolling + zooming just felt more natural than this. Currently I just have the Manga View rework enabled and not the new reader as I find that ruins my reading experience.

**Additional context**
![Prev_View](https://user-images.githubusercontent.com/47586386/160899613-b189dd4c-6e12-4c2b-848c-e2bb4462c7bf.png)
![New_View](https://user-images.githubusercontent.com/47586386/160899617-dc8f73da-5f23-4af2-9b23-cf499e38741d.png)

**Comment by FaizanDurrani** [comment]
Cant you just hide the overlay when reading by tapping in the middle of the reader?

**Comment by MiBinger** [comment]
@FaizanDurrani looks like that feature may have been adjusted. while using the new reader view I was having to tap the screen 2-3 times before the overlay would respond but now it appears to be working with just one tap. still, I think the ability to freely zoom in + out felt way smoother on the old reader. feels like I am chained to that new scroll bar if that makes any sense

**Comment by FaizanDurrani** [comment]
If you want to zoom out more than the screen, turn on pillarbox. Apart from that the bounce has been removed to facilitate the infinite chapter scrolling
