### ISSUE TITLE
[REQUEST] Enhancing the library selection button features in Manga Info page.

### ISSUE THREAD

**Issue by McMiller81** [Paperback-iOS/app#523]
**Description**
The Library button on the individual manga Info page
A Request for bringing back a old Feature or enhancing the current one
- Request that using the button when a library is selected for a manga to not be reset first and then opened to the library selection page.
- - Previously pressing the button would open the library selection page and show current selection that you could then remove/add or change.

**How would it improve the App?**
Having over 300 manga in my libraries i have to juggle them between libraries and also as the button is not currently showing in what library the content is i have to search for that before doing changes.
having the option of opening the page with previous selection i can just go see under what library the manga is even without changes.
- At the moment my only option is to clear all selections and then open the selection page and make new selections

**Additional context**
There is another possible solution for this give the user the option to select a individual color for each library so that they can be indetified easily.

**Comment by FaizanDurrani** [comment]
Have you tried using the new reworked view? It might have what you want

**Comment by FaizanDurrani** [comment]
![8F970533-247C-4D79-B9B5-BFBF136928EE](https://user-images.githubusercontent.com/4832034/161040435-b2bf1b75-c03f-4d5d-a0cb-0eb6a3a02c63.png)

**Comment by McMiller81** [comment]
The Settings ->  Experimental Features -> Manga View Rework
Setting gives me back the selection view on already selected libraries.

Would love it on the main version.

**Comment by FaizanDurrani** [comment]
That will be the main version in a couple of updates. The current manga view has been deprecated and will soon be removed.
