### ISSUE TITLE
[REQUEST] Option to move "X" button in the new reader.

### ISSUE THREAD

**Issue by NeoMasamune** [Paperback-iOS/app#524]
**Description**
I think that it would be useful to have an option to move the "X" button that exits a chapter to the top left of the screen from its default location at the top right. There already exists an option to move the chevron and settings button locations.

**How would it improve the App?**
It would improve the usability when reading manga by providing users the ability to have access to the majority of actions with one hand when reading manga horizontally.

**Comment by FaizanDurrani** [comment]
Can you not just use the swipe-down gesture instead?

**Comment by NeoMasamune** [comment]
I had no idea that such a gesture existed :O That behaves perfectly. Thank you!
