### ISSUE TITLE
[BUG] Unmerge Sources Shows Same Source Name for All Sources

### ISSUE THREAD

**Issue by PythonCoderAS** [Paperback-iOS/app#526]
**Describe the bug**
In the unmerge manga menu, all of the sources have the same name.

**To Reproduce**
Unknown

**Expected behaviour**
Sources to have different names

**App Version**
Eg: v0.7-r24

**Screenshots**
![image](https://user-images.githubusercontent.com/13932583/161426807-32f8ec3b-e1cd-4738-9f3d-307bd06b539c.png)

**Comment by PythonCoderAS** [comment]
Also, ![image](https://user-images.githubusercontent.com/13932583/161426826-f5ff4e58-4fb0-48bc-aabe-9a784a8bc3fa.png)

**Comment by FaizanDurrani** [comment]
Will not be fixed. The old view is due removal in a couple of updates. It is only there right now to provide a fallback should anything in the new view break.
