### ISSUE TITLE
[BUG] saving image of a page closes the manga and it can’t be reopened without restarting app

### ISSUE THREAD

**Issue by Gocards458** [Paperback-iOS/app#529]
**Describe the bug**
When saving the image of a page while reading a manga it closes the manga and can’t be reopened unless you close and reopen the app

**To Reproduce** 
Open a manga chapter press and hold down on the page until the save button appears then hit it and select save image in the menu that appears

**Expected behaviour**
After saving the image of a page you should be back at that page able to continue reading

**App Version**
v0.7-r24

**Comment by TheNetsky** [comment]
Enabled the new reader from the experimental view, please close this issue.
