### ISSUE TITLE
[REQUEST] Tap sides to change pages

### ISSUE THREAD

**Issue by Sai-P** [Paperback-iOS/app#53]
**Description**
Implement the ability to change pages by tapping on either side of the screen (i.e. right-side to go backwards, left-side to go forwards in the case of the right-left page progression).

**How would it improve the App?**
Easier to flip through pages while reading manga with only one hand on your device.

**Comment by ConradWeiser** [comment]
Is this a relevant feature on **all** devices? Maybe I can understand this on tablet horizontal views. 
Is this applicable even on an iphone?

Probably. 
I'll look into this one.
