### ISSUE TITLE
[BUG] Add Source search crashes often

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#532]
**Describe the bug**

When using new reader and tapping to add source it's a hit and a miss on how many times you can do this sometimes on second attempt it will freeze and crash or sometimes 3rd source addition crashes

**To Reproduce**
Steps to reproduce the behaviour

Add manga keep tapping to add sources and it will crash

**Expected behaviour**

Add source search endlessly without crashes

**App Version**
Eg: v0.2-wip.3.1

v0.7 b24 iOS 15.4 iPhone 12 Pro 

**Screenshots**

https://user-images.githubusercontent.com/5268461/162311430-13568299-453d-44f0-be74-be6b333553df.MOV

**Comment by FaizanDurrani** [comment]
do you have async sources turned on?

**Comment by XenitXTD** [comment]
@FaizanDurrani 

It happens on both turned on and not

I have tested both settings and behavior remains unchanged

**Comment by XenitXTD** [comment]
@FaizanDurrani 

This is still an issue on v0.7 r38, search in general it happens less when async is turned of but still just a general issue of freezing an app crashing when searching will multiple sources or trying to add a source to manga.

**Comment by FaizanDurrani** [comment]
Its highly likely that this is a source issue. Nevertheless, I'll investigate it more to see if its possible to fix it

**Comment by FaizanDurrani** [comment]
This should be fixed in r40.
