### ISSUE TITLE
[BUG] Select Chapters in New UI

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#536]
**Describe the bug**

So in the new manga view you can download all chapters but you can select chapters to download or any select you can do actions on it such as remove downloaded chapters selectively etc

**To Reproduce**
Steps to reproduce the behaviour

Open any manga click the 3 dots to select chapters once selected the dots becomes a cross and you have no actions you can perform on selected chapters such as remove selected downloads or selectively download chapters

**Expected behaviour**

Old ui offered selective chapter download and removal which is gone in the new layout

**App Version**
Eg: v0.2-wip.3.1

v0.7 b24 iOS 15.4 iPhone 12 Pro

**Screenshots**

https://user-images.githubusercontent.com/5268461/162325961-440cb16c-387b-48c8-b628-6d0a07a32229.MOV

**Comment by FaizanDurrani** [comment]
Scroll the options in the toolbar, there's a Manage Download button

**Comment by XenitXTD** [comment]
Oh wow didn't even notice the change
