### ISSUE TITLE
[REQUEST] Tap to search on artist or author

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#537]
**Description**
A clear description of the feature

Ability to tap to search on artist or author similar to how it was enabled in v0.7 for the tags

**How would it improve the App?**
How would the feature improve the app?

Sometimes you want to find other works by an artist or author and similar to how tap to search on tags made things seem less this would add the same quality of life improvement

**Additional context**

**Comment by TheNetsky** [comment]
Most sources do not support this feature and cannot be added to them, so I don't think this is a good idea.

**Comment by TheNetsky** [comment]
Everything manga related usually comes from a source, only _some_ sources support this feature.

**Comment by Akiawa** [comment]
Kind of dupe: https://github.com/Paperback-iOS/app/issues/121

**Comment by FaizanDurrani** [comment]
As Netsky has said, the majority of the sources will not be able to support this hence it will not be considered.
Sources that want to support "search by author" can simply add a text field in the search tab.
