### ISSUE TITLE
[BUG] Crashing after recent iOS update (iPad 15.4.1)

### ISSUE THREAD

**Issue by monk050** [Paperback-iOS/app#539]
**Describe the bug**
when opening chapters from either Library or Discovery tab with repos MangaSee or Manga4life app will crash. added other repos to test. hit and miss with Mangeakakalot and MangaDex with crashes

0.7 (26). downgraded to 0.7 (25) to test with same results

Appears after updating iPad to 15.4.1 earlier today. was working prior to this iOS update

logs showing a few errors at various crashes

JSError SyntaxError [PaperbackError(300)] JSError SyntaxError: JSON Parse error: Unrecognized token '<' - parse@[native code]

**To Reproduce**
try opening any mange from those repos listed above

**Expected behaviour**

**App Version**
0.7 (26). downgraded to 0.7 (25) with same results

**Screenshots**
n/a

**Comment by TheNetsky** [comment]
"JSError SyntaxError [PaperbackError(300)] JSError SyntaxError: JSON Parse error: Unrecognized token '<' - parse@[native code]" See the #source-status channel within Discord to resolve this.

For the other crashes, enable new manga reader and manga view from experimental settings

**Comment by monk050** [comment]
enable experimental settings - resolved issue. will close. thank you
