### ISSUE TITLE
[BUG] bulk download causes library to have render issues

### ISSUE THREAD

**Issue by XenitXTD** [Paperback-iOS/app#540]
**Describe the bug**

When using a bulk download or download all, the UI freezes while it's attempting to queue downloads but once it becomes responsive again it causes UI to have display issues and not render normally until you quit the app

**To Reproduce**
Steps to reproduce the behaviour

Go to library, get a manga 250 chapters and then download all once it finally queues you will see the behaviour

**Expected behaviour**

Continue using app as normal after download and preferably not have it freeze up while queuing 

**App Version**
Eg: v0.2-wip.3.1

v0.7 b24 iOS 15.4 iPhone 12 Pro

**Screenshots**

https://user-images.githubusercontent.com/5268461/162483989-024f4158-f30a-4ce2-9ca1-07f1aaedb42d.MOV

https://user-images.githubusercontent.com/5268461/162484018-34ded21c-dc18-4d40-9914-d6919484a845.MOV

**Comment by FaizanDurrani** [comment]
This should be fixed past 0.7-r31

**Comment by XenitXTD** [comment]
@FaizanDurrani 

On 0.7 r34 and this is still unchanged behaviour

Only change is that it doesn't hang while queuing but the display issues are the same until you quit and relaunch app

**Comment by XenitXTD** [comment]
@FaizanDurrani i have noticed the behaviour is still on r45

I also noticed when you do a bulk download it doesn't actually queue all the chapters

Example something with 800 chapters you say download all it starts queuing and then somewhere the queue process dies or fails and after that render issues begin

It doesn't loose what it queues but ultimately you have to queue items more than once to get everything

This doesn't happen on smaller sets of bulk downloads

**Comment by FaizanDurrani** [comment]
@XenitXTD Can you check if it still persists on 0.8
