### ISSUE TITLE
[BUG] download the manga and strange popup comes up

### ISSUE THREAD

**Issue by dtantono** [Paperback-iOS/app#541]
**Describe the bug**
strange popup comes up

**To Reproduce**
I download some mangas and then couple of minutes later strange popup shows up

**Expected behaviour**
that annoying popup should not happened and then it crashed

**App Version**
Paperback 0.6.2 with iOS 15.4.1

**Screenshots**
![Screenshot 2022-04-12 at 14 51 22](https://user-images.githubusercontent.com/29157187/162890427-a7c61d73-c426-4974-b0ef-60cc876083c8.png)

<img width="375" alt="Screenshot 2022-04-12 at 17 57 46" src="https://user-images.githubusercontent.com/29157187/162923392-6f401ca9-07d7-44a9-89f7-20322a9b7034.png">

**Comment by XenitXTD** [comment]
This is common and expected as a failure can occur during download

Those pop up's are option and can be hidden in the settings from showing aka you don't want to see when connection errors occur as these are cause by several things like for example cloud fare etc

If you don't want to see them hide them using settings->error popup toggle

**Comment by dtantono** [comment]
Yes, thanks for the advice because the pop-up is quite intrusive and it leads the app to crash afterwards. I hope it this app can be more stable.

**Comment by dtantono** [comment]
@nar1n I deleted it and since this is the default source of this app, when this app got an update. this source will return. is that so?

**Comment by XenitXTD** [comment]
> @nar1n I deleted it and since this is the default source of this app, when this app got an update. this source will return. is that so?

@dtantono if you delete the app and install it from scratch then you will likely get it but if you perform updates to keep your library sources etc don't reset but it keeps your previous settings 

Alternatively you can perform a backup to restore but in all my updates this source has never reappeared
