### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YoinkVevo** [Paperback-iOS/app#549]
Using version 0.6.2-r1.0.0
Downloaded through AltStore 

when refreshing all of your manga, instead of updating the numbers to show what has how many updates, none of the numbers change.
This is consistent and sometimes the numbers change but only for a few random manga leaving the rest untouched.

**Comment by FaizanDurrani** [comment]
Updates are handled by sources, if a source doesn't mark a title as updated the app will not fetch chapters for that title.
