### ISSUE TITLE
[BUG] Sort by Last Updated

### ISSUE THREAD

**Issue by Atem83** [Paperback-iOS/app#55]
**Describe the bug**
The results from the "Sort by Last Updated" ignores your language filter so even new chapters for unwanted language will up the manga in your list.

**To Reproduce**
Just need to "Sort by Last Updated" in the app to see that some of the most recent manga haven't any new chapter for you language (eg : english) but appear "recent" because a new chapter in another language is out ...

**Expected behaviour**
The "Sort by Last Updated" need to show only manga updated for chapters from your language filter.

**App Version**
v0.2-public

**Comment by ConradWeiser** [comment]
Implemented properly in future versions of the app
