### ISSUE TITLE
[BUG]App crashing when searching

### ISSUE THREAD

**Issue by babykimbap** [Paperback-iOS/app#552]
**Describe the bug**
App crashes when making a search under search everything 

**To Reproduce**
Searching tomodachi or tomodachi game freezes the app and then crashes

**Expected behaviour**
Search results should be showing when typing the keywords

**App Version**
Eg: v0.7-r26

**Screenshots**

**Comment by TheNetsky** [comment]
Please fill in the entire issue template before submitting. You didn't provide any app verison. But I think you're using 0.7? If so enable experimental View and Reader. 

Close this issue.

**Comment by babykimbap** [comment]
I toggled those options and it still crashed.
