### ISSUE TITLE
[BUG] exited from reader after using "Save Image" function

### ISSUE THREAD

**Issue by Tornado333** [Paperback-iOS/app#554]
**Describe the bug**
Being exited from reading page after using the "save image" function on a panel. 
After saving panel can't re-enter the manga (or any other manga) until reloading the app.
Bug seems to only happen when saving image, not when sharing to discord, instagram, etc

note : panel is being saved to camera roll, no problems with that

**To Reproduce**
Open any manga > hold down panel > save > save image > (this is when you get exited from reading page) > try to open the manga again, or any other manga

**Expected behaviour**
Should be re-enetered into the reading page after saving panel and not be exited from page.

**App Version**
downloaded through altstore
v0.6.2-r1.0.0
IOS 15.4.1
iPhone 8 Plus

**Screenshots**
https://user-images.githubusercontent.com/92910272/164960516-6b784a1b-194c-43f8-9355-021339cc311b.MOV

**Comment by TheNetsky** [comment]
You're using an old version of the app. Use 0.7 and enable experimental reader and manga view.

Close this issue.
