### ISSUE TITLE
[REQUEST]Folders in Library

### ISSUE THREAD

**Issue by Yoshiii49** [Paperback-iOS/app#555]
**Description**
Adding the function to create folders and folders within those.

**How would it improve the App?**
People could organize their library the way they want. This makes it easier for people with 200-300 Manga in their library (or anyone obsessed with having control over how their library is organized)

**Additional Info**
A few examples on why i would love this feature
-I usually put the Manga where i am at the newest chapter on top so i don’t miss anything. Therefore there is no real order
-Sometimes i just wanna check on a specific Manga and having it in a folder where i know it is there would make this way easier.
-I added so much that i sometimes forget if i really read something or not and it would be helpful to have  “reading”, “have to read” “not up to date” folders

**Comment by moonpen** [comment]
Doesn't this already exist in the form of collections?

**Comment by FaizanDurrani** [comment]
There are indeed no plans in the foreseeable future to support subfolders. It is already possible to organize your library into collections to separate "Reading", "On-Hold", "Planning" titles etc.
