### ISSUE TITLE
[BUG] Search causes app to freeze and crash

### ISSUE THREAD

**Issue by Arzo99** [Paperback-iOS/app#556]
**Describe the bug**
App freezes and crashes when searching anything almost everytime and can’t delete individual search terms without clearing search history 

**To Reproduce**
Search any manga, scroll to the bottom then it freezes and crashes

**Expected behaviour**
Search Results without app crash and anle to delete search terms

**App Version**
Eg: v0.2-wip.3.1
v0.7

**Screenshots**

https://user-images.githubusercontent.com/104381610/165146478-c411f1a5-1e12-4468-952d-cc3abaa3a288.MOV

https://user-images.githubusercontent.com/104381610/165146804-220ad06a-4627-4a8f-830d-54e486144cfe.MOV

Also tried the suggested experimental features no problems solved

**Comment by Arzo99** [comment]
> Try removing a couple of sources

It did fix the issue a bit but it still crashes often

**Comment by FaizanDurrani** [comment]
Make sure your app is updated

**Comment by Arzo99** [comment]
> Make sure your app is updated

I have the v0.7-r24, is it the latest? If not how do I update it?

**Comment by FaizanDurrani** [comment]
> This is still an issue on v0.7 r38

How many sources do you have installed?

**Comment by XenitXTD** [comment]
I had 20~ about I have reduced this and also disabled some sources from global search

Just something worth noting I had all these installed on v0.62 and it never crashed the apps they would just fade away if no results nothing to crash the app

**Comment by FaizanDurrani** [comment]
It's a memory leak somewhere, I am still investigating it.

**Comment by FaizanDurrani** [comment]
This should be fixed in r40, reopen if it isn't.
