### ISSUE TITLE
[BUG] - Experimental Reader does not open comics in the library

### ISSUE THREAD

**Issue by ChristophWally** [Paperback-iOS/app#558]
**Describe the bug**

Device: iPad Pro 12.9. 
OS: 15.4  
App Version: 0.7 (26)

When using the experimental reader it does not allow me to open up manga comics from my library. I tap the thumbnail and nothing happens. 

This only occurs on the iPad and functions fine on the iPhone.
Only occurs in the library.

**To Reproduce**
1) Open Paperback on iPad.
2) Enable new reader in experimental settings.
3) Attempt to open manga in library.

**Expected behaviour**
Open into the manga comic’s chapter list.

**Comment by FaizanDurrani** [comment]
Update to r28 and tell me if this issue is still present

**Comment by ChristophWally** [comment]
I’ve updated to r30, and it’s still present. Uninstalled and reinstalled the app as well.

My model is iPad Pro (12.9-inch) (M1 5th generation) if that helps at all.

**Comment by FaizanDurrani** [comment]
Upload a video here to better illustrate whats happening.

**Comment by ChristophWally** [comment]
Video can be found [here](https://youtu.be/ekr2Xf0uS94).

It is demonstrating outside of the library when I click on a manga comic it loads into the chapter select screen fine. However, when I go into the library at around 19-21 seconds in I am clicking on a thumbnail and nothing happens. At 23 seconds I am showing the hold gesture still works.

**Comment by FaizanDurrani** [comment]
You’re not on the latest version, also it seems that you’re using a mouse/trackpad try tapping the item.

**Comment by ChristophWally** [comment]
The video I recorded was before I updated, but I uploaded it to demonstrate the issue. I can confirm that I have updated r30 (also reinstalled the app) and the same issue occurs. Also I used a trackpad to illustrate the issue, it’s the same if I tap the item with.a finger (nothing opens).

**Comment by FaizanDurrani** [comment]
Try tapping “downloaded manga” then “all manga” in the sidebar.

**Comment by ChristophWally** [comment]
Not sure why but this seems to have worked. I can now access the chapter selection screen. Thanks!
