### ISSUE TITLE
[BUG] Legacy Reader not working unless Legacy Manga View is also on

### ISSUE THREAD

**Issue by RiceManDan** [Paperback-iOS/app#563]
**Describe the bug**
The Legacy Reader setting does not apply unless the Legacy Manga View setting is also on

**To Reproduce**
Turn on legacy reader. Enter a chapter. The reader is still the new version. Turn on legacy manga view. The manga page changes to legacy view and the reader now changes to the legacy reader as well.

**Expected behaviour**
The legacy reader should function independently from the legacy manga view toggle and turn on without needing to turn in legacy manga view.

**App Version**
iPad Air 5th gen, iPadOS 15.4.1, v.0.7-r31

**Comment by FaizanDurrani** [comment]
Fixed in 0.7-r34
