### ISSUE TITLE
[REQUEST] Add support for ProMotion/120Hz for vertical manga scrolling.

### ISSUE THREAD

**Issue by NeloBlivion** [Paperback-iOS/app#564]
**Description**
On the new reader, the scrolling animation seems to be locked to 60Hz. While this is the standard refresh rate for most Apple devices, the iPad Pro has had ProMotion for several years and recent (and likely future) iPhone models also support 120hz. 

The legacy reader view seems to support it, but the new reader doesn't; as such, the viewing experience on the new reader is subpar for users that have ProMotion devices. It would be great if the new reader was updated to support it once again.

**How would it improve the App?**
This would greatly improve the reading experience for users at 120Hz, which is also bound to become more and more common in the near future.

**Comment by krumble1** [comment]
I have the same issue, and a friend reminded me that I can just go into Settings > Experimental Features and enable the option for Legacy Reader. This seems to have restored ProMotion (120hz refresh rate) functionality for me.

**Comment by FaizanDurrani** [comment]
This should be fixed in r36, if you are using AltStore please wait for an update.

**Comment by NeloBlivion** [comment]
> This should be fixed in r36, if you are using AltStore please wait for an update.

Using Testflight, doesn't seem to be fixed in any of the new releases (36, 37, 38). Though if it's ready, I hope to see it implemented soon.

**Comment by FaizanDurrani** [comment]
@NeloBlivion Have you tried it on the r38 release? It was released a couple of minutes ago
Also, is it possible for you to record your screen while you scroll with a separate device? (slow-mo mode if you have iPhone)

**Comment by FaizanDurrani** [comment]
Unfortunately, I don't have a ProMotion enabled iDevice (apart from MBP) so I can't exactly test it all that well.

**Comment by NeloBlivion** [comment]
@FaizanDurrani Yep, no luck on r38. Hadn't considered recording with another device, so i'll see If i can get that video.

**Comment by NeloBlivion** [comment]
Here @FaizanDurrani, not as noticeable on video compared to in person but you can see the difference between legacy and new reader scrolling
https://gofile.io/d/9mFYDb

**Comment by FaizanDurrani** [comment]
I've tweaked the flick response on the vertical reader, it should be closer to the default scrollview now.
