### ISSUE TITLE
Custom themes can mess up the readability of buttons in the manga viewer.

### ISSUE THREAD

**Issue by Celarye** [Paperback-iOS/app#567]
The function that adapts the manga viewer buttons color to the color of the manga thumbnail may interfere with a custom theme. A fix could be making a setting to turn of this function. Example: https://imgur.com/a/MzxCFzQ

**Comment by RiceManDan** [comment]
Where does one find custom themes?

**Comment by Celarye** [comment]
@RiceManDan join the discord https://discord.gg/paperback, accept the server rules and go to the #themes channel.

**Comment by RiceManDan** [comment]
It doesn't seem to appear for me. Is it exclusive to supporters?

https://i.imgur.com/9h55oF5.png

**Comment by Celarye** [comment]
It isn’t exclusive no, it will appear under #releases after you accepted the server rules in #welcome.
