### ISSUE TITLE
[BUG] App crash when pressing Group View.

### ISSUE THREAD

**Issue by otDan** [Paperback-iOS/app#572]
**Describe the bug**
Pressing Group View crashes app.

**To Reproduce**
Have two sources in one view and press the button.

**Expected behaviour**
Show the Group View page instead of the app shutting down.

**App Version**
v0.7-r35

**Screenshots**

https://user-images.githubusercontent.com/59731738/166687791-282880fc-44eb-4443-986b-2876338bf25c.MP4

**Comment by FaizanDurrani** [comment]
This was fixed in r38 and above
