### ISSUE TITLE
Unable to open Mangakakalot after v0.7-r36 update

### ISSUE THREAD

**Issue by amoskoh99** [Paperback-iOS/app#573]
**Describe the bug**
After the latest update (as of 5/5/22), Mangakakalot mangas show this error message when opening a chapter, even after reinstalling

**To Reproduce**
Go to Mangakakalot and open a random chapter.

**Expected behaviour**
When I press the "Read Now" button, I expect it to open the chapter that I am reading instead of the error message popping up

App Version
v0.7-r36

**Screenshot**: ![image](https://user-images.githubusercontent.com/16147113/166861143-f2c129bf-a626-4127-bebb-7e2ee7218a03.png)

**Comment by timbroder** [comment]
I can reproduce this as well. Same app version

**Comment by TheNetsky** [comment]
Source issue, don't open issues on this Github for source related problems @timbroder @amoskoh99 
Please close this.
