### ISSUE TITLE
[BUG] Adding new source and removing old one for mangas make them inaccessible

### ISSUE THREAD

**Issue by TheZoc** [Paperback-iOS/app#578]
**Describe the bug**
This bugs happens when trying to add new sources to replace old broken/unsupported ones.

**To Reproduce**
Having selected a source on Mangakakalot (or Mangabat or any of the currently unsupported ones that were previously supported):
- Click on the 3 dots above the chapter listing
- Click Add Source
- Search for a working source
- Click on the new working source
- Select "Yes, Import merged sources" (Not sure what this options does. The text with the ID seems unfinished for now. I haven't tried pressing "No" or "Abort"
- When you're back on the chapter list, click the 3 dots, click on "Remove Source" and remove the old, unfunctional source.
- This will make it look like as it's working. Now, go back one screen, to the "All Manga" list
- Select the previously modified manga
- You will get into an infinite loop trying to load the manga

I did try to making a backup and opening it with a text editor, it seems that the `"sourceId"` field is gone from the json file.

**Expected behaviour**
Be able to load the modified manga with the new source.
If it could load the already broken ones so I could add the new source again, that would be perfect.
Deleting the broken ones would be helpful otherwise, from the "All Mangas" list.

**App Version**
v0.7-r36

**Screenshots**
![bug](https://user-images.githubusercontent.com/924927/167317910-1a34f616-5868-47bc-9a2d-9581c4a270f0.jpg)

**Comment by moonpen** [comment]
Also had the same issue when migrating sources and trying to remove old source from the manga leaves it in a infinite loop

**Comment by FaizanDurrani** [comment]
This should be fixed in r38

**Comment by moonpen** [comment]
Tested with 2 different manga's seems to be resolved
