### ISSUE TITLE
[BUG] UI is empty, nothing is shown. Error popup JSError SyntaxError [PaperbackError(300)]

### ISSUE THREAD

**Issue by Charlweed** [Paperback-iOS/app#579]
**Describe the bug**
This is a brand-new first-time install. Error is encountered on an iPad with iPadOS 15.4.1 and an iPhone with iOS 15. Same vehavior is seen on 0.6.2, and v0.7-r34
 
When opening the App, the screen is empty, no manga are shown. Error popup displays .
Paperback: JSError SyntaxError [PaperbackError(300)] JSError SyntaxError: JSON Parse error: Unrecognized token '<' - parse@[native code] @ promiseReactionJob@[native code]:606:76

**To Reproduce**
This happens every time the app is launched.  Waiting does not update anything.

**Expected behaviour**
I expect the UI to correctly update and show manga.

**App Version**
0.6.2, and v0.7-r34

**Screenshots**
![paperback_error](https://user-images.githubusercontent.com/328567/167512567-c491da91-6fce-49f5-86b2-7646b52f1b6f.PNG)

**Comment by TheNetsky** [comment]
Not an app issue, source issue. Join the Discord instead,
Please close this,

**Comment by Charlweed** [comment]
Ok, I'll close it. When I join the discord server, which channel should I join, and what should I ask?
