### ISSUE TITLE
[REQUEST] Add a source list

### ISSUE THREAD

**Issue by thatgirlsarah** [Paperback-iOS/app#581]
**Description**
Don’t know if anybody said this already but there should be a source list similar to tachiyomi where you can download sources directly.

**How would it improve the App?**
Since the discord got rid of the #external-repos channel, it’s hard to find sources.

**Comment by Jxfe** [comment]
Paperback currently and will never support external repositories. You are free to add your own but they will never provide or tell you where to get one. Apple app store prohibits any app that does this which is why you don't see a reader in the iOS Store unlike Android.

**Comment by thatgirlsarah** [comment]
Oh ok. It's just that it's hard to google for sources because nothing shows up and I don't know how to develop my own.

**Comment by Jxfe** [comment]
DM me on Discord weeb#7820

**Comment by XenitXTD** [comment]
We really need a fit repo with a list of links to 3rd party sources because they gonna be hard to find now

**Comment by Jxfe** [comment]
Its not allowed or else they will get removed off app store read up dm me for the source discord.
