### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LankySmurph** [Paperback-iOS/app#583]
**Describe the bug**
When opening and backing out of a title, the badge on the title will increment by one every time. Even if nothing has changed other than opening and closing a title.

**To Reproduce**
Open a title, back out of the title. Repeat.

**Expected behaviour**
Nothing, other than opening and closing the title.

**App Version**
v0.7-r38

**Video**

https://user-images.githubusercontent.com/27979868/168093566-9b1202ff-065c-4f48-9ea2-382b47c54717.MP4

**Comment by FaizanDurrani** [comment]
This should be fixed in r40.
