### ISSUE TITLE
[BUG] Upgrading beyond Build 35 causes 403 when reading

### ISSUE THREAD

**Issue by ssalihsrz** [Paperback-iOS/app#587]
**Describe the bug**
After receving an update notification on test flight update to any build past 35. Reader displays a blank page, when enabling error pop up we see a 403 message on almost any webtoon/manga

**To Reproduce**
Steps to reproduce the behaviour
Update from Build 35 on test flight to any newer version.
Rolling back to Build 35 and I can read again.

**Expected behaviour**
After update, continue to be able to read any chapter like previous upgrades

**App Version**
Eg: v0.2-wip.3.1
v.07(36,38,40)

**Screenshots**

**Comment by TheNetsky** [comment]
Not an app issue, source issue.
Please close this.

**Comment by ssalihsrz** [comment]
Is there any resolution to this? I can close it no problem.
