### ISSUE TITLE
[REQUEST] Headers Option for thumbnails

### ISSUE THREAD

**Issue by xOnlyFadi** [Paperback-iOS/app#590]
**Description**
this feature would add an option for some sites that use a different image site that needs some specific headers to make the thumbnails appear again in the app with no problems.

**How would it improve the App?**
It would improve the app by making the thumbnails appear again in the app and would not show a blank image

**Comment by FaizanDurrani** [comment]
Use interceptors.

**Comment by xOnlyFadi** [comment]
> Use interceptors.

mine already have interceptors and would still blank images get

**Comment by FaizanDurrani** [comment]
Make sure you're setting the header value again instead of modifying it.
```js
request.headers = {
  ...(request.headers ?? {}),
  newHeaders: 'here'
}
```

**Comment by xOnlyFadi** [comment]
> Make sure you're setting the header value again instead of modifying it.
> 
> ```js
> request.headers = {
>   ...(request.headers ?? {}),
>   newHeaders: 'here'
> }
> ```

mine looks like this 
```ts
    requestManager = createRequestManager({
        requestsPerSecond: 3,
        requestTimeout: 15000,
        interceptor: {
            interceptRequest: async (request: Request): Promise<Request> => {

                request.headers = {
                    ...(request.headers ?? {}),
                    ...{
                        ...(this.userAgent && { 'user-agent': this.userAgent }),
                        'referer': `${this.baseUrl}/`
                    }
                }

                return request
            },

            interceptResponse: async (response: Response): Promise<Response> => {
                return response
            }
        }
    });
```

**Comment by FaizanDurrani** [comment]
It should be

```ts
    requestManager = createRequestManager({
        requestsPerSecond: 3,
        requestTimeout: 15000,
        interceptor: {
            interceptRequest: async (request: Request): Promise<Request> => {
                request.headers = {
                    ...(request.headers ?? {}),
                    'referer': `${this.baseUrl}/`,
                    'user-agent': this.userAgent ?? request.headers?.['user-agent']
                }

                return request
            },

            interceptResponse: async (response: Response): Promise<Response> => {
                return response
            }
        }
    });```

**Comment by xOnlyFadi** [comment]
> It should be
> 
> ```ts
>     requestManager = createRequestManager({
>         requestsPerSecond: 3,
>         requestTimeout: 15000,
>         interceptor: {
>             interceptRequest: async (request: Request): Promise<Request> => {
>                 request.headers = {
>                     ...(request.headers ?? {}),
>                     'referer': `${this.baseUrl}/`,
>                     'user-agent': this.userAgent ?? request.headers?.['user-agent']
>                 }
> 
>                 return request
>             },
> 
>             interceptResponse: async (response: Response): Promise<Response> => {
>                 return response
>             }
>         }
>     });
> ```

it worked thank you.
