### ISSUE TITLE
[REQUEST] Body option on createRequestObject

### ISSUE THREAD

**Issue by xOnlyFadi** [Paperback-iOS/app#598]
**Description**
the body option is an request feature on some sites api that use a custom body to request the needed info inside to get for the things to work.

**How would it improve the App?**
it would improve the app by helping developers to get info from sites that use a custom method to get info from them like graphql etc.

**Comment by FaizanDurrani** [comment]
This is already supported, look at the Anilist tracker, it uses their GraphQL API

**Comment by FaizanDurrani** [comment]
https://github.com/Paperback-iOS/trackers-main/blob/main/src/Anilist/Anilist.ts

**Comment by xOnlyFadi** [comment]
do I need to update `paperback-extensions-common` to the alpha?

**Comment by FaizanDurrani** [comment]
No but do that anyways, its basically ready to go stable at this point anyway.

Use the `data` field in the `createRequestObject` method to pass in data. If you pass in an object, the app will serialise it according to the `content-type` set in the header.

If you pass in a string, it will just use it as-is without changing it.

**Comment by FaizanDurrani** [comment]
Don't forget to update the cli to the alpha aswell

**Comment by xOnlyFadi** [comment]
thanks for the help it worked.
