### ISSUE TITLE
[REQUEST] Customize ui

### ISSUE THREAD

**Issue by acknologia** [Paperback-iOS/app#60]
**Description**
Allowing us to change what ui elements we have on series pictures.
right now on the recent list we have 5 elements (picture / name / chapter # / language / time)
if we can select in the settings which elements we want that would be nice.

Another option can be to move all the other elements to immediately below the picture
(i will add a terrible reproduction of what i mean vs what we already have)

Also having options for which tabs we want. For example i think having its own tab for recents would be super useful for me since thats where i would spend most of my time but downloads wont be as useful for me because i dont download.

**How would it improve the App?**
A lot of the series picture is  is already covered by the title and these other things. By letting the users select what they think is important, more or less of the series picture will be visible when scrolling.

**Additional context**
![image](https://user-images.githubusercontent.com/64101826/79906646-2f72f080-83e6-11ea-9854-28c84edc392a.png)
![template](https://user-images.githubusercontent.com/64101826/79907637-ede34500-83e7-11ea-9080-f3bdcdae11e9.png)

**Comment by acknologia** [comment]
Also a recently views tab would be nice

**Comment by FaizanDurrani** [comment]
History is implemented, layout for manga tiles changed
