### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EgOCrispy** [Paperback-iOS/app#607]
Hey so I downloaded paperback on my m1 mac off the app store but every time i click off a series and try to click back on it the app crashes. I tried multiple sources and re downloading  it but the same problem persists.

https://user-images.githubusercontent.com/104405653/172490794-395c6074-581a-4477-ac96-cddf35b05fae.MOV

https://user-images.githubusercontent.com/104405653/172490904-d2016c30-d5f7-4ae4-99a0-29f50057a6a7.MOV

**Comment by FaizanDurrani** [comment]
Try turning off the legacy reader and view

**Comment by EgOCrispy** [comment]
> Try turning off the legacy reader and view

That fixed it, thank you so much!
