### ISSUE TITLE
[BUG] iPadOS 16 Dev Beta causes issues with connection Swift.String Error

### ISSUE THREAD

**Issue by r3dlobst3r** [Paperback-iOS/app#608]
**Describe the bug**
After upgrade to the Dev beta of iPadOS 16, the app has a swift error connecting to my Komga server.

**To Reproduce**
Install iOS/iPadOS 16

**App Version**
New Appstore version (congrats by the way!)

**Screenshots**
![IMG_0001](https://user-images.githubusercontent.com/33791877/172511629-f4dded26-5a1d-4b98-b754-1f85d1136bbd.png)

**Comment by xOnlyFadi** [comment]
You have not provided any useful information.

Missing:
App version
Source version

**Comment by FaizanDurrani** [comment]
Paperback does not support dev versions of iOS. Either go back to iOS 15 or wait for iOS 16 to become stable.

**Comment by r3dlobst3r** [comment]
Yeah I figured, still thought it fit as a bug report for an upcoming os that maybe you would want to know about.
