### ISSUE TITLE
[REQUEST] resume reading

### ISSUE THREAD

**Issue by slzxluv** [Paperback-iOS/app#61]
**Description**
For users to resume reading from the last chapter read.

**How would it improve the App?**
more convenient for readers that wish to stop reading and planned to continue reading again after some days or months without trying to remember which chapter number they had stopped previously.

**Additional context**

**Comment by ConradWeiser** [comment]
Can be marked as completed

**Comment by FaizanDurrani** [comment]
Added in v0.3.0-b7
