### ISSUE TITLE
[Filter] [New feature] Possibility to add more filters or to group them

### ISSUE THREAD

**Issue by Bencyril** [Paperback-iOS/app#610]
Hi guys!

After using the app, that is really nice, I think it's missing one thing:

Grouping multiple Filters in one search
Currently, the only possible way to filter is only by Genre (Action, Adventure, Shōnen, others)
And you have to check each repo to find the status like running, completed or other

Would be nice to have in the search the possibility to filter by Genre AND by Status

Thanks !

**Comment by TheNetsky** [comment]
This is source dependant, not all sources support this or have this implemented.
