### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by EgOCrispy** [Paperback-iOS/app#612]
**Description**
Hey so I just wanted to suggest being able to view anilist within the app itself.

**How would it improve the App?**
I feel like it would improve the app because it’ll make it easier to check your progress  especially if you’re switching devices constantly. 
**Additional context**

Syncernazation between devices would be helpful as well but viewing anilist should be good enough since it already auto tracks.

**Comment by FaizanDurrani** [comment]
Not entirely sure what you mean by that.
You can view an already tracked entry's progress by tapping the track button then pressing "back", then going into "Manage".

**Comment by EgOCrispy** [comment]
> Not entirely sure what you mean by that.
> 
> You can view an already tracked entry's progress by tapping the track button then pressing "back", then going into "Manage".

oh okay yeah that works thanks. Didn't know how to get back on the manage page.
