### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by S3813354** [Paperback-iOS/app#617]
**Describe the bug**
Downloads stop on ipad when the screen is off

**To Reproduce**

Have the background app refresh on for paper back app store version.

Add a manga to library, select all chapters and download all chapters. Turn the screen off. Come back in a while the downloads will have stopped and not progressed at all from the last screen on time

**Expected behaviour**
Once the screen is off, it keeps on downloading in the background, nd it finishes download while the screen is off.

**App Version**
Eg: v0.2-wip.3.1

**Screenshots**

**Comment by XenitXTD** [comment]
This has been raised and background downloads is not possible and past tricks to achieve this have removed the apps from the store

I have requested that at the least the minute the app is open or you are busy in it it immediately resumes and or allows for auto downloading latest chapters on select manga
