### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AdmnJ** [Paperback-iOS/app#619]
**Describe the bug**
Bottom and top bar never go away when reading.

**To Reproduce**
-Current version of the app and iPadOS
-start reading any manga
-bottom and top navigation never goes away. Causing bars to cover a large enough portion of the top and bottom that if I am reading in horizontal mode instead of vertical I have to zoom in to see some text on the bottom.

**Expected behaviour**
Either the ui quickly disappears as you start reading or you get a translucent button to toggle it on and off.

**App Version**
V0.7-r46

**Screenshots**
![image](https://user-images.githubusercontent.com/43836753/174464504-3c41ad89-9f2d-4715-8453-c9948f7dfdab.jpeg)

**Comment by AdmnJ** [comment]
Update, I disabled tap navigation and was able to get the bars to hide.

**Comment by TheNetsky** [comment]
You just have to tap the center of the screen, not a bug, close this.
