### ISSUE TITLE
[BUG] After the latest beta update most sources don't work

### ISSUE THREAD

**Issue by omi-kun** [Paperback-iOS/app#620]
After the beta update all chapters of MangaNelo dont reload AT ALL titles and search of source are all good but when i try to read the chapter nothing appears

App Version (v0.7-r45)

![image](https://user-images.githubusercontent.com/69520027/174856428-dbbf53a1-b7be-457a-8ab2-5295eb907c24.png)![image](https://user-images.githubusercontent.com/69520027/174856443-5cbbbd7b-6909-4f43-bee8-0014c4e1ddbe.png)

**Comment by TheNetsky** [comment]
Your sources are outdated, not an app issue. Close this.

**Comment by TheNetsky** [comment]
You must look for that yourself, google.
