### ISSUE TITLE
Tonnliy is not showing [BUG]

### ISSUE THREAD

**Issue by Uhero121** [Paperback-iOS/app#621]
**Screenshots**
I have attached screenshot showing on what is a problem 
![help 1](https://user-images.githubusercontent.com/108062215/175278764-3a6c256c-ddd2-4c63-ac3b-97d9755644e0.png)
![help 2](https://user-images.githubusercontent.com/108062215/175278771-93e93870-25e4-4768-aa3d-5f726eadc3a9.png)

**Describe the bug**
Every time I bring up Tonnliy on the app it brings up an error message saying go to my setting and showing any pages. If anyone help that be great

**Expected behaviour**
it should be to show each of manwah without any issue

**App Version**
Not sure version

**Comment by TheNetsky** [comment]
The error message literally says what to do; Do the Cloudflare bypass.

Close this issue.
