### ISSUE TITLE
[BUG] Not showing updates

### ISSUE THREAD

**Issue by rishabh139** [Paperback-iOS/app#626]
**Describe the bug**
Mangas not showing updates till each one is individually opened

**To Reproduce**
Hit or miss behaviour but many mangas don't show any updates until they are individually opened.

**Expected behaviour**
When I refresh the folder, I expect all the updates to automatically show up instead of me having to manually sift through all the mangas.

**App Version**
Eg: v0.7

**Comment by TheNetsky** [comment]
Duplicated of https://github.com/Paperback-iOS/app/issues/560
