### ISSUE TITLE
[BUG] anilist tracking error

### ISSUE THREAD

**Issue by Samk19** [Paperback-iOS/app#627]
**Describe the bug**
unable to login on anilist

**To Reproduce**
enable tracking repository main 
Install Anilist 
Login with anilist credentials 
Verify not a robot
Login button press
Error

**Expected behaviour**
Successful login should have happened 
But instead have error and login is unsuccessful 

**App Version**
v0.7-r46

**Anilist extension version**
v1.0.10

**Screenshots**
![DBE60FD9-F82F-4F80-A033-3FFD68B3D731](https://user-images.githubusercontent.com/36104528/176312246-66146917-1566-4da9-86e3-6488447f4993.png)

**Comment by FaizanDurrani** [comment]
You’re likely running iOS 16, we don’t support iOS betas.

**Comment by Samk19** [comment]
I am currently running ios 15.5
