### ISSUE TITLE
[REQUEST] Remember tab state when switching between tabs

### ISSUE THREAD

**Issue by mara42** [Paperback-iOS/app#63]
**Description**
When doing something in one tab, changing to another tab and the comming back, it would be ideal if the previous state (e.g. page, selection, scroll position) of that tab would be shown. 

Current behaviour remembers a previously selected manga but not scroll position and reloads thumbnails between tab switches. 

Example of expected behaviour: open lates updates on the discover tab and scroll down for a bit, go to settings tab, go back and see the same scroll position. 

**How would it improve the App?**
- Faster and more responsive feeling
- Changing tabs feels less annnoying
- Users are used to this behaviour in other apps

**Additional context**
\-

**Comment by FaizanDurrani** [comment]
This is a limitation of SwiftUI, nothing I can do.

I'll keep the issue open incase Apple decides to improve TabView

**Comment by mara42** [comment]
Looking up some discussion on the topic, it does seem that the use of UIKit directly is necessary at the moment to workaround the issue ☹️

**Comment by FaizanDurrani** [comment]
Closing this for now since there's no way to achieve this atm
