### ISSUE TITLE
[BUG] "Chapter" / Volume list formatting

### ISSUE THREAD

**Issue by CirqueDuMal** [Paperback-iOS/app#643]
**Summary**
Running Komga server with plugin

In Paperback:
Discover Menu...
Recently added series... 
Click on a series... On the right hand side...

Ch. 1-1 - Aho-Girl v01 (163.6 MiB)
_UNKNOWN 
Ch. 2-2 - Aho-Girl v02 (155.6 MiB)
_UNKNOWN 
etc etc

Found that if I edit some settings in Komga:
First Line = Title (I set this, works fine)
Second Line = Language (I set to English)

Ch. 1-1 - A Clueless Girl (163.6 MiB)
GB
Ch. 2-2 - I'm with Stupid (155.6 MiB)
GB
etc etc

**Questions / Issues**
- Ch. 1-1  
Can't find a way to change this, doesn't apply. 
"Ch. 1" would be fine... but the "1 - 1" to "2 - 2" is excessive, is there any way to control this?

- MiB 
Are we really measuring in MebiBytes?  
Megabytes a far more accessible.. 
But why is this so important that it's on the main line?

- GB
Is this trying to show Great Brittan maybe?  
If it were an flag, I'd get it, but right now, it's just GB...
So now we have 163.6 MiB GB... yey?

**Expected behaviour**
Need control over this, or documentation exposed to the user to understand what changes are needed

**App Version**
iPad Air (4th Gen)
iPadOS 15.3.1 
app store version

**Comment by FaizanDurrani** [comment]
> **Questions / Issues**
> 
>     * Ch. 1-1
>       Can't find a way to change this, doesn't apply.
>       "Ch. 1" would be fine... but the "1 - 1" to "2 - 2" is excessive, is there any way to control this?
Fixed.

>     * MiB
>       Are we really measuring in MebiBytes?
>       Megabytes a far more accessible..
>       But why is this so important that it's on the main line?
This is how Komga returns the size (ref: https://api.paperback.moe/api/v1/series/08N7JCY8RDRPK/books)

>     * GB
>       Is this trying to show Great Brittan maybe?
>       If it were an flag, I'd get it, but right now, it's just GB...
>       So now we have 163.6 MiB GB... yey?
GB is meant to be "English"; this is more of a relic from the earlier versions of Paperback when it showed a flag. The English flag had the id of "GB" since 0.7 Paperback has switched from using a set of defined flags to allowing any string in the language field (to support more languages)

**Comment by CirqueDuMal** [comment]
@FaizanDurrani Thank you for the very fast response!  I'll look forward to seeing the changes in the future update!

I'll go see if I can pester Komga about their silly file sizes.

Keep up the great work!  I'm very pleased with the app so far!
