### ISSUE TITLE
[BUG] Series not being marked as having a new chapter in Collections

### ISSUE THREAD

**Issue by chronooo** [Paperback-iOS/app#649]
**Describe the bug**
Normally when a series has a new chapter, the top-right corner of the series will be marked with the number of new, unread chapters available to read. For A few weeks this has not been available. If you click a series, it will load that there are new chapters, but the red-marker displaying that there are new unread chapters will not show.

**To Reproduce**
Steps to reproduce the behaviour
1. Add a series to the library/collections
2. Wait for a new chapter to be released
3. Refresh and see that new chapter is not being marked on series.

**Expected behaviour**
When I refresh my library/collection, the series that had a new chapter would appear at the top, with the number of new, unread, chapters that they have stored up.

**App Version**
v0.7-r46

**Screenshots**

**Comment by Seyden** [comment]
Can confirm, also the title won’t be pushed to the top anymore when it has new chapters, it will stay at the same position. Also if you read the newest chapter, the title won’t be pushed back to the front (how it was usually done).

This is quite annoying

**Comment by seannn9** [comment]
Same issue here. Been checking for new chapters manually which is a hassle if you have a ton of manga in your library.

**Comment by BLB3AUTY** [comment]
Confirm on same issue.  
New chapters are not being marked in library.

**Comment by TheNetsky** [comment]
Source issue.
