### ISSUE TITLE
[REQUEST] Backup to include tracking

### ISSUE THREAD

**Issue by Samk19** [Paperback-iOS/app#650]
**Description**
Enable tracking when restoring title through backup file

**How would it improve the App?**
How would the feature improve the app?
It will improve the backup n restore process.
It is a hassle to re-enable tracking if we have many titles.

**Additional context**
N/A

**Comment by FaizanDurrani** [comment]
duplicate of #469

**Comment by TheNetsky** [comment]
Dupe of https://github.com/Paperback-iOS/app/issues/469
