### ISSUE TITLE
[BUG] [[PAPER BACK ERROR: 400]] & [[300]]

### ISSUE THREAD

**Issue by Xxcean** [Paperback-iOS/app#660]
**Describe the bug** 
The error(s) appears periodically after using the search feature or scrolling through manga. I haven’t detected a consistent in-app issue other than the pop-ups.

**To Reproduce**
Simply using the app, or scrolling through a saved manga/webtoon, it may pop-up in droves.

**Expected behaviour**
no errors

**App Version**
(Testflight) Version 0.7 -r(47)

**Screenshots**
![B713E15B-6777-4D0E-A20F-E7016796ED8E](https://user-images.githubusercontent.com/112822264/188327161-2fd82191-eeee-4a59-80ca-eebe33d52656.jpeg)

![1EAA1020-CB8B-4B11-B5EC-D3413C62DFAA](https://user-images.githubusercontent.com/112822264/188327168-c03bdce8-a2d5-4edf-91dc-a9ef6c2c1b8d.jpeg)

**Comment by rintendou** [comment]
Do you have Async turned on? Can be found in experimental settings

**Comment by Xxcean** [comment]
> Do you have Async turned on? Can be found in experimental settings

Hey! Just tried it out, Error 300 is still appearing, I assume it may just have to be fixed in another patch?

**Comment by TheNetsky** [comment]
1. is a timeout
2. is a source issue, not support shall be given by Paperback for that.
