### ISSUE TITLE
[BUG] pls update new domain

### ISSUE THREAD

**Issue by tktmgn20** [Paperback-iOS/app#666]
**Describe the bug**
Source is not update new domain ( HentaiVN 2.8.1 - Huynhzip3 )

**To Reproduce**
pls update new domain ( hentaivn.la )

**Expected behaviour**
pls update new domain ( hentaivn.la )

**App Version**
Eg: v0.6.2-r.1.0.0

**Comment by TheNetsky** [comment]
We do not provide support for third party source, go to the developer's Discord/Github page and open the an issue there.
