### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by serideri** [Paperback-iOS/app#672]
**Describe the bug**
Mangas don't show thumbnails in Library only.
Replacing the mangas by merging or reloading the thumbnails only helps for a short while before it reverts back to having no thumbnails.

**To Reproduce**
1. Add a Manga to Library/Collections
2. Open said Collection
3.  No Thumbnails to be seen 

**Expected behaviour**
Thumbnails should appear.

**App Version**
Eg: v0.7-r46

**Screenshots**
/

**Comment by TheNetsky** [comment]
This is a source issue. We don't provide support for third-party sources.
