### ISSUE TITLE
[BUG] App does not properly handle image requests

### ISSUE THREAD

**Issue by Ivanmatthew** [Paperback-iOS/app#687]
**Describe the bug**
When paperback requests the data on an image weblink, paperback doesn’t account for websites who check on specific headers if they request the image itself or not. It results in the website hosting that image to potentially return an html file with the requested image inside of it. (I think it’s something to do with routing?). It results in paperback app unable to show the images to the end user as it expected image data instead of html data.

**To Reproduce**
Read any image that has this sort of routing. For example, use a wordpress hosted image.
Visit that image on your pc and you’ll understand the bug description.
For a third-party-specific reproduction:
- Open Paperback App
- Add source https://github.com/TheNetsky/extensions-generic/tree/madara (Manhuaus)
- Search for “rich player”
- Select chapter 8

**Expected behaviour**
It should show the image, instead of an error message.

**App Version**
v0.7-r46

**Screenshots**
https://media.discordapp.net/attachments/967885879324598362/1023727739540361236/2022-09-25_16-48-06.mp4

**Solution**
Add header:
“Content-Type”: “image/*”
or
“Content-Type”: “image/jpeg”

**Comment by TheNetsky** [comment]
Source issue.

**Comment by Ivanmatthew** [comment]
My bad, my mind is scrambled. Issue needs to be moved to https://github.com/TheNetsky/extensions-generic/tree/madara
