### ISSUE TITLE
[REQUEST] Open manga in browser

### ISSUE THREAD

**Issue by SirNoodly** [Paperback-iOS/app#69]
**Description**
A button/share feature that allows user to open the currently viewed manga’s Mangadex page in a browser (either share to browser, or in-app browser). 

**How would it improve the App?**
Allows further integration with Mangadex, and gives people a way to quickly view information that may currently be unavailable in the app.

**Comment by ConradWeiser** [comment]
Can be marked as completed

**Comment by FaizanDurrani** [comment]
Added in v0.3.0-b7
