### ISSUE TITLE
No new updates unless interacting with individual books

### ISSUE THREAD

**Issue by YodaGaming** [Paperback-iOS/app#695]
no push notifications either

**Comment by hoover900** [comment]
this is happening for me as well regardless of source

**Comment by TheNetsky** [comment]
Source issue.

**Comment by YodaGaming** [comment]
after looking further into this, I figured out its not actually a "source issue" (as its happening with EVERY source). if you disable "update all titles" you should get a far better result pulling updates.

**Comment by TheNetsky** [comment]
If issue still persists, open a proper bug report.

**Comment by FaizanDurrani** [comment]
> after looking further into this, I figured out its not actually a "source issue" (as its happening with EVERY source). if you disable "update all titles" you should get a far better result pulling updates.

Hmm, that setting just forces the app to fetch chapters for every title in your library. If anything, leaving it on should improve updates at the expense of taking more time (since it checks EVERY title in your library). Regardless, updates are fixed in 0.8 so this is already addressed.

**Comment by inexald** [comment]
So this bug will not be fixed and 0.8 has no eta… great so we have a half broken app and no one will fix it… great support

**Comment by TheNetsky** [comment]
This WILL be fixed or at least afaik should be.

**Comment by TheNetsky** [comment]
> So this bug will not be fixed and 0.8 has no eta… great so we have a half broken app and no one will fix it… great support

There's one dev, who has other things besides this, be patient.

If you really cannot wait and need update notifications RIGHT NOW then you can join the Patreon. Besides that yeah, nothing u can do besides clicking on the items you want to read.

**Comment by inexald** [comment]
This bug is around for more than three months, and this here is the first time that some is addressing it. I asked on both discord for help and was always send away with other kind words. I AM still patient, but it’s kinda frustrating if you have this problem that long and you get no help.
and yeah I am a patriot for about two years now, but I don’t pay 10 bucks per month for a app that is in early alpha and will maybe work.

**Comment by TheNetsky** [comment]
That's because there has been no update since, 0.8 has been a major rewrite of the app. This is a known issue since long before, but also due to the nature of iOS and it's restrictions push notifications will alway be an issue.

**Comment by inexald** [comment]
It has nothing to do with push notifications, i don’t care about that. The app itself does not properly search for new chapters as long as you don’t look in every single manga yourself.

**Comment by TheNetsky** [comment]
Anyways, it's being worked on.

**Comment by baraa272** [comment]
> after looking further into this, I figured out its not actually a "source issue" (as its happening with EVERY source). if you disable "update all titles" you should get a far better result pulling updates.

where is that option  ?

**Comment by baraa272** [comment]
i still face this bug

**Comment by Celarye** [comment]
This is fixed in 0.8.

**Comment by baraa272** [comment]
> This is fixed in 0.8.

sure how can someone actually get it ?

**Comment by Celarye** [comment]
You can get the 0.8 beta by becoming a patron.
