### ISSUE TITLE
[BUG]Mangaforest is not working

### ISSUE THREAD

**Issue by Escabt** [Paperback-iOS/app#696]
None of the mangas work from this source from some reason it just shows up as blank.

Eg: v0.7-r46
![CCDD407A-35A0-4F58-B2DE-1589B0111FEF](https://user-images.githubusercontent.com/122589319/212240837-25ced74e-ad07-4d91-8484-c08fc8ace83e.jpeg)

**Comment by Celarye** [comment]
This is a source issue and Paperback is not responsible or related to third party sources in any way. Instead try contacting the source developer.

Please close this issue.
