### ISSUE TITLE
Manga not loading

### ISSUE THREAD

**Issue by rohawn** [Paperback-iOS/app#704]
![IMG_8543](https://user-images.githubusercontent.com/71676226/217729669-89207731-9ed2-4fb4-a777-f36584eb533f.PNG)

Just getting a blank screen like this loading infinitely. Deleted and reinstalled the app and having the same issue. Let me know if any fix.

**Comment by Celarye** [comment]
This seems like a source issue. We can’t help you with that so instead contact the source dev.

**Comment by TheNetsky** [comment]
Seems like a source issue, if you have problems with the app, follow the bug report format.
