### ISSUE TITLE
[BUG]low quality 

### ISSUE THREAD

**Issue by Redrowdyrocket** [Paperback-iOS/app#705]
When i change settings to vertical read mode the quality down soo bad
![D66A63AE-7FCA-4B93-8857-DCC46C75AD1C](https://user-images.githubusercontent.com/125145562/218269805-315bd160-4e62-48cd-b4b7-3fb6e8281f03.png)

**Comment by TheNetsky** [comment]
Please follow the bug format and supply more information.
