### ISSUE TITLE
[BUG] Comick API + ID changes.

### ISSUE THREAD

**Issue by meotimdihia** [Paperback-iOS/app#714]
### Source new URL

https://api.comick.fun/

### Other details

`https://api.comick.fun/comic/{id}/chapter`(deprecated) will change to `https://api.comick.fun/comic/{hid}/chapters`

And please map `slug` to `hid` as Comic ID. Because sometimes, we'll change the slug and the user list will miss the comic that has the slug that was changed.

For example: [https://api.comick.fun/tachiyomi/mapping?slugs=naruto&slugs=one-piece](https://api.comick.fun/tachiyomi/mapping?slugs=naruto&slugs=one-piece)

**Comment by TheNetsky** [comment]
Seems like a source issue, Paperback is not related with third party sources.
