### ISSUE TITLE
[REQUEST] A tab for recently updated manga

### ISSUE THREAD

**Issue by cocofire** [Paperback-iOS/app#72]
A tab at the top that says how many updated mangas and when you press it, it shows the recently updated manga and when you read the chapter, it goes away from the tab. Just like in Manga Rock.

**Comment by ConradWeiser** [comment]
Sorting by recently updated manga has been added to the library. I don't believe there are plans for there to be a tab to display such, however the functionality can be easily completed in the library view.
The sort method in question will bring all of the recently updated titles right to the top of the app.
