### ISSUE TITLE
[BUG] CONTENT SETTINGS CANT BE CHANGED

### ISSUE THREAD

**Issue by sdpaci** [Paperback-iOS/app#723]
I follow all the troubleshooting steps and still can't change the content settings which makes the app basically unusable.  It keeps saying server communication error or verify email but I never get an email in my inbox or spam or promotions etc... What should I do?
I have been struggling with this for months. I gave up and came back to try again because I thought this might be a nice app to use but this simple things seems more frustration than it is worth. Hopefully there is some solution to be found here. Seems like you should just be able to adjust the content settings in the app and not the silly portal which seems to be causing so many issues. Should I delete everything and start over?

**Comment by Celarye** [comment]
The need for the not in app portal is because of Apple restrictions afaik. And maybe try using a different email?

**Comment by sdpaci** [comment]
Seems to have worked w/diff email. Owe you one, m8!
