### ISSUE TITLE
sources not showing details

### ISSUE THREAD

**Issue by yuhly** [Paperback-iOS/app#734]
i just added 3 sources from netsky and they dont show mangas, its just a blank white slate. is this a bug?

![5471AD85-F59F-498F-A380-54042DDA3E20](https://user-images.githubusercontent.com/91270641/230695605-2b46344e-8838-4bfa-8f16-b7f3daf8a1e9.png)

**Comment by TheNetsky** [comment]
Please provide more information as per bug report template, can't do much here.

**Comment by yuhly** [comment]
> Please provide more information as per bug report template, can't do much here.

I randomly added one source and it says undefined. turns out, every source that I add is like this.

![Uploading 078A6998-61EF-4AC4-80A7-449F2622D954.png…]()

**Comment by TheNetsky** [comment]
Once again, follow the bug template, still not very useful. But I guess it's marker completed now.
