### ISSUE TITLE
[BUG] Installing repository 0.8 gives a JAVASCRIPT EXCEPTION error

### ISSUE THREAD

**Issue by Techwiz34** [Paperback-iOS/app#738]
I just set up the paperback app on iOS 15 minutes ago, and I was attempting to add the repositories for Mangakakalot and Manganato. When an attempt to install or refresh the repositories is made, it gives me this error:

 [JAVASCRIPT EXCEPTION] (TypeError: undefined is not an object) Method: undefined:undefined:undefined

I am using iOS version 16.4.1 on my iPhone XS, and attached is a screenshot with the error in question.
![IMG_0003 1](https://user-images.githubusercontent.com/37275502/231046974-32e53085-24c5-4afa-b5ea-3c129c0430ab.PNG)

**Comment by Techwiz34** [comment]
found the answer in another issue post

**Comment by Techwiz34** [comment]
oops

**Comment by Celarye** [comment]
@Techwiz34 Please refrain from mentioning third party sources or issues with them on the official GitHub page in the future. Paperback does not give support regarding third party sources. Instead contact the third party source developer in the place you got it from.

**Comment by loraesv** [comment]
> I just set up the paperback app on iOS 15 minutes ago, and I was attempting to add the repositories for Mangakakalot and Manganato. When an attempt to install or refresh the repositories is made, it gives me this error:
> 
> [JAVASCRIPT EXCEPTION] (TypeError: undefined is not an object) Method: undefined:undefined:undefined
> 
> I am using iOS version 16.4.1 on my iPhone XS, and attached is a screenshot with the error in question. ![IMG_0003 1](https://user-images.githubusercontent.com/37275502/231046974-32e53085-24c5-4afa-b5ea-3c129c0430ab.PNG)

i have the same problem, please help me

**Comment by TheNetsky** [comment]
You're installing 0.8 sources on the 0.7 app...
Also no source support here.
