### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RandomSteve42** [Paperback-iOS/app#741]
When I go to install my external sources it says 
[JAVASCRIPT
EXCEPTION] Optional (TypeError:
undefined is not an object) Method: undefined:undefined:undefined
It then pops up refresh but it just does the same thing again and I have no way to use my sources.

**Comment by Celarye** [comment]
You installed a source which is meant for the 0.8 version of the app on your 0.7 app.

**Comment by RandomSteve42** [comment]
Is there a way for me to update my app or do I just need to install a 0.7 version and thank you very much

**Comment by Celarye** [comment]
The 0.8 app is currently in beta, to get access to this you need to become a patron.
