### ISSUE TITLE
[REQUEST] Vertical padding option for longstrip reading.

### ISSUE THREAD

**Issue by ImOldGregg** [Paperback-iOS/app#76]
**Description**
When you are reading in longstrip. Have the ability to enable vertical padding on the left and right side of the screen. Or another option is to enable a custom zoom and have it lock for all pages or chapters.

**How would it improve the App?**
When reading webtoons in landscape mode this will allow for better reading allowing more of the content to be displayed.

**Additional context**

Before:
![701F15BC-4032-4FDD-B2C6-A39272E8DEB9](https://user-images.githubusercontent.com/64284396/80255714-1ca92780-8643-11ea-8dc1-a10114805d73.png)

After:
![9CB13623-01B5-46DA-B47A-169C90C1CED2](https://user-images.githubusercontent.com/64284396/80255747-30548e00-8643-11ea-97f6-6608a19e53fd.png)

**Comment by blipnomi** [comment]
zooming on longstrip would be nice but definitely don’t want to be forced into being zoomed out

**Comment by ImOldGregg** [comment]
You wouldn’t be forced to. It could just be an option to tick on or off. Or like I said before maybe a custom zoom out option that you can lock in place for all pages or chapters until you want to turn it off.

**Comment by blipnomi** [comment]
oh yeah sorry, misread your ticket

**Comment by ImOldGregg** [comment]
It’s mainly for people with the larger iPads. Longstrip in landscape mode on an iPad Pro is kind of in your face and I find myself wanting to zoom out every page to read it easier which gets annoying.

**Comment by blipnomi** [comment]
yeah that’s fair

**Comment by ImOldGregg** [comment]
Oh man i completely understand. Not many people have this problem I don't think. I like to read at my desk during the down time and using the smart folio keyboard pretty much everything is in landscape. I’ve only found one app that has this feature so far and thats manga dogs. Only thing is the quality of the content looks compressed and blocky. I have no clue what they are doing to some of the reads. I know I’m being picky but I’m hoping this app will be the one to rule them all lol

**Comment by ImOldGregg** [comment]
Just keeping this one alive since I've seen similar requests. Pay no attention.

**Comment by FaizanDurrani** [comment]
Added in the latest alpha 0.4.0 (2.0.7-Alpha)
