### ISSUE TITLE
[REQUEST] padding below description header

### ISSUE THREAD

**Issue by blipnomi** [Paperback-iOS/app#77]
**Description**
add padding-bottom: 15px; (where red line is in the attached image) or whatever it is in SwiftUI to the description. wouldn’t be opposed if the author information and description font were a bit smaller either. maybe it could match system font size?

**How would it improve the App?**
it looks cramped

**Additional context**
![image](https://user-images.githubusercontent.com/64299326/80272334-50616d00-8696-11ea-9dda-f9c0b27e23a6.jpeg)

**Comment by FaizanDurrani** [comment]
Fixed in b7
