### ISSUE TITLE
[REQUEST] Cancel queued downloads in the Download Manager

### ISSUE THREAD

**Issue by yetiam-on-git** [Paperback-iOS/app#772]
**Description**
Cancel queued downloads in the Download Manager

**How would it improve the App?**
Prioritize certain downloads, adjust to slow internet, and clear relevant bugs (see context). Makes the Download Manager an actual manager rather than just a display

**Additional context**
ex. I queued a bugged title's chapters and removed the title from my library without canceling the download, so I can no longer purge the nonexistent chapters from the queue without removing the entire source

**Comment by FaizanDurrani** [comment]
As of 0.8.6-r2, this should be possible with the Download Queue (accessible from the Library)
