### ISSUE TITLE
[REQUEST] Background Manga DLing with Temp Files

### ISSUE THREAD

**Issue by milkyautism** [Paperback-iOS/app#786]
**Description**
Downloading manga in the background (+ temp file support) / Not stopping download when the app is not open or isnt connected to WiFi

**How would it improve the App?**
It could save me and many users the headache of having to watch over their downloads when they need to do something else

**Additional context**
As of iPadOS 17, i still need to leave my iPad open just for it to download chapters. Locking? Stop downloads, Close app? Stop downloads, Wifi disconnect for one second? Congrats, you lose progress!...

I hope this feature gets added in the future.

**Comment by TheNetsky** [comment]
iOS does not allow the start of new download within the background, so this is not possible. 
See https://github.com/Paperback-iOS/app/issues/435
