### ISSUE TITLE
[BUG] App crash with consecutive downloaded chapters browsing/navigating

### ISSUE THREAD

**Issue by Ivanmatthew** [Paperback-iOS/app#789]
**Describe the bug**
When reading or skipping chapters, the app crashes

**To Reproduce**
1) Download ~5 chapters of the same manga
2) Open the first chapter
3) Press the next chapter button a few times
4) Scroll down a bit, you’ll see the last chapter’s image phasing into the current chapter’s image. At this point it crashes.

**Expected behaviour**
The next chapter to have properly loaded and the previous chapter to have properly be unloaded

**App Version**
v0.8.3-r2

P.S.
This might happen due to the autoloading of next chapter feature, where pressing the next chapter button usually works because getting the images of the next chapter would take longer than unloading the last chapter’s images properly, due to wifi latency etc. But this isn’t this case with downloaded chapters because it already has their images, thus loading instantaneous, before the app could have even unloaded the last chapter’s images.

**Comment by FaizanDurrani** [comment]
This should be fixed in 0.8.6-r2, please reopen the issue if it still persists.

**Comment by Ivanmatthew** [comment]
Issue is solved for non-downloaded chapters, but still persists on downloaded chapters.
The debounce/cooldown you put on navigating to next/previous chapters takes too long to block navigation that it will still allow for original reproduction steps to take place.

Most likely solvable by checking the state of the unloading process for last chapter(?)
