### ISSUE TITLE
[REQUEST] Ability to switch between source grouped notification and individual notification

### ISSUE THREAD

**Issue by FaizanDurrani** [Paperback-iOS/app#79]
**Description**
At the moment the notifications are grouped by source (currently only MD). Would like an option  to switch to notifications for individual manga

**How would it improve the App?**
At the moment the grouped notifications aren't really that useful, individual notifications would tell the user which manga updated precisely

**Comment by ConradWeiser** [comment]
Pull request opened, needs tested in an Alpha Build still

**Comment by FaizanDurrani** [comment]
Added in alpha
