### ISSUE TITLE
[BUG] Cache which is storage some information of manga and chapter does not refresh when have an change in information 

### ISSUE THREAD

**Issue by AlanNois** [Paperback-iOS/app#791]
**Describe the bug**
Hello Paperback developers,

I wanted to provide some feedback about a bug I've encountered in version 0.8.3-r2 of Paperback related to caching/storage of information.

Specifically, I've noticed that when information is changed externally, like chapters or manga details updated, the Paperback app does not update its cached information to reflect these changes. The information in the app remains outdated although I force close the app completely.

This seems to be some caching or storage issue where the app is retaining old information and not refreshing it when external changes occur. I believe this worked adequately in previous versions.

It would be great if this could be fixed properly in the main app.

I just wanted to provide this feedback as I'm really enjoying using Paperback otherwise and think it's a fantastic webtoon app! If any logs or additional info would be helpful in diagnosing this caching issue, please let me know.

Appreciate you looking into this and all the great work on Paperback!

Let me know if you would like me to modify or expand this bug report in any way. I'm happy to provide more details on exactly how to reproduce it or any other info that would be helpful. 

**Expected behaviour**
Fix that bug to display the change in information

**App Version**
v0.8.3-r2

**Comment by FaizanDurrani** [comment]
As discussed in the Discord. The app does indeed update the metadata of chapters but holds onto the Date since that date is the date at which the chapter object was created in the app.
