### ISSUE TITLE
[solved]

### ISSUE THREAD

**Issue by jashanpbpb** [Paperback-iOS/app#792]
When i try to open title and scroll for a bit it crashes. I am on the newest version so experimental features is removed. Picture do load and it doesn’t crash unless i scroll.
This problem isn’t due to the new version. I updated the app hoping to solve this issue 

App Version: v0.8.5-r1

**Comment by FaizanDurrani** [comment]
Run DB repair, if that doesnt solve the issue, open a modmail on the discord server by messaging "Support & Modmail" bot.
Discord server: https://discord.paperback.moe

**Comment by jashanpbpb** [comment]
i have already tried it but it doesn’t work

**Comment by jashanpbpb** [comment]
https://github.com/Paperback-iOS/app/assets/123755552/d70612ce-e1f0-4150-80a1-bf05646444b1

**Comment by TheNetsky** [comment]
https://discord.paperback.moe

**Comment by jashanpbpb** [comment]
Tried every single link but it shows invalid discord server Paperback is fixed. I just backed up everything and reinstalled the app

**Comment by TheNetsky** [comment]
> Tried every single link but it shows invalid discord server Paperback is fixed. I just backed up everything and reinstalled the app

100% something on your end or you're banned form the Discord for some reason.
