### ISSUE TITLE
[Ui - BUG] accentColor Buttons/Boxes use bodyTextColor instead of accentTextColor

### ISSUE THREAD

**Issue by chinouvm** [Paperback-iOS/app#793]
**Describe the bug**
I was creating a theme for Paperback and I noticed that buttons in for example the Library section use the bodyTextColor instead of the accentTextColor. This will result in unreadable text on those buttons when creating custom themes.

**Screenshot:**
![](https://i.imgur.com/R2gAUYR.png)

**Expected behaviour**
Buttons using the accentColorText so that the text color can be tweaked to be readable on colorful backgrounds

**App Version**
v0.8.5-r1

**Comment by Celarye** [comment]
+1, have noted this issue before

**Comment by chinouvm** [comment]
It would also be nice if these red boxes with the refresh icon could be changed.
![image](https://github.com/Paperback-iOS/app/assets/80408039/61f7cc45-d173-4174-ad4b-18294a39e565)

**Comment by FaizanDurrani** [comment]
> It would also be nice if these red boxes with the refresh icon could be changed.

The key for that is `buttonNormalBackgroundColor` and `buttonNormalTextColor`
