### ISSUE TITLE
[REQUEST] Collection reader settings

### ISSUE THREAD

**Issue by StateFarmTaxes** [Paperback-iOS/app#794]
**Description**
Allows users to change title reader settings such as whether its horizontal or vertical within the collection settings.

**How would it improve the App?**
It would improve the app via quality of life. It would make users who use collection read with different reader settings based on what the titles call for more better and not have to go to each title to change their reader setting.

**Additional context**
N/A

**Comment by FaizanDurrani** [comment]
Will not be implemented anytime soon. For quick mode swap use the button in the reader.
