### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sunuiyum** [Paperback-iOS/app#795]
When I search for any new manga, I'm met with the below error:

"Paperback: JSValue is not a Promise or resolved value [PaperbackError(200)] JSValue is not a Promise or resolved value"

The app otherwise functions OK (e.g., the manga already in my library continues to update).

I'm on App Version v0.7-r52.
![IMG_8694FE5AA431-1](https://github.com/Paperback-iOS/app/assets/141067853/6c654103-9440-4ef0-8f5f-2405142ea79f)

**Comment by chinouvm** [comment]
This could be due to a faulty source. Maybe remove and add them one by one to see which one is faulty.

**Comment by TheNetsky** [comment]
Source issue
