### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jhjosephcho** [Paperback-iOS/app#797]
**Describe the bug**
The IOS app crashes when manually trying to fetch updates in library. 

**To Reproduce**
Go to library and swipe down to fetch updates. Click yes on prompt. 

**Expected behaviour**
Expect the library to fetch new updates. 

**App Version**
Eg: v0.8.6-r2

**Screenshots**
N/A

**Comment by FaizanDurrani** [comment]
Run db repair from settings, reopen if the issue persists

**Comment by jhjosephcho** [comment]
Just tried and it won't let me run db repair. Crashes when I try.

**Comment by FaizanDurrani** [comment]
Try making a backup

**Comment by jhjosephcho** [comment]
When I press New Backup the app crashes but when I go back to the Backups section I see this new file. Does this mean the backup worked?
![image](https://github.com/Paperback-iOS/app/assets/30779935/926123d2-341e-496a-ae18-b2f38b580260)

**Comment by jhjosephcho** [comment]
This issue started for me after the most recent update.

**Comment by FaizanDurrani** [comment]
Uh join the Discord and open a support post https://discord.paperback.moe
