### ISSUE TITLE
[BUG] Make the reader respect the "Hide Other Groups" option.

### ISSUE THREAD

**Issue by amenokagaseo** [Paperback-iOS/app#801]
### Preflight Checklist

- [X] I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
- [X] I am sure that my feature request has nothing to with third party extensions.
- [X] I am using the latest available Paperback version (currently 0.8).
- [X] I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a feature request that matches the one I want to file, without success.

### What type of Apple device is the feature request for?

All device types

### Describe the feature

Currently, the reader doesn't respect the Hide Other Groups setting, which makes it such that attempting to read a very long series consistently is difficult when the only source available has multiple groups uploaded to it. The only way to go about it as of now is to back out to the chapter select at every single chapter and then reselect the next chapter from the same group. This makes it very annoying to read comics that have upwards of hundreds of issues uploaded by multiple groups on the same source, especially if that source has source-side login implementation to block specific groups.

### Feature Motivation

It would remove the need for backing out of chapters every time one wanted to move to the next chapter of a specific source. Currently, the way that the reader handles chapter switching ignores group priority and simply moves to the first uploaded chapter, which is honestly a really bad implementation since it generally ends up moving to a low-quality result on most sources due to group sniping.

### Anything Else?

I'd like to briefly acknowledge a feature added in the public release of the 0.8 update, which implemented the functionality to automatically ignore other chapters with the same number from different sources and simply move to the next available upload of the next chapter, which is not a solution to the actual problem at hand and instead creates more frustration when trying to read consistently. Not only is this poorly implemented, but it's not a toggle, which creates anti-user functionality.

**Comment by FaizanDurrani** [comment]
The reader should already be respecting group priority and the hide other groups toggle, if it is not then it is a bug
Can you attach a recording showcasing the issue?

**Comment by amenokagaseo** [comment]
I don't really have any non-copyrighted content that I can provide a recording of, but after further inspection I've found that this issue manifests differently on a per-source basis and may actually be a source bug rather than a reader bug.

Namely, on Komga, it works as intended, where supplying multiple chapters with different groups and enabling "Hide Other Groups", it simply moves to the next available chapter, functioning normally. However, enabling the option on community-made sources has vastly different results, such as either refusing to move to the next chapter (simply displaying END at the end of each chapter and forcing the user to back out) or moving to a hidden chapter from a different group.

This leads me to assume that the logic behind this behaviour is handled by the source, and not the app itself, right? Because if not then there's definitely something weird going on.

**Comment by FaizanDurrani** [comment]
The source needs to provide the same chapter number and volume number with a different group for the app to consider it as the same chapter but by a different group.

Definitely a source issue.
