### ISSUE TITLE
[FEATURE REQUEST]: Bookmark chapters

### ISSUE THREAD

**Issue by hyoretsu** [Paperback-iOS/app#803]
### Preflight Checklist

- [X] I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
- [X] I am sure that my feature request has nothing to with third party extensions.
- [X] I am using the latest available Paperback version (currently 0.8).
- [X] I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a feature request that matches the one I want to file, without success.

### What type of Apple device is the feature request for?

All device types

### Describe the feature

A simple favorite/tag chapter feature. Normally I'd say it also prevented auto chapter deletion, but since we need to manually delete chapters in Paperback as of now, that's just something to keep in mind.

### Feature Motivation

It'd give the user a little more freedom I guess. It's a good feature to have, and I imagine it isn't hard to implement.

**Comment by FaizanDurrani** [comment]
I have no clue what this means, elaborate further on the feature. Give examples scenarios and use-cases.

**Comment by hyoretsu** [comment]
It's basically a generic tag on a chapter, it's a feature from Tachiyomi. Use case is remembering good chapters and such, used it a lot on Tachiyomi.
![image](https://github.com/Paperback-iOS/app/assets/20804322/275a31b1-5a5e-4bcb-a1b3-4d896de0ed6d)

I'm closing this issue though, since after remembering the actual name of this feature I saw that there's already an issue for that #159.
