### ISSUE TITLE
[REQUEST] Refresh/fetch manga in Follows with a pull-to-refresh gesture

### ISSUE THREAD

**Issue by ghost** [Paperback-iOS/app#81]
**Description**
Pulling down the page to refresh/fetch the manga in the Follows page. Maybe this can be tied in with #36 to allow the same functionality in Discover & chapter lists.

**How would it improve the App?**
Reaching all the way to the refresh button on the top is a bit of a hassle for (bigger screen) iPad users.

**Additional context**
N/A

**Comment by FaizanDurrani** [comment]
Feature present in 0.3.0 (2.2.0-Alpha)
