### ISSUE TITLE
[REQUEST] Secondary click in bottom navigation bar to go back to the main screen

### ISSUE THREAD

**Issue by ghost** [Paperback-iOS/app#82]
**Description**
When you have a manga info/chapter pane open in Discover/Follows, clicking the button in the bottom navigation bar again makes you go back to the main screen of the tab.

**How would it improve the App?**
Not having to reach to the back button on the top would be great for (bigger screen) iPad users.

**Additional context**
It would have the same functionality as the clicking the back button on the top.

_As example:_
In Discover, you have the info/chapter pane of a manga open, instead of clicking the back button at the top of the screen, you can click the Discover (tab) button in the bottom navigation bar to go back to the main Discover screen.

**Comment by FaizanDurrani** [comment]
Another one of SwiftUI’s TabView limitation. I’ll see if I can switch to UIKit tabview.

**Comment by carlobonandrini** [comment]
I would opt for swiping from the left to the right of the screen to go back. Just saying

**Comment by FaizanDurrani** [comment]
The implementation of how the app navigates has changed drastically since this issue was opened.
