### ISSUE TITLE
[FEATURE REQUEST] Chapter Number Sorting

### ISSUE THREAD

**Issue by george-emerald** [Paperback-iOS/app#820]
### Preflight Checklist

- [X] I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
- [X] I am sure that my feature request has nothing to with third party extensions.
- [X] I am using the latest available Paperback version (currently 0.8).
- [X] I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a feature request that matches the one I want to file, without success.

### What type of Apple device is the feature request for?

iPad

### Describe the feature

Paperback needs a sort-by-chapter-number function. I'm not entirely sure what it's using currently but it makes long titles with multiple releases like Detective Conan unreadable.

### Feature Motivation

Long titles with releases of older chapters mixed in with newer chapters will be readable on the app.

**Comment by Celarye** [comment]
iirc Paperback sorts by the chapter numbers given by the source, so it's for the source to provide it properly. Contact the source dev and see of something can be improved there.

**Comment by george-emerald** [comment]
Now where can I find nar1n, the developer of the MangaDex extension?

**Comment by Celarye** [comment]
Refrain from mentioning third party sources, we're not allowed to help you with them here. And you should try to contact the devs in the same place you got the third party source from.
