### ISSUE TITLE
[BUG] Not visible in "Austria" App Store

### ISSUE THREAD

**Issue by radaiko** [Paperback-iOS/app#821]
### Preflight Checklist

- [X] I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
- [X] I am sure that my bug has nothing to with third party extensions.
- [X] I have read the [troubleshooting FAQs](https://paperback.moe/help/faq/) and looked trough the \#help-desk channel on the [official Discord](https://discord.com/invite/Paperback), but none solved my issue.
- [X] I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a bug report that matches the one I want to file, without success.

### What type of Apple device have you encountered the bug with?

All device types

### Operating System Version

iOS 17.1

### App Version

None

### Describe the Bug

I can't find the app in the App Store. It's possible to find it in Safari but as soon as I switch to the App Store I get the message not available in your country or region.

### Steps to Reproduce

Use a device with country set to "Austria"

**Comment by TheNetsky** [comment]
Not a bug, app is just not in that store. Switch App Store regions. Else join the Patreon.
