### ISSUE TITLE
[FEATURE REQUEST]  More theme customisation

### ISSUE THREAD

**Issue by GabrielCWT** [Paperback-iOS/app#828]
### Preflight Checklist

- [X] I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
- [X] I am sure that my feature request has nothing to with third party extensions.
- [X] I am using the latest available Paperback version (currently 0.8).
- [X] I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a feature request that matches the one I want to file, without success.

### What type of Apple device is the feature request for?

iPhone

### Describe the feature

Certain text colours cannot be customised e.g. clear button in search and in history.
Chapter notifications (red) in library cannot be changed
Chapter notification (red bar on left) on page for a manga cannot be changed (Refer to image for this)
![IMG_4194](https://github.com/Paperback-iOS/app/assets/77312579/8ae8b1c5-8422-4243-9b93-78e3f2172a34)

### Feature Motivation

Pleasing to the eyes when using custom themes

**Comment by Celarye** [comment]
Duplicate (is mentioned in it) of #719

**Comment by GabrielCWT** [comment]
Dim twitter from your theme repo ;).

Anyways closing this since it's a duplicate
