### ISSUE TITLE
[FEATURE REQUEST] Crashes when opening download manager

### ISSUE THREAD

**Issue by DylanBT928** [Paperback-iOS/app#838]
### Preflight Checklist

- [X] I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
- [X] I am sure that my bug has nothing to with third party extensions.
- [X] I have read the [troubleshooting FAQs](https://paperback.moe/help/faq/) and looked trough the \#help-desk channel on the [official Discord](https://discord.com/invite/Paperback), but none solved my issue.
- [X] I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a bug report that matches the one I want to file, without success.

### What type of Apple device have you encountered the bug with?

iPhone

### Operating System Version

iOS 17.2.1

### App Version

v0.8.7-r12

### Describe the Bug

App crashes upon opening the download manager.

### Steps to Reproduce

1. Open the app
2. Go to settings
3. Click on download manager

### Anything Else?

https://github.com/Paperback-iOS/app/assets/75633077/230fdfcf-8dfd-41b6-88db-fafc5f88fbc7

**Comment by XenitXTD** [comment]
This is generally fixed with a repair database, have you tried that?

**Comment by DylanBT928** [comment]
@XenitXTD Just did a database repair and it seems to be working now. Thank you!
