### ISSUE TITLE
[BUG] - Can’t load PDFs from Komga server

### ISSUE THREAD

**Issue by chaseofbase** [Paperback-iOS/app#851]
### Preflight Checklist

- [X] I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
- [X] I am sure that my bug has nothing to with third party extensions.
- [X] I have read the [troubleshooting FAQs](https://paperback.moe/help/faq/) and looked trough the \#help-desk channel on the [official Discord](https://discord.com/invite/Paperback), but none solved my issue.
- [X] I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a bug report that matches the one I want to file, without success.

### What type of Apple device have you encountered the bug with?

iPad

### Operating System Version

iPad OS 17.6.1

### App Version

0.8.8-r31

### Describe the Bug

I can successfully connected the app to my Komga server and read image-based content (from .zip archives of jpgs) but attempting to load any PDF content gives me this error:

paperback:%20Processing%20image%20failed.%20Processor%3A%20WebPProcessor%20(identifier%3A%0A%22com.yeatse%20WebPProcessor%22).%20Processing%20item%3A%20data%20(1488320%20bytes).%0AKingfisher.KingfisherError.processorError/reason:%0AKingfisher.KingfisherError.ProcessorErrorReason.processingFailed%20(processor:%0AKingfisherWebP.WebPProcessoridentifier:%20%22com.yeatse.WebPProcessor%22),%20item:%0AKingfisher.ImageProcess%7Ctem.data(1488320 bytes)))

### Steps to Reproduce

1. Connect to remote Komga server
2. Attempt to load PDF content to read in app

**Comment by Celarye** [comment]
PDFs are not supported in the 0.8 reader, but 0.9.0 is currently in it's alpha phase and will support different types of readers down the line (feature for 0.9.x and not 0.9.0). We recommend that you bring this up again once 0.9.0 reaches the stable phase.
