### ISSUE TITLE
[BUG] Orientation Lock

### ISSUE THREAD

**Issue by LettuceJuice** [Paperback-iOS/app#853]
### Preflight Checklist

- [X] I have read and I agree to follow the [support disclaimer](https://github.com/Paperback-iOS/app#support-disclaimer).
- [X] I am sure that my bug has nothing to with third party extensions.
- [X] I have read the [troubleshooting FAQs](https://paperback.moe/help/faq/) and looked trough the \#help-desk channel on the [official Discord](https://discord.com/invite/Paperback), but none solved my issue.
- [X] I have searched the [issue tracker](https://github.com/Paperback-iOS/app/issues) for a bug report that matches the one I want to file, without success.

### What type of Apple device have you encountered the bug with?

iPhone

### Operating System Version

iOS 16.7.2

### App Version

0.8.8-r31

### Describe the Bug

Orientation lock stops working when receiving an error popup while reading a chapter. Must be disabled and re-enabeld for it to work again inside the chapter. I have only experienced this in vertical lock mode as I don't use it in horizontal mode.

### Steps to Reproduce

1. Have orientation lock on.
2. Rotate device into landscape.
3. Receive error popup.

**Comment by Celarye** [comment]
Bugs like these will not be fixed in 0.8, but 0.9 is currently in it's alpha phase. We recommend that you check this out in 0.9 once it reaches the beta or stable phase.
