### ISSUE TITLE
[REQUEST] Double Tap to Zoom For Better 4-Koma Reading Experience

### ISSUE THREAD

**Issue by joelfong** [Paperback-iOS/app#87]
**Description**
For portrait orientation, it would be good to have a feature where one can double tap to zoom into a page. Ideally so that 50% of the page width will fit in the device width. 

**How would it improve the App?**
Many 4-koma manga have 2 vertical strips of 4 frames. This feature will allow for a much better 4-koma reading experience, similar to that of MR, where one can much more easily read and follow the vertical 4-koma frames. 

**Additional context**
![1-Before Zoom](https://user-images.githubusercontent.com/25445388/80305982-f4602b00-87f2-11ea-8ec8-710138a57e77.PNG)

![2-After Zoom](https://user-images.githubusercontent.com/25445388/80305988-fa560c00-87f2-11ea-9c14-1b5df56eacc9.PNG)

**Comment by joelfong** [comment]
Currently in 0.3.0-b4 it looks like it zooms to 100% for 1 single page when double-tapped. This really defeats the purpose of any zoom since it zooms too much, and it also seems that the scaling is based off the resolution of the first page. 

Some chapters have pages of varying resolutions and if the subsequent pages are of a lower resolution, it gets scaled up hilariously to a pixelated form when zoomed in. 

![IMG_1582](https://user-images.githubusercontent.com/25445388/80954378-d5cfe480-8e2f-11ea-9864-57a60e937d3e.PNG)

![IMG_1581](https://user-images.githubusercontent.com/25445388/80954383-d799a800-8e2f-11ea-953f-b495a4dede27.PNG)

Furthermore zooming in to 1 single page is pointless if it is restricted to the original page frame and doesn't affect the zoom for the rest of the pages.

How do you expect people to read anything if the reader is like this?

![IMG_1580](https://user-images.githubusercontent.com/25445388/80951854-40caec80-8e2b-11ea-8eeb-61729021eb29.PNG)

There's a reason why many people prefer mangarock's implementation of double-tap to zoom. It doesn't depend on the page resolution, which can vary significantly depending on the source. Instead it does a consistent scaling across all manga to let 50% of the page fit within the device width. And if you read right to left, it also aligns the zoomed pages such that all subsequent pages are also zoomed in and aligned to the right for easy reading from the previous page. 

The developers behind mangarock understand how people read manga and they do all they can to make it a great and intuitive experience. They understand UI/UX design deeply. 

I'm glad you are taking our feedback seriously and are trying to implement them as best you can, but you need to understand the intent behind these features, instead of just adding a feature for the sake of adding a feature. 

Right now you are doing the job of a programmer, but also a UI/UX designer. I would suggest taking some time to really define how you want people to experience using the app. Think about different kinds of manga, how different people may read them differently on different devices in different orientations. How can you make reading manga a good and consistent experience across all of these cases?

Don't just add features based on a list. Solve the UI/UX design, and you will know exactly what features you need to implement and be able to code for it properly.

**Comment by FaizanDurrani** [comment]
Added in 0.4.0 (2.2.9-Alpha)
