### ISSUE TITLE
[REQUEST] Content In Landscape Orientation To Be Within Safe Area

### ISSUE THREAD

**Issue by joelfong** [Paperback-iOS/app#88]
**Description**
Current landscape orientation has the page width equal to the device screen width. However, for iPhones with a notch, this means there is content being blocked by the notch. iOS guidelines for Safe Areas should be followed so that all content is visible regardless of device. 

**How would it improve the App?**
Improved readability for iPhones with notch. 

**Additional context**
MR has a good implementation of this. It actually has a default scaling that has the page width smaller than the safe area width. I suspect this follows the aspect ratio of the older iPhones without notch. This also allows for more content to be seen at once on notched device, which is a nice feature to have. If the user double taps, it zooms in to fill the safe area. And the user is free to pinch to zoom to have it fill the whole screen if he/she so desires. 

![1-Default Landscape](https://user-images.githubusercontent.com/25445388/80306233-8e74a300-87f4-11ea-9e4a-e35784add40f.PNG)

![2-Double Tap to fill safe area](https://user-images.githubusercontent.com/25445388/80306239-959bb100-87f4-11ea-95fe-595f21f8f29c.PNG)

![3-Manual Pinch to Zoom](https://user-images.githubusercontent.com/25445388/80306241-96ccde00-87f4-11ea-8eb5-610b8705ca72.PNG)

**Comment by ImOldGregg** [comment]
https://github.com/FaizanDurrani/Paperback-Public/issues/76

**Comment by ImOldGregg** [comment]
Something like that?

**Comment by FaizanDurrani** [comment]
It's similar I guess but both have a different take on the problem

**Comment by joelfong** [comment]
I feel #76 is more for iPads, to have custom scaling to show more content, particularly for webtoons. But this is more for notched devices with respecting safe areas rather than deliberately adding padding. The primary aim is to prevent any content from being blocked by the notch, and we all know how apple loves notches on the iPhone. Showing more content is just a side benefit if any.

**Comment by ImOldGregg** [comment]
Yeah it shouldn't be hard to implement this one. Just set default outside notch and double tap to zoom full screen. My request may be a little more tricky depending on how you go about it lol hopefully paper wont hate me for it 😅

**Comment by ImOldGregg** [comment]
I haven’t actually tested with my phone tho so I completely missed that issue.

**Comment by FaizanDurrani** [comment]
Implemented in Alpha as "Pillarboxing"
