### ISSUE TITLE
[REQUEST] Filter out duplicate chapters

### ISSUE THREAD

**Issue by Pixelatex** [Paperback-iOS/app#93]
**Description**
Some manga's have 3-4 versions of say chapter 5 because they were uploaded by different groups.

Could we make some way to hide these, select a scanlation group filter on top,... some kind of way to only show chapter 1 to x without duplicates.

**How would it improve the App?**
This will improve the experience for readers who are bulk reading a new manga/re-reading an older one as they don't have to accidentally open the same chapter twice of more.

**Comment by acknologia** [comment]
also possibly filtering out chapters that will come out later.

too often do i see "updated" manga that actually just says next chapter will be out in X hours or days.

**Comment by ConradWeiser** [comment]
Both of these comments are explicitly a MangaDex problem. Other sources don't tend to have this problem. As such, building this functionality into the app as an edge case is something which probably needs to be debated over a little more.

> too often do i see "updated" manga that actually just says next chapter will be out in X hours or days.
This problem is something which can/should be fixed in the MangaDex source itself. I'll see about bringing it up at some point. This 'can' be fixed easily.

**Comment by Ekomonster** [comment]
> Both of these comments are explicitly a MangaDex problem. Other sources don't tend to have this problem. As such, building this functionality into the app as an edge case is something which probably needs to be debated over a little more.
> 
> > too often do i see "updated" manga that actually just says next chapter will be out in X hours or days.
> 
> This problem is something which can/should be fixed in the MangaDex source itself. I'll see about bringing it up at some point. This 'can' be fixed easily.

Its not only mangadex but also Mangapark and which I believe is quite common for the source. 
[This video](https://discord.com/channels/673606787290759230/757959539051069591/796038924686196806) shows what I am talking about but this is also very common with Mangadex.

**Comment by PythonCoderAS** [comment]
I think the current approach with the MangaDex extension can be copied to other extensions.

**Comment by FaizanDurrani** [comment]
This is fixed in the recent update to the source
