### ISSUE TITLE
[REQUEST] Ability to export/import backups

### ISSUE THREAD

**Issue by FaizanDurrani** [Paperback-iOS/app#94]
**Description**
Ability to export backups would help in accidental data loss caused by human error (tapping the wrong resolving option while syncing) or transferring to another app (Neko for example)

**How would it improve the App?**
<Description>

**Comment by ConradWeiser** [comment]
Can be marked as completed

**Comment by FaizanDurrani** [comment]
Added in v0.3.0-b7
