### ISSUE TITLE
[REQUEST] A way to reload pages that failed to load 

### ISSUE THREAD

**Issue by Benwor28** [Paperback-iOS/app#95]
**Description**. A way to reload a page that has failed to load would be great.

**How would it improve the App?**
Not having to interrupt ones flow of reading is normally a good thing.

**Additional context**
Tapping the failed page could be a way reload it, also maybe change the graphic of a failed page to indicate that one could tap it

**Comment by ConradWeiser** [comment]
Present in v0.5
