### ISSUE TITLE
[REQUEST] Tap the manga covers for a full-screen view of them

### ISSUE THREAD

**Issue by gameherob** [Paperback-iOS/app#98]
**Description**
Exactly what the title says, maybe even an option to choose what cover is displayed in the follows menu.

**How would it improve the App?**
I think it would be a nice addiction, and if there was the option to choose a cover it will add to the overall customizability of the app

**Comment by FaizanDurrani** [comment]
Implemented in 0.4.0 (2.2.12-Alpha)
