### ISSUE TITLE
[REQUEST] Recent tab

### ISSUE THREAD

**Issue by Snypaz26** [Paperback-iOS/app#99]
**Description**
A clear description of the feature

Create a recent tab that u can back to read previous manga u read makes it easier like manga rock 

**How would it improve the App?**
How would the feature improve the app?

**Additional context**
![624EF4A5-970D-4DB5-9CE3-58E1FC722E71](https://user-images.githubusercontent.com/64497251/80528172-84bd7d80-8963-11ea-9e87-9f1039aa435f.png)

**Comment by acknologia** [comment]
if possible keeping track of when manga was last read also would be really handy

**Comment by FaizanDurrani** [comment]
Added in b8
